using System.Text;
using Microsoft.CodeAnalysis;

namespace TeleFlow.Generators;

public sealed partial class TelegramHandlerSourceGenerator
{
    private static string GenerateSource(
        IReadOnlyList<GeneratedHandlerMethod> handlers,
        IReadOnlyList<GeneratedErrorHandlerMethod> errorHandlers)
    {
        StringBuilder builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("[assembly: global::TeleFlow.Telegram.TelegramGeneratedHandlersAttribute(typeof(global::TeleFlow.Generated.TelegramGeneratedHandlersRegistrar))]");
        builder.AppendLine();
        builder.AppendLine("namespace TeleFlow.Generated;");
        builder.AppendLine();
        builder.AppendLine("internal sealed class TelegramGeneratedHandlersRegistrar : global::TeleFlow.Telegram.ITelegramGeneratedHandlerRegistrar");
        builder.AppendLine("{");
        builder.AppendLine("    public void Register(global::TeleFlow.Telegram.ITelegramGeneratedHandlerRegistry registry)");
        builder.AppendLine("    {");

        int descriptorIndex = 0;

        for (int handlerIndex = 0; handlerIndex < handlers.Count; handlerIndex++)
        {
            foreach (GeneratedRoute route in handlers[handlerIndex].Routes)
            {
                AppendRegistration(builder, handlers[handlerIndex], route, handlerIndex, descriptorIndex);
                descriptorIndex++;
            }
        }

        int errorDescriptorIndex = 0;

        for (int handlerIndex = 0; handlerIndex < errorHandlers.Count; handlerIndex++)
        {
            foreach (string? exceptionType in errorHandlers[handlerIndex].ExceptionTypes)
            {
                AppendErrorRegistration(
                    builder,
                    errorHandlers[handlerIndex],
                    exceptionType,
                    handlerIndex,
                    errorDescriptorIndex);
                errorDescriptorIndex++;
            }
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        for (int index = 0; index < handlers.Count; index++)
        {
            AppendInvoker(builder, handlers[index], index);
        }

        for (int index = 0; index < errorHandlers.Count; index++)
        {
            AppendErrorInvoker(builder, errorHandlers[index], index);
        }

        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string GenerateStateGroupsSource(IReadOnlyList<GeneratedStateGroup> groups)
    {
        StringBuilder builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        foreach (IGrouping<string?, GeneratedStateGroup> namespaceGroup in groups.GroupBy(static group => group.Namespace, StringComparer.Ordinal))
        {
            if (!string.IsNullOrWhiteSpace(namespaceGroup.Key))
            {
                builder.AppendLine($"namespace {namespaceGroup.Key};");
                builder.AppendLine();
            }

            foreach (GeneratedStateGroup group in namespaceGroup)
            {
                builder.Append(group.Accessibility);
                builder.Append(' ');

                if (group.IsStatic)
                {
                    builder.Append("static ");
                }

                builder.Append("partial class ");
                builder.AppendLine(group.TypeName);
                builder.AppendLine("{");

                foreach (GeneratedStateProperty state in group.States)
                {
                    builder.Append("    public static partial global::TeleFlow.Framework.States.State ");
                    builder.Append(state.Name);
                    builder.Append(" => global::TeleFlow.Framework.States.State.Create(");
                    builder.Append(ToLiteral($"{group.Prefix}:{state.Segment}"));
                    builder.AppendLine(");");
                }

                builder.AppendLine("}");
                builder.AppendLine();
            }
        }

        return builder.ToString();
    }

    private static void AppendRegistration(
        StringBuilder builder,
        GeneratedHandlerMethod handler,
        GeneratedRoute route,
        int invokerIndex,
        int descriptorIndex)
    {
        builder.AppendLine("        registry.RegisterHandler(new global::TeleFlow.Telegram.TelegramGeneratedHandlerDescriptor(");
        builder.AppendLine($"            typeof({handler.HandlerTypeName}),");
        builder.AppendLine($"            {ToLiteral(handler.MethodName)},");
        builder.AppendLine($"            global::TeleFlow.Telegram.TelegramGeneratedHandlerKind.{route.Kind},");
        builder.AppendLine($"            global::TeleFlow.Telegram.TelegramGeneratedRouteKind.{route.RouteKind},");
        builder.AppendLine($"            {ToNullableLiteral(route.Pattern)},");
        builder.AppendLine("            new string[]");
        builder.AppendLine("            {");

        foreach (string prefix in route.CommandPrefixes)
        {
            builder.AppendLine($"                {ToLiteral(prefix)},");
        }

        builder.AppendLine("            },");
        builder.AppendLine($"            {ToBoolLiteral(route.AllowSpaceAfterPrefix)},");
        builder.AppendLine($"            {ToBoolLiteral(route.IgnoreCase)},");
        builder.AppendLine($"            {descriptorIndex},");
        builder.AppendLine($"            {ToNullableLiteral(handler.ModuleName)},");
        builder.AppendLine($"            {ToNullableLiteral(route.Command)},");
        builder.AppendLine($"            {ToTypeOfNullable(handler.CallbackPayloadType)},");
        builder.AppendLine("            new global::TeleFlow.Telegram.TelegramGeneratedTextFilterDescriptor[]");
        builder.AppendLine("            {");

        foreach (GeneratedTextFilter filter in route.TextFilters)
        {
            builder.AppendLine(
                $"                new global::TeleFlow.Telegram.TelegramGeneratedTextFilterDescriptor({ToLiteral(filter.Value)}, (global::TeleFlow.Annotations.TextMatchMode){filter.Mode}, {ToBoolLiteral(filter.IgnoreCase)}),");
        }

        builder.AppendLine("            },");
        builder.AppendLine("            new global::TeleFlow.Telegram.TelegramGeneratedFilterDescriptor[]");
        builder.AppendLine("            {");

        foreach (GeneratedFilter filter in route.Filters)
        {
            AppendFilter(builder, filter);
        }

        builder.AppendLine("            },");
        builder.AppendLine("            new global::TeleFlow.Telegram.TelegramGeneratedChatMemberTransitionDescriptor[]");
        builder.AppendLine("            {");

        foreach (GeneratedChatMemberTransition transition in route.ChatMemberTransitions)
        {
            builder.AppendLine(
                $"                new global::TeleFlow.Telegram.TelegramGeneratedChatMemberTransitionDescriptor((global::TeleFlow.Annotations.TelegramMemberStatusSet){transition.OldStatus}, (global::TeleFlow.Annotations.TelegramMemberStatusSet){transition.NewStatus}),");
        }

        builder.AppendLine("            },");
        builder.AppendLine("            new global::TeleFlow.Telegram.TelegramGeneratedRoleRequirementDescriptor[]");
        builder.AppendLine("            {");

        foreach (int requirement in route.RoleRequirements)
        {
            builder.AppendLine(
                $"                new global::TeleFlow.Telegram.TelegramGeneratedRoleRequirementDescriptor((global::TeleFlow.Annotations.TelegramMemberStatusSet){requirement}),");
        }

        builder.AppendLine("            },");
        builder.AppendLine("            new string[]");
        builder.AppendLine("            {");

        foreach (string state in handler.States)
        {
            builder.AppendLine($"                {ToLiteral(state)},");
        }

        builder.AppendLine("            },");
        builder.AppendLine("            new global::TeleFlow.Telegram.TelegramGeneratedHandlerParameterDescriptor[]");
        builder.AppendLine("            {");

        foreach (GeneratedParameter parameter in handler.Parameters)
        {
            builder.AppendLine(
                $"                new global::TeleFlow.Telegram.TelegramGeneratedHandlerParameterDescriptor(typeof({parameter.TypeName}), global::TeleFlow.Telegram.TelegramGeneratedHandlerParameterKind.{parameter.Kind}, {ToLiteral(parameter.Name)}),");
        }

        builder.AppendLine("            },");
        builder.AppendLine($"            Invoke_{invokerIndex},");
        builder.AppendLine($"            {ToNullableLiteral(handler.SceneName)},");
        builder.AppendLine("            new global::TeleFlow.Telegram.TelegramGeneratedRouteValueDescriptor[]");
        builder.AppendLine("            {");

        if (route.RouteValues.Values.Any(static value => value.Constraint is not null))
        {
            foreach (KeyValuePair<string, GeneratedRouteValue> routeValue in route.RouteValues.OrderBy(static value => value.Key, StringComparer.Ordinal))
            {
                builder.AppendLine(
                    $"                new global::TeleFlow.Telegram.TelegramGeneratedRouteValueDescriptor({ToLiteral(routeValue.Key)}, typeof({GetRouteValueTypeName(routeValue.Value)}), {ToBoolLiteral(routeValue.Value.IsOptional)}),");
            }
        }

        builder.AppendLine("            },");
        AppendAutoAnswerCallback(builder, handler.AutoAnswerCallback);
        builder.AppendLine("            ));");
    }

    private static void AppendAutoAnswerCallback(
        StringBuilder builder,
        GeneratedAutoAnswerCallback? autoAnswerCallback)
    {
        if (autoAnswerCallback is null)
        {
            builder.AppendLine("            null");
            return;
        }

        builder.AppendLine("            new global::TeleFlow.Telegram.TelegramGeneratedAutoAnswerCallbackDescriptor(");
        builder.AppendLine($"                enabled: {ToBoolLiteral(autoAnswerCallback.Enabled)},");
        builder.AppendLine($"                text: {ToNullableLiteral(autoAnswerCallback.Text)},");
        builder.AppendLine($"                showAlert: {ToBoolLiteral(autoAnswerCallback.ShowAlert)})");
    }

    private static void AppendFilter(
        StringBuilder builder,
        GeneratedFilter filter)
    {
        if (filter.CustomTypeName is not null)
        {
            if (filter.CustomAttributeExpression is null)
            {
                builder.AppendLine(
                    $"                new global::TeleFlow.Telegram.TelegramGeneratedFilterDescriptor(typeof({filter.CustomTypeName}), typeof({filter.CustomContextTypeName})),");
            }
            else
            {
                builder.AppendLine(
                    $"                new global::TeleFlow.Telegram.TelegramGeneratedFilterDescriptor(typeof({filter.CustomTypeName}), typeof({filter.CustomContextTypeName}), {filter.CustomAttributeExpression}),");
            }

            return;
        }

        builder.AppendLine("                new global::TeleFlow.Telegram.TelegramGeneratedFilterDescriptor(");
        builder.AppendLine($"                    global::TeleFlow.Telegram.TelegramGeneratedFilterKind.{filter.Kind},");
        builder.AppendLine("                    new string[]");
        builder.AppendLine("                    {");

        foreach (string value in filter.StringValues)
        {
            builder.AppendLine($"                        {ToLiteral(value)},");
        }

        builder.AppendLine("                    },");
        builder.AppendLine("                    new long[]");
        builder.AppendLine("                    {");

        foreach (long value in filter.LongValues)
        {
            builder.AppendLine($"                        {value}L,");
        }

        builder.AppendLine("                    }),");
    }

    private static void AppendErrorRegistration(
        StringBuilder builder,
        GeneratedErrorHandlerMethod handler,
        string? exceptionType,
        int invokerIndex,
        int descriptorIndex)
    {
        builder.AppendLine("        registry.RegisterErrorHandler(new global::TeleFlow.Telegram.TelegramGeneratedErrorHandlerDescriptor(");
        builder.AppendLine($"            typeof({handler.HandlerTypeName}),");
        builder.AppendLine($"            {ToLiteral(handler.MethodName)},");
        builder.AppendLine($"            exceptionType: {ToTypeOfNullable(exceptionType)},");
        builder.AppendLine($"            telegramContextType: {ToTypeOfNullable(handler.TelegramContextType)},");
        builder.AppendLine($"            registrationOrder: {descriptorIndex},");
        builder.AppendLine($"            moduleName: {ToNullableLiteral(handler.ModuleName)},");
        builder.AppendLine("            parameters: new global::TeleFlow.Telegram.TelegramGeneratedErrorHandlerParameterDescriptor[]");
        builder.AppendLine("            {");

        foreach (GeneratedErrorParameter parameter in handler.Parameters)
        {
            builder.AppendLine(
                $"                new global::TeleFlow.Telegram.TelegramGeneratedErrorHandlerParameterDescriptor(typeof({parameter.TypeName}), global::TeleFlow.Telegram.TelegramGeneratedErrorHandlerParameterKind.{parameter.Kind}, {ToLiteral(parameter.Name)}),");
        }

        builder.AppendLine("            },");
        builder.AppendLine($"            invoker: InvokeError_{invokerIndex}));");
    }

    private static void AppendInvoker(StringBuilder builder, GeneratedHandlerMethod handler, int index)
    {
        builder.AppendLine($"    private static async global::System.Threading.Tasks.ValueTask Invoke_{index}(");
        builder.AppendLine("        global::System.IServiceProvider services,");
        builder.AppendLine("        object?[] arguments,");
        builder.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        builder.AppendLine(
            $"        var handler = ({handler.HandlerTypeName})(services.GetService(typeof({handler.HandlerTypeName})) ?? throw new global::System.InvalidOperationException({ToLiteral($"Telegram handler '{handler.HandlerTypeMetadataName}' is not registered in the current service provider.")}));");
        builder.Append("        await handler.");
        builder.Append(handler.MethodName);
        builder.Append('(');

        for (int parameterIndex = 0; parameterIndex < handler.Parameters.Length; parameterIndex++)
        {
            if (parameterIndex > 0)
            {
                builder.Append(", ");
            }

            GeneratedParameter parameter = handler.Parameters[parameterIndex];
            builder.Append('(');
            builder.Append(parameter.TypeName);
            builder.Append($")arguments[{parameterIndex}]!");
        }

        builder.AppendLine(").ConfigureAwait(false);");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void AppendErrorInvoker(StringBuilder builder, GeneratedErrorHandlerMethod handler, int index)
    {
        string asyncKeyword = handler.ReturnKind == GeneratedErrorReturnKind.Sync ? string.Empty : "async ";

        builder.AppendLine($"    private static {asyncKeyword}global::System.Threading.Tasks.ValueTask<global::TeleFlow.Telegram.TelegramErrorHandlingResult> InvokeError_{index}(");
        builder.AppendLine("        global::System.IServiceProvider services,");
        builder.AppendLine("        object?[] arguments,");
        builder.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        builder.AppendLine(
            $"        var handler = ({handler.HandlerTypeName})(services.GetService(typeof({handler.HandlerTypeName})) ?? throw new global::System.InvalidOperationException({ToLiteral($"Telegram error handler '{handler.HandlerTypeMetadataName}' is not registered in the current service provider.")}));");

        if (handler.ReturnKind == GeneratedErrorReturnKind.Sync)
        {
            builder.Append("        return new global::System.Threading.Tasks.ValueTask<global::TeleFlow.Telegram.TelegramErrorHandlingResult>(handler.");
            AppendErrorInvocationArguments(builder, handler);
            builder.AppendLine(");");
        }
        else
        {
            builder.Append("        return await handler.");
            AppendErrorInvocationArguments(builder, handler);
            builder.AppendLine(".ConfigureAwait(false);");
        }

        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void AppendErrorInvocationArguments(
        StringBuilder builder,
        GeneratedErrorHandlerMethod handler)
    {
        builder.Append(handler.MethodName);
        builder.Append('(');

        for (int parameterIndex = 0; parameterIndex < handler.Parameters.Length; parameterIndex++)
        {
            if (parameterIndex > 0)
            {
                builder.Append(", ");
            }

            GeneratedErrorParameter parameter = handler.Parameters[parameterIndex];
            builder.Append('(');
            builder.Append(parameter.TypeName);
            builder.Append($")arguments[{parameterIndex}]!");
        }

        builder.Append(')');
    }

    private static string ToNullableLiteral(string? value)
    {
        return value is null ? "null" : ToLiteral(value);
    }

    private static string ToTypeOfNullable(string? typeName)
    {
        return typeName is null ? "null" : $"typeof({typeName})";
    }

    private static string ToLiteral(string value)
    {
        StringBuilder builder = new StringBuilder(value.Length + 2);
        builder.Append('"');

        foreach (char character in value)
        {
            builder.Append(character switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\r' => "\\r",
                '\n' => "\\n",
                '\t' => "\\t",
                _ => character.ToString()
            });
        }

        builder.Append('"');
        return builder.ToString();
    }

    private static string ToBoolLiteral(bool value)
    {
        return value ? "true" : "false";
    }

    private static string ToAttributeCreationExpression(AttributeData attribute)
    {
        if (attribute.AttributeClass is null)
        {
            return "null!";
        }

        StringBuilder builder = new StringBuilder();
        builder.Append("new ");
        builder.Append(attribute.AttributeClass.ToDisplayString(FullyQualifiedFormat));
        builder.Append('(');

        for (int index = 0; index < attribute.ConstructorArguments.Length; index++)
        {
            if (index > 0)
            {
                builder.Append(", ");
            }

            builder.Append(ToAttributeArgumentExpression(attribute.ConstructorArguments[index]));
        }

        builder.Append(')');

        if (attribute.NamedArguments.Length > 0)
        {
            builder.Append(" { ");

            for (int index = 0; index < attribute.NamedArguments.Length; index++)
            {
                if (index > 0)
                {
                    builder.Append(", ");
                }

                KeyValuePair<string, TypedConstant> argument = attribute.NamedArguments[index];
                builder.Append(argument.Key);
                builder.Append(" = ");
                builder.Append(ToAttributeArgumentExpression(argument.Value));
            }

            builder.Append(" }");
        }

        return builder.ToString();
    }

    private static string ToAttributeArgumentExpression(TypedConstant constant)
    {
        if (constant.IsNull)
        {
            return "null";
        }

        return constant.Kind switch
        {
            TypedConstantKind.Primitive => ToPrimitiveLiteral(constant.Value, constant.Type),
            TypedConstantKind.Enum => ToEnumLiteral(constant),
            TypedConstantKind.Type => constant.Value is ITypeSymbol type
                ? $"typeof({type.ToDisplayString(FullyQualifiedFormat)})"
                : "null",
            TypedConstantKind.Array => ToArrayLiteral(constant),
            _ => "null"
        };
    }

    private static string ToPrimitiveLiteral(
        object? value,
        ITypeSymbol? type)
    {
        return value switch
        {
            string stringValue => ToLiteral(stringValue),
            char charValue => ToCharLiteral(charValue),
            bool boolValue => ToBoolLiteral(boolValue),
            byte byteValue => byteValue.ToString(System.Globalization.CultureInfo.InvariantCulture),
            sbyte sbyteValue => sbyteValue.ToString(System.Globalization.CultureInfo.InvariantCulture),
            short shortValue => shortValue.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ushort ushortValue => ushortValue.ToString(System.Globalization.CultureInfo.InvariantCulture),
            int intValue => intValue.ToString(System.Globalization.CultureInfo.InvariantCulture),
            uint uintValue => uintValue.ToString(System.Globalization.CultureInfo.InvariantCulture) + "U",
            long longValue => longValue.ToString(System.Globalization.CultureInfo.InvariantCulture) + "L",
            ulong ulongValue => ulongValue.ToString(System.Globalization.CultureInfo.InvariantCulture) + "UL",
            float floatValue => floatValue.ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "F",
            double doubleValue => doubleValue.ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "D",
            _ when type?.SpecialType == SpecialType.System_Object => "null",
            _ => value?.ToString() ?? "null"
        };
    }

    private static string ToCharLiteral(char value)
    {
        string escaped = value switch
        {
            '\'' => "\\'",
            '\\' => "\\\\",
            '\r' => "\\r",
            '\n' => "\\n",
            '\t' => "\\t",
            _ => value.ToString()
        };

        return $"'{escaped}'";
    }

    private static string ToEnumLiteral(TypedConstant constant)
    {
        var enumType = constant.Type?.ToDisplayString(FullyQualifiedFormat) ?? "int";
        var value = constant.Value switch
        {
            ulong ulongValue => ulongValue.ToString(System.Globalization.CultureInfo.InvariantCulture) + "UL",
            long longValue => longValue.ToString(System.Globalization.CultureInfo.InvariantCulture) + "L",
            uint uintValue => uintValue.ToString(System.Globalization.CultureInfo.InvariantCulture) + "U",
            _ => Convert.ToString(constant.Value, System.Globalization.CultureInfo.InvariantCulture) ?? "0"
        };

        return $"({enumType}){value}";
    }

    private static string ToArrayLiteral(TypedConstant constant)
    {
        var elementType = constant.Type is IArrayTypeSymbol arrayType
            ? arrayType.ElementType.ToDisplayString(FullyQualifiedFormat)
            : "object";
        StringBuilder builder = new StringBuilder();

        builder.Append("new ");
        builder.Append(elementType);
        builder.Append("[] { ");

        for (int index = 0; index < constant.Values.Length; index++)
        {
            if (index > 0)
            {
                builder.Append(", ");
            }

            builder.Append(ToAttributeArgumentExpression(constant.Values[index]));
        }

        builder.Append(" }");

        return builder.ToString();
    }
}
