// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-25T20:26:26.1770012+00:00
//   Source SHA-256: bad109f0fc19b3b0d1703be99fa0161ca066363d8fca62e1165527885add506f
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Use this method to process a received chat join request query. Returns True on success.
/// </summary>
/// <remarks>
/// Telegram result type: Boolean.
/// </remarks>
public sealed partial record class AnswerChatJoinRequestQuery : ITelegramApiMethod<bool>
{
    public static string MethodName => "answerChatJoinRequestQuery";

    /// <summary>
    /// Unique identifier of the join request query
    /// </summary>
    [JsonPropertyName("chat_join_request_query_id")]
    [JsonRequired]
    public required string ChatJoinRequestQueryId { get; init; } = null!;

    /// <summary>
    /// Result of the query. Must be either “approve” to allow the user to join the chat, “decline” to disallow the user to join the chat, or “queue” to leave the decision to other administrators.
    /// </summary>
    [JsonPropertyName("result")]
    [JsonRequired]
    public required string Result { get; init; } = null!;

}