// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-25T20:26:26.1770012+00:00
//   Source SHA-256: bad109f0fc19b3b0d1703be99fa0161ca066363d8fca62e1165527885add506f
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Use this method to reply to a received guest message. On success, a SentGuestMessage object is returned.
/// </summary>
/// <remarks>
/// Telegram result type: SentGuestMessage.
/// </remarks>
public sealed partial record class AnswerGuestQuery : ITelegramApiMethod<SentGuestMessage>
{
    public static string MethodName => "answerGuestQuery";

    /// <summary>
    /// Unique identifier for the query to be answered
    /// </summary>
    [JsonPropertyName("guest_query_id")]
    [JsonRequired]
    public required string GuestQueryId { get; init; } = null!;

    /// <summary>
    /// A JSON-serialized object describing the message to be sent
    /// </summary>
    [JsonPropertyName("result")]
    [JsonRequired]
    public required InlineQueryResult Result { get; init; } = null!;

}