// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Use this method to set the result of an interaction with a Web App and send a corresponding message on behalf of the user to the chat from which the query originated. On success, a SentWebAppMessage object is returned.
/// </summary>
/// <remarks>
/// Telegram result type: SentWebAppMessage.
/// </remarks>
public sealed partial record class AnswerWebAppQuery : ITelegramApiMethod<SentWebAppMessage>
{
    public static string MethodName => "answerWebAppQuery";

    /// <summary>
    /// Unique identifier for the query to be answered
    /// </summary>
    [JsonPropertyName("web_app_query_id")]
    [JsonRequired]
    public required string WebAppQueryId { get; init; } = null!;

    /// <summary>
    /// A JSON-serialized object describing the message to be sent
    /// </summary>
    [JsonPropertyName("result")]
    [JsonRequired]
    public required InlineQueryResult Result { get; init; } = null!;

}