// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Use this method to approve a suggested post in a direct messages chat. The bot must have the &apos;can_post_messages&apos; administrator right in the corresponding channel chat. Returns True on success.
/// </summary>
/// <remarks>
/// Telegram result type: Boolean.
/// </remarks>
public sealed partial record class ApproveSuggestedPost : ITelegramApiMethod<bool>
{
    public static string MethodName => "approveSuggestedPost";

    /// <summary>
    /// Unique identifier for the target direct messages chat
    /// </summary>
    [JsonPropertyName("chat_id")]
    [JsonRequired]
    public required long ChatId { get; init; }

    /// <summary>
    /// Identifier of a suggested post message to approve
    /// </summary>
    [JsonPropertyName("message_id")]
    [JsonRequired]
    public required long MessageId { get; init; }

    /// <summary>
    /// Point in time (Unix timestamp) when the post is expected to be published; omit if the date has already been specified when the suggested post was created. If specified, then the date must be not more than 2678400 seconds (30 days) in the future.
    /// </summary>
    [JsonPropertyName("send_date")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? SendDate { get; init; }

}