// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Use this method to ban a channel chat in a supergroup or a channel. Until the chat is unbanned, the owner of the banned chat won&apos;t be able to send messages on behalf of any of their channels. The bot must be an administrator in the supergroup or channel for this to work and must have the appropriate administrator rights. Returns True on success.
/// </summary>
/// <remarks>
/// Telegram result type: Boolean.
/// </remarks>
public sealed partial record class BanChatSenderChat : ITelegramApiMethod<bool>
{
    public static string MethodName => "banChatSenderChat";

    /// <summary>
    /// Unique identifier for the target chat or username of the target channel in the format @username
    /// </summary>
    [JsonPropertyName("chat_id")]
    [JsonRequired]
    public required IntegerString ChatId { get; init; } = null!;

    /// <summary>
    /// Unique identifier of the target sender chat
    /// </summary>
    [JsonPropertyName("sender_chat_id")]
    [JsonRequired]
    public required long SenderChatId { get; init; }

}