// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Use this method to copy messages of any kind. Service messages, paid media messages, giveaway messages, giveaway winners messages, and invoice messages can&apos;t be copied. A quiz poll can be copied only if the value of the field correct_option_id is known to the bot. The method is analogous to the method forwardMessage, but the copied message doesn&apos;t have a link to the original message. Returns the MessageId of the sent message on success.
/// </summary>
/// <remarks>
/// Telegram result type: MessageId.
/// </remarks>
public sealed partial record class CopyMessage : ITelegramApiMethod<MessageId>
{
    public static string MethodName => "copyMessage";

    /// <summary>
    /// Unique identifier for the target chat or username of the target bot, supergroup or channel in the format @username
    /// </summary>
    [JsonPropertyName("chat_id")]
    [JsonRequired]
    public required IntegerString ChatId { get; init; } = null!;

    /// <summary>
    /// Unique identifier for the target message thread (topic) of a forum; for forum supergroups and private chats of bots with forum topic mode enabled only
    /// </summary>
    [JsonPropertyName("message_thread_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? MessageThreadId { get; init; }

    /// <summary>
    /// Identifier of the direct messages topic to which the message will be sent; required if the message is sent to a direct messages chat
    /// </summary>
    [JsonPropertyName("direct_messages_topic_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? DirectMessagesTopicId { get; init; }

    /// <summary>
    /// Unique identifier for the chat where the original message was sent (or username of the target bot, supergroup or channel in the format @username)
    /// </summary>
    [JsonPropertyName("from_chat_id")]
    [JsonRequired]
    public required IntegerString FromChatId { get; init; } = null!;

    /// <summary>
    /// Message identifier in the chat specified in from_chat_id
    /// </summary>
    [JsonPropertyName("message_id")]
    [JsonRequired]
    public required long MessageId { get; init; }

    /// <summary>
    /// New start timestamp for the copied video in the message
    /// </summary>
    [JsonPropertyName("video_start_timestamp")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? VideoStartTimestamp { get; init; }

    /// <summary>
    /// New caption for media, 0-1024 characters after entities parsing. If not specified, the original caption is kept.
    /// </summary>
    [JsonPropertyName("caption")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Caption { get; init; }

    /// <summary>
    /// Mode for parsing entities in the new caption. See formatting options for more details.
    /// </summary>
    [JsonPropertyName("parse_mode")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ParseMode { get; init; }

    /// <summary>
    /// A JSON-serialized list of special entities that appear in the new caption, which can be specified instead of parse_mode
    /// </summary>
    [JsonPropertyName("caption_entities")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<MessageEntity>? CaptionEntities { get; init; }

    /// <summary>
    /// Pass True, if the caption must be shown above the message media. Ignored if a new caption isn&apos;t specified.
    /// </summary>
    [JsonPropertyName("show_caption_above_media")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? ShowCaptionAboveMedia { get; init; }

    /// <summary>
    /// Sends the message silently. Users will receive a notification with no sound.
    /// </summary>
    [JsonPropertyName("disable_notification")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? DisableNotification { get; init; }

    /// <summary>
    /// Protects the contents of the sent message from forwarding and saving
    /// </summary>
    [JsonPropertyName("protect_content")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? ProtectContent { get; init; }

    /// <summary>
    /// Pass True to allow up to 1000 messages per second, ignoring broadcasting limits for a fee of 0.1 Telegram Stars per message. The relevant Stars will be withdrawn from the bot&apos;s balance.
    /// </summary>
    [JsonPropertyName("allow_paid_broadcast")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? AllowPaidBroadcast { get; init; }

    /// <summary>
    /// Unique identifier of the message effect to be added to the message; only available when copying to private chats
    /// </summary>
    [JsonPropertyName("message_effect_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? MessageEffectId { get; init; }

    /// <summary>
    /// A JSON-serialized object containing the parameters of the suggested post to send; for direct messages chats only. If the message is sent as a reply to another suggested post, then that suggested post is automatically declined.
    /// </summary>
    [JsonPropertyName("suggested_post_parameters")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public SuggestedPostParameters? SuggestedPostParameters { get; init; }

    /// <summary>
    /// Description of the message to reply to
    /// </summary>
    [JsonPropertyName("reply_parameters")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ReplyParameters? ReplyParameters { get; init; }

    /// <summary>
    /// Additional interface options. A JSON-serialized object for an inline keyboard, custom reply keyboard, instructions to remove a reply keyboard or to force a reply from the user.
    /// </summary>
    [JsonPropertyName("reply_markup")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ReplyMarkup? ReplyMarkup { get; init; }

}