// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Use this method to copy messages of any kind. If some of the specified messages can&apos;t be found or copied, they are skipped. Service messages, paid media messages, giveaway messages, giveaway winners messages, and invoice messages can&apos;t be copied. A quiz poll can be copied only if the value of the field correct_option_ids is known to the bot. The method is analogous to the method forwardMessages, but the copied messages don&apos;t have a link to the original message. Album grouping is kept for copied messages. On success, an Array of MessageId of the sent messages is returned.
/// </summary>
/// <remarks>
/// Telegram result type: Array of MessageId.
/// </remarks>
public sealed partial record class CopyMessages : ITelegramApiMethod<IReadOnlyList<MessageId>>
{
    public static string MethodName => "copyMessages";

    /// <summary>
    /// Unique identifier for the target chat or username of the target bot, supergroup or channel in the format @username
    /// </summary>
    [JsonPropertyName("chat_id")]
    [JsonRequired]
    public required IntegerString ChatId { get; init; } = null!;

    /// <summary>
    /// Unique identifier for the target message thread (topic) of a forum; for forum supergroups and private chats of bots with forum topic mode enabled only
    /// </summary>
    [JsonPropertyName("message_thread_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? MessageThreadId { get; init; }

    /// <summary>
    /// Identifier of the direct messages topic to which the messages will be sent; required if the messages are sent to a direct messages chat
    /// </summary>
    [JsonPropertyName("direct_messages_topic_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? DirectMessagesTopicId { get; init; }

    /// <summary>
    /// Unique identifier for the chat where the original messages were sent (or username of the target bot, supergroup or channel in the format @username)
    /// </summary>
    [JsonPropertyName("from_chat_id")]
    [JsonRequired]
    public required IntegerString FromChatId { get; init; } = null!;

    /// <summary>
    /// A JSON-serialized list of 1-100 identifiers of messages in the chat from_chat_id to copy. The identifiers must be specified in a strictly increasing order.
    /// </summary>
    [JsonPropertyName("message_ids")]
    [JsonRequired]
    public required IReadOnlyList<long> MessageIds { get; init; } = null!;

    /// <summary>
    /// Sends the messages silently. Users will receive a notification with no sound.
    /// </summary>
    [JsonPropertyName("disable_notification")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? DisableNotification { get; init; }

    /// <summary>
    /// Protects the contents of the sent messages from forwarding and saving
    /// </summary>
    [JsonPropertyName("protect_content")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? ProtectContent { get; init; }

    /// <summary>
    /// Pass True to copy the messages without their captions
    /// </summary>
    [JsonPropertyName("remove_caption")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? RemoveCaption { get; init; }

}