// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Deletes a story previously posted by the bot on behalf of a managed business account. Requires the can_manage_stories business bot right. Returns True on success.
/// </summary>
/// <remarks>
/// Telegram result type: Boolean.
/// </remarks>
public sealed partial record class DeleteStory : ITelegramApiMethod<bool>
{
    public static string MethodName => "deleteStory";

    /// <summary>
    /// Unique identifier of the business connection
    /// </summary>
    [JsonPropertyName("business_connection_id")]
    [JsonRequired]
    public required string BusinessConnectionId { get; init; } = null!;

    /// <summary>
    /// Unique identifier of the story to delete
    /// </summary>
    [JsonPropertyName("story_id")]
    [JsonRequired]
    public required long StoryId { get; init; }

}