// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Use this method to get information about the connection of the bot with a business account. Returns a BusinessConnection object on success.
/// </summary>
/// <remarks>
/// Telegram result type: BusinessConnection.
/// </remarks>
public sealed partial record class GetBusinessConnection : ITelegramApiMethod<BusinessConnection>
{
    public static string MethodName => "getBusinessConnection";

    /// <summary>
    /// Unique identifier of the business connection
    /// </summary>
    [JsonPropertyName("business_connection_id")]
    [JsonRequired]
    public required string BusinessConnectionId { get; init; } = null!;

}