// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Use this method to get custom emoji stickers, which can be used as a forum topic icon by any user. Requires no parameters. Returns an Array of Sticker objects.
/// </summary>
/// <remarks>
/// Telegram result type: Array of Sticker.
/// </remarks>
public sealed partial record class GetForumTopicIconStickers : ITelegramApiMethod<IReadOnlyList<Sticker>>
{
    public static string MethodName => "getForumTopicIconStickers";

}