// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Use this method to get the current list of the bot&apos;s commands for the given scope and user language. Returns an Array of BotCommand objects. If commands aren&apos;t set, an empty list is returned.
/// </summary>
/// <remarks>
/// Telegram result type: Array of BotCommand.
/// </remarks>
public sealed partial record class GetMyCommands : ITelegramApiMethod<IReadOnlyList<BotCommand>>
{
    public static string MethodName => "getMyCommands";

    /// <summary>
    /// A JSON-serialized object, describing scope of users. Defaults to BotCommandScopeDefault.
    /// </summary>
    [JsonPropertyName("scope")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public BotCommandScope? Scope { get; init; }

    /// <summary>
    /// A two-letter ISO 639-1 language code or an empty string
    /// </summary>
    [JsonPropertyName("language_code")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? LanguageCode { get; init; }

}