// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// A simple method for testing your bot&apos;s authentication token. Requires no parameters. Returns basic information about the bot in form of a User object.
/// </summary>
/// <remarks>
/// Telegram result type: User.
/// </remarks>
public sealed partial record class GetMe : ITelegramApiMethod<User>
{
    public static string MethodName => "getMe";

}