// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.3
//   Telegram Bot API release: 2026-08-24
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#august-24-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Returns the bot&apos;s Telegram Star transactions in chronological order. On success, returns a StarTransactions object.
/// </summary>
/// <remarks>
/// Telegram result type: StarTransactions.
/// </remarks>
public sealed partial record class GetStarTransactions : ITelegramApiMethod<StarTransactions>
{
    public static string MethodName => "getStarTransactions";

    /// <summary>
    /// Number of transactions to skip in the response
    /// </summary>
    [JsonPropertyName("offset")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? Offset { get; init; }

    /// <summary>
    /// The maximum number of transactions to be retrieved. Values between 1-100 are accepted. Defaults to 100.
    /// </summary>
    [JsonPropertyName("limit")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? Limit { get; init; }

}