// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Marks incoming message as read on behalf of a business account. Requires the can_read_messages business bot right. Returns True on success.
/// </summary>
/// <remarks>
/// Telegram result type: Boolean.
/// </remarks>
public sealed partial record class ReadBusinessMessage : ITelegramApiMethod<bool>
{
    public static string MethodName => "readBusinessMessage";

    /// <summary>
    /// Unique identifier of the business connection on behalf of which to read the message
    /// </summary>
    [JsonPropertyName("business_connection_id")]
    [JsonRequired]
    public required string BusinessConnectionId { get; init; } = null!;

    /// <summary>
    /// Unique identifier of the chat in which the message was received. The chat must have been active in the last 24 hours.
    /// </summary>
    [JsonPropertyName("chat_id")]
    [JsonRequired]
    public required long ChatId { get; init; }

    /// <summary>
    /// Unique identifier of the message to mark as read
    /// </summary>
    [JsonPropertyName("message_id")]
    [JsonRequired]
    public required long MessageId { get; init; }

}