// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Removes verification from a chat that is currently verified on behalf of the organization represented by the bot. Returns True on success.
/// </summary>
/// <remarks>
/// Telegram result type: Boolean.
/// </remarks>
public sealed partial record class RemoveChatVerification : ITelegramApiMethod<bool>
{
    public static string MethodName => "removeChatVerification";

    /// <summary>
    /// Unique identifier for the target chat or username of the target bot or channel in the format @username
    /// </summary>
    [JsonPropertyName("chat_id")]
    [JsonRequired]
    public required IntegerString ChatId { get; init; } = null!;

}