// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Use this method to reopen a closed topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights, unless it is the creator of the topic. Returns True on success.
/// </summary>
/// <remarks>
/// Telegram result type: Boolean.
/// </remarks>
public sealed partial record class ReopenForumTopic : ITelegramApiMethod<bool>
{
    public static string MethodName => "reopenForumTopic";

    /// <summary>
    /// Unique identifier for the target chat or username of the target supergroup in the format @username
    /// </summary>
    [JsonPropertyName("chat_id")]
    [JsonRequired]
    public required IntegerString ChatId { get; init; } = null!;

    /// <summary>
    /// Unique identifier for the target message thread of the forum topic
    /// </summary>
    [JsonPropertyName("message_thread_id")]
    [JsonRequired]
    public required long MessageThreadId { get; init; }

}