// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Stores a message that can be sent by a user of a Mini App. Returns a PreparedInlineMessage object.
/// </summary>
/// <remarks>
/// Telegram result type: PreparedInlineMessage.
/// </remarks>
public sealed partial record class SavePreparedInlineMessage : ITelegramApiMethod<PreparedInlineMessage>
{
    public static string MethodName => "savePreparedInlineMessage";

    /// <summary>
    /// Unique identifier of the target user that can use the prepared message
    /// </summary>
    [JsonPropertyName("user_id")]
    [JsonRequired]
    public required long UserId { get; init; }

    /// <summary>
    /// A JSON-serialized object describing the message to be sent
    /// </summary>
    [JsonPropertyName("result")]
    [JsonRequired]
    public required InlineQueryResult Result { get; init; } = null!;

    /// <summary>
    /// Pass True if the message can be sent to private chats with users
    /// </summary>
    [JsonPropertyName("allow_user_chats")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? AllowUserChats { get; init; }

    /// <summary>
    /// Pass True if the message can be sent to private chats with bots
    /// </summary>
    [JsonPropertyName("allow_bot_chats")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? AllowBotChats { get; init; }

    /// <summary>
    /// Pass True if the message can be sent to group and supergroup chats
    /// </summary>
    [JsonPropertyName("allow_group_chats")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? AllowGroupChats { get; init; }

    /// <summary>
    /// Pass True if the message can be sent to channel chats
    /// </summary>
    [JsonPropertyName("allow_channel_chats")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? AllowChannelChats { get; init; }

}