// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-25T20:26:26.1770012+00:00
//   Source SHA-256: bad109f0fc19b3b0d1703be99fa0161ca066363d8fca62e1165527885add506f
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Stores a keyboard button that can be used by a user within a Mini App. Returns a PreparedKeyboardButton object.
/// </summary>
/// <remarks>
/// Telegram result type: PreparedKeyboardButton.
/// </remarks>
public sealed partial record class SavePreparedKeyboardButton : ITelegramApiMethod<PreparedKeyboardButton>
{
    public static string MethodName => "savePreparedKeyboardButton";

    /// <summary>
    /// Unique identifier of the target user that can use the button
    /// </summary>
    [JsonPropertyName("user_id")]
    [JsonRequired]
    public required long UserId { get; init; }

    /// <summary>
    /// A JSON-serialized object describing the button to be saved. The button must be of the type request_users, request_chat, or request_managed_bot.
    /// </summary>
    [JsonPropertyName("button")]
    [JsonRequired]
    public required KeyboardButton Button { get; init; } = null!;

}