// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Use this method to send a checklist on behalf of a connected business account. On success, the sent Message is returned.
/// </summary>
/// <remarks>
/// Telegram result type: Message.
/// </remarks>
public sealed partial record class SendChecklist : ITelegramApiMethod<Message>
{
    public static string MethodName => "sendChecklist";

    /// <summary>
    /// Unique identifier of the business connection on behalf of which the message will be sent
    /// </summary>
    [JsonPropertyName("business_connection_id")]
    [JsonRequired]
    public required string BusinessConnectionId { get; init; } = null!;

    /// <summary>
    /// Unique identifier for the target chat or username of the target bot in the format @username
    /// </summary>
    [JsonPropertyName("chat_id")]
    [JsonRequired]
    public required IntegerString ChatId { get; init; } = null!;

    /// <summary>
    /// A JSON-serialized object for the checklist to send
    /// </summary>
    [JsonPropertyName("checklist")]
    [JsonRequired]
    public required InputChecklist Checklist { get; init; } = null!;

    /// <summary>
    /// Sends the message silently. Users will receive a notification with no sound.
    /// </summary>
    [JsonPropertyName("disable_notification")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? DisableNotification { get; init; }

    /// <summary>
    /// Protects the contents of the sent message from forwarding and saving
    /// </summary>
    [JsonPropertyName("protect_content")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? ProtectContent { get; init; }

    /// <summary>
    /// Unique identifier of the message effect to be added to the message
    /// </summary>
    [JsonPropertyName("message_effect_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? MessageEffectId { get; init; }

    /// <summary>
    /// A JSON-serialized object for description of the message to reply to
    /// </summary>
    [JsonPropertyName("reply_parameters")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ReplyParameters? ReplyParameters { get; init; }

    /// <summary>
    /// A JSON-serialized object for an inline keyboard
    /// </summary>
    [JsonPropertyName("reply_markup")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public InlineKeyboardMarkup? ReplyMarkup { get; init; }

}