// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Changes the profile photo of a managed business account. Requires the can_edit_profile_photo business bot right. Returns True on success.
/// </summary>
/// <remarks>
/// Telegram result type: Boolean.
/// </remarks>
public sealed partial record class SetBusinessAccountProfilePhoto : ITelegramApiMethod<bool>
{
    public static string MethodName => "setBusinessAccountProfilePhoto";

    /// <summary>
    /// Unique identifier of the business connection
    /// </summary>
    [JsonPropertyName("business_connection_id")]
    [JsonRequired]
    public required string BusinessConnectionId { get; init; } = null!;

    /// <summary>
    /// The new profile photo to set
    /// </summary>
    [JsonPropertyName("photo")]
    [JsonRequired]
    public required InputProfilePhoto Photo { get; init; } = null!;

    /// <summary>
    /// Pass True to set the public photo, which will be visible even if the main photo is hidden by the business account&apos;s privacy settings. An account can have only one public photo.
    /// </summary>
    [JsonPropertyName("is_public")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? IsPublic { get; init; }

}