// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Use this method to set the score of the specified user in a game message. On success, if the message is not an inline message, the Message is returned, otherwise True is returned. Returns an error, if the new score is not greater than the user&apos;s current score in the chat and force is False.
/// </summary>
/// <remarks>
/// Telegram result type: Message or Boolean.
/// </remarks>
public sealed partial record class SetGameScore : ITelegramApiMethod<MessageBoolean>
{
    public static string MethodName => "setGameScore";

    /// <summary>
    /// User identifier
    /// </summary>
    [JsonPropertyName("user_id")]
    [JsonRequired]
    public required long UserId { get; init; }

    /// <summary>
    /// New score, must be non-negative
    /// </summary>
    [JsonPropertyName("score")]
    [JsonRequired]
    public required long Score { get; init; }

    /// <summary>
    /// Pass True if the high score is allowed to decrease. This can be useful when fixing mistakes or banning cheaters.
    /// </summary>
    [JsonPropertyName("force")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Force { get; init; }

    /// <summary>
    /// Pass True if the game message should not be automatically edited to include the current scoreboard
    /// </summary>
    [JsonPropertyName("disable_edit_message")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? DisableEditMessage { get; init; }

    /// <summary>
    /// Required if inline_message_id is not specified. Unique identifier for the target chat.
    /// </summary>
    [JsonPropertyName("chat_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? ChatId { get; init; }

    /// <summary>
    /// Required if inline_message_id is not specified. Identifier of the sent message.
    /// </summary>
    [JsonPropertyName("message_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? MessageId { get; init; }

    /// <summary>
    /// Required if chat_id and message_id are not specified. Identifier of the inline message.
    /// </summary>
    [JsonPropertyName("inline_message_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? InlineMessageId { get; init; }

}