// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Use this method to move a sticker in a set created by the bot to a specific position. Returns True on success.
/// </summary>
/// <remarks>
/// Telegram result type: Boolean.
/// </remarks>
public sealed partial record class SetStickerPositionInSet : ITelegramApiMethod<bool>
{
    public static string MethodName => "setStickerPositionInSet";

    /// <summary>
    /// File identifier of the sticker
    /// </summary>
    [JsonPropertyName("sticker")]
    [JsonRequired]
    public required string Sticker { get; init; } = null!;

    /// <summary>
    /// New sticker position in the set, zero-based
    /// </summary>
    [JsonPropertyName("position")]
    [JsonRequired]
    public required long Position { get; init; }

}