// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-25T20:26:26.1770012+00:00
//   Source SHA-256: bad109f0fc19b3b0d1703be99fa0161ca066363d8fca62e1165527885add506f
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Changes the emoji status for a given user that previously allowed the bot to manage their emoji status via the Mini App method requestEmojiStatusAccess. Returns True on success.
/// </summary>
/// <remarks>
/// Telegram result type: Boolean.
/// </remarks>
public sealed partial record class SetUserEmojiStatus : ITelegramApiMethod<bool>
{
    public static string MethodName => "setUserEmojiStatus";

    /// <summary>
    /// Unique identifier of the target user
    /// </summary>
    [JsonPropertyName("user_id")]
    [JsonRequired]
    public required long UserId { get; init; }

    /// <summary>
    /// Custom emoji identifier of the emoji status to set. Pass an empty string to remove the status.
    /// </summary>
    [JsonPropertyName("emoji_status_custom_emoji_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? EmojiStatusCustomEmojiId { get; init; }

    /// <summary>
    /// Expiration date of the emoji status, if any
    /// </summary>
    [JsonPropertyName("emoji_status_expiration_date")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? EmojiStatusExpirationDate { get; init; }

}