// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Use this method to specify a URL and receive incoming updates via an outgoing webhook. Whenever there is an update for the bot, we will send an HTTPS POST request to the specified URL, containing a JSON-serialized Update. In case of an unsuccessful request (a request with response HTTP status code different from 2XY), we will repeat the request and give up after a reasonable amount of attempts. Returns True on success.
/// </summary>
/// <remarks>
/// Telegram result type: Boolean.
/// If you&apos;d like to make sure that the webhook was set by you, you can specify secret data in the parameter secret_token. If specified, the request will contain a header “X-Telegram-Bot-Api-Secret-Token” with the secret token as content.
/// Notes1. You will not be able to receive updates using getUpdates for as long as an outgoing webhook is set up.2. To use a self-signed certificate, you need to upload your public key certificate using certificate parameter. Please upload as InputFile, sending a String will not work.3. Ports currently supported for webhooks: 443, 80, 88, 8443. If you&apos;re having any trouble setting up webhooks, please check out this amazing guide to webhooks.
/// </remarks>
public sealed partial record class SetWebhook : ITelegramApiMethod<bool>
{
    public static string MethodName => "setWebhook";

    /// <summary>
    /// HTTPS URL to send updates to. Use an empty string to remove webhook integration.
    /// </summary>
    [JsonPropertyName("url")]
    [JsonRequired]
    public required string Url { get; init; } = null!;

    /// <summary>
    /// Upload your public key certificate so that the root certificate in use can be checked. See our self-signed guide for details.
    /// </summary>
    [JsonPropertyName("certificate")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public InputFile? Certificate { get; init; }

    /// <summary>
    /// The fixed IP address which will be used to send webhook requests instead of the IP address resolved through DNS
    /// </summary>
    [JsonPropertyName("ip_address")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? IpAddress { get; init; }

    /// <summary>
    /// The maximum allowed number of simultaneous HTTPS connections to the webhook for update delivery, 1-100. Defaults to 40. Use lower values to limit the load on your bot&apos;s server, and higher values to increase your bot&apos;s throughput.
    /// </summary>
    [JsonPropertyName("max_connections")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? MaxConnections { get; init; }

    /// <summary>
    /// A JSON-serialized list of the update types you want your bot to receive. For example, specify [&quot;message&quot;, &quot;edited_channel_post&quot;, &quot;callback_query&quot;] to only receive updates of these types. See Update for a complete list of available update types. Specify an empty list to receive all update types except chat_member, message_reaction, and message_reaction_count (default). If not specified, the previous setting will be used.Please note that this parameter doesn&apos;t affect updates created before the call to the setWebhook, so unwanted updates may be received for a short period of time.
    /// </summary>
    [JsonPropertyName("allowed_updates")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<string>? AllowedUpdates { get; init; }

    /// <summary>
    /// Pass True to drop all pending updates
    /// </summary>
    [JsonPropertyName("drop_pending_updates")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? DropPendingUpdates { get; init; }

    /// <summary>
    /// A secret token to be sent in a header “X-Telegram-Bot-Api-Secret-Token” in every webhook request, 1-256 characters. Only characters A-Z, a-z, 0-9, _ and - are allowed. The header is useful to ensure that the request comes from a webhook set by you.
    /// </summary>
    [JsonPropertyName("secret_token")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? SecretToken { get; init; }

}