// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Method
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using TelegramFile = TeleFlow.Telegram.Schema.Types.File;
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using TeleFlow.Telegram.Schema.Types;

namespace TeleFlow.Telegram.Schema.Methods;

/// <summary>
/// Use this method to upload a file with a sticker for later use in the createNewStickerSet, addStickerToSet, or replaceStickerInSet methods (the file can be used multiple times). Returns the uploaded File on success.
/// </summary>
/// <remarks>
/// Telegram result type: File.
/// </remarks>
public sealed partial record class UploadStickerFile : ITelegramApiMethod<TelegramFile>
{
    public static string MethodName => "uploadStickerFile";

    /// <summary>
    /// User identifier of sticker file owner
    /// </summary>
    [JsonPropertyName("user_id")]
    [JsonRequired]
    public required long UserId { get; init; }

    /// <summary>
    /// A file with the sticker in .WEBP, .PNG, .TGS, or .WEBM format. See https://core.telegram.org/stickers for technical requirements. More information on Sending Files »
    /// </summary>
    [JsonPropertyName("sticker")]
    [JsonRequired]
    public required InputFile Sticker { get; init; } = null!;

    /// <summary>
    /// Format of the sticker, must be one of “static”, “animated”, “video”
    /// </summary>
    [JsonPropertyName("sticker_format")]
    [JsonRequired]
    public required string StickerFormat { get; init; } = null!;

}