// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Abstraction
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable

namespace TeleFlow.Telegram.Schema.Abstractions;

/// <summary>
/// Represents a generated Telegram Bot API method request model.
/// </summary>
public interface ITelegramApiMethod<TResult>
{
    static abstract string MethodName { get; }
}