// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: ConstantGroup
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable

namespace TeleFlow.Telegram.Schema.Constants;

/// <summary>
/// Known Telegram Bot API chat type values.
/// </summary>
public static class ChatTypes
{
    /// <summary>
    /// Telegram Bot API value <c>channel</c>.
    /// </summary>
    public const string Channel = "channel";

    /// <summary>
    /// Telegram Bot API value <c>group</c>.
    /// </summary>
    public const string Group = "group";

    /// <summary>
    /// Telegram Bot API value <c>private</c>.
    /// </summary>
    public const string Private = "private";

    /// <summary>
    /// Telegram Bot API value <c>sender</c>.
    /// </summary>
    public const string Sender = "sender";

    /// <summary>
    /// Telegram Bot API value <c>supergroup</c>.
    /// </summary>
    public const string Supergroup = "supergroup";
}