// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: ConstantGroup
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable

namespace TeleFlow.Telegram.Schema.Constants;

/// <summary>
/// Known Telegram Bot API InputStoryContent type values.
/// </summary>
public static class InputStoryContentTypes
{
    /// <summary>
    /// Telegram Bot API value <c>photo</c>.
    /// </summary>
    public const string Photo = "photo";

    /// <summary>
    /// Telegram Bot API value <c>video</c>.
    /// </summary>
    public const string Video = "video";
}