// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: ConstantGroup
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable

namespace TeleFlow.Telegram.Schema.Constants;

/// <summary>
/// Known Telegram Bot API RevenueWithdrawalState type values.
/// </summary>
public static class RevenueWithdrawalStateTypes
{
    /// <summary>
    /// Telegram Bot API value <c>failed</c>.
    /// </summary>
    public const string Failed = "failed";

    /// <summary>
    /// Telegram Bot API value <c>pending</c>.
    /// </summary>
    public const string Pending = "pending";

    /// <summary>
    /// Telegram Bot API value <c>succeeded</c>.
    /// </summary>
    public const string Succeeded = "succeeded";
}