// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: ConstantGroup
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable

namespace TeleFlow.Telegram.Schema.Constants;

/// <summary>
/// Known Telegram Bot API TransactionPartner type values.
/// </summary>
public static class TransactionPartnerTypes
{
    /// <summary>
    /// Telegram Bot API value <c>affiliate_program</c>.
    /// </summary>
    public const string AffiliateProgram = "affiliate_program";

    /// <summary>
    /// Telegram Bot API value <c>chat</c>.
    /// </summary>
    public const string Chat = "chat";

    /// <summary>
    /// Telegram Bot API value <c>fragment</c>.
    /// </summary>
    public const string Fragment = "fragment";

    /// <summary>
    /// Telegram Bot API value <c>other</c>.
    /// </summary>
    public const string Other = "other";

    /// <summary>
    /// Telegram Bot API value <c>telegram_ads</c>.
    /// </summary>
    public const string TelegramAds = "telegram_ads";

    /// <summary>
    /// Telegram Bot API value <c>telegram_api</c>.
    /// </summary>
    public const string TelegramApi = "telegram_api";

    /// <summary>
    /// Telegram Bot API value <c>user</c>.
    /// </summary>
    public const string User = "user";
}