// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object describes the types of gifts that can be gifted to a user or a chat.
/// </summary>
public sealed partial record class AcceptedGiftTypes
{
    /// <summary>
    /// True, if unlimited regular gifts are accepted
    /// </summary>
    [JsonPropertyName("unlimited_gifts")]
    [JsonRequired]
    public required bool UnlimitedGifts { get; init; }

    /// <summary>
    /// True, if limited regular gifts are accepted
    /// </summary>
    [JsonPropertyName("limited_gifts")]
    [JsonRequired]
    public required bool LimitedGifts { get; init; }

    /// <summary>
    /// True, if unique gifts or gifts that can be upgraded to unique for free are accepted
    /// </summary>
    [JsonPropertyName("unique_gifts")]
    [JsonRequired]
    public required bool UniqueGifts { get; init; }

    /// <summary>
    /// True, if a Telegram Premium subscription is accepted
    /// </summary>
    [JsonPropertyName("premium_subscription")]
    [JsonRequired]
    public required bool PremiumSubscription { get; init; }

    /// <summary>
    /// True, if transfers of unique gifts from channels are accepted
    /// </summary>
    [JsonPropertyName("gifts_from_channels")]
    [JsonRequired]
    public required bool GiftsFromChannels { get; init; }

}