// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-25T20:26:26.1770012+00:00
//   Source SHA-256: bad109f0fc19b3b0d1703be99fa0161ca066363d8fca62e1165527885add506f
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// The background is a gradient fill.
/// </summary>
public sealed partial record class BackgroundFillGradient : IJsonOnDeserialized
{
    /// <summary>
    /// Type of the background fill, always “gradient”
    /// </summary>
    public const string TypeValue = "gradient";

    [JsonPropertyName("type")]
    [JsonRequired]
    public string Type { get; init; } = TypeValue;

    /// <summary>
    /// Top color of the gradient in the RGB24 format
    /// </summary>
    [JsonPropertyName("top_color")]
    [JsonRequired]
    public required long TopColor { get; init; }

    /// <summary>
    /// Bottom color of the gradient in the RGB24 format
    /// </summary>
    [JsonPropertyName("bottom_color")]
    [JsonRequired]
    public required long BottomColor { get; init; }

    /// <summary>
    /// Clockwise rotation angle of the background fill in degrees; 0-359
    /// </summary>
    [JsonPropertyName("rotation_angle")]
    [JsonRequired]
    public required long RotationAngle { get; init; }

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Type != TypeValue)
        {
            throw new JsonException("Expected Telegram literal 'gradient' for field 'type' on BackgroundFillGradient.");
        }

    }
}