// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Represents the scope of bot commands, covering all administrators of a specific group or supergroup chat.
/// </summary>
public sealed partial record class BotCommandScopeChatAdministrators : IJsonOnDeserialized
{
    /// <summary>
    /// Scope type, must be chat_administrators
    /// </summary>
    public const string TypeValue = "chat_administrators";

    [JsonPropertyName("type")]
    [JsonRequired]
    public string Type { get; init; } = TypeValue;

    /// <summary>
    /// Unique identifier for the target chat or username of the target supergroup in the format @username. Channel direct messages chats and channel chats aren&apos;t supported.
    /// </summary>
    [JsonPropertyName("chat_id")]
    [JsonRequired]
    public required IntegerString ChatId { get; init; } = null!;

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Type != TypeValue)
        {
            throw new JsonException("Expected Telegram literal 'chat_administrators' for field 'type' on BotCommandScopeChatAdministrators.");
        }

    }
}