// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Represents the scope of bot commands, covering all group and supergroup chat administrators.
/// </summary>
public sealed partial record class BotCommandScopeAllChatAdministrators : IJsonOnDeserialized
{
    /// <summary>
    /// Scope type, must be all_chat_administrators
    /// </summary>
    public const string TypeValue = "all_chat_administrators";

    [JsonPropertyName("type")]
    [JsonRequired]
    public string Type { get; init; } = TypeValue;

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Type != TypeValue)
        {
            throw new JsonException("Expected Telegram literal 'all_chat_administrators' for field 'type' on BotCommandScopeAllChatAdministrators.");
        }

    }
}