// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object contains information about changes to a user payment subscription toward the current bot.
/// </summary>
public sealed partial record class BotSubscriptionUpdated
{
    /// <summary>
    /// User who subscribed for payments toward the bot
    /// </summary>
    [JsonPropertyName("user")]
    [JsonRequired]
    public required User User { get; init; } = null!;

    /// <summary>
    /// Bot-specified invoice payload
    /// </summary>
    [JsonPropertyName("invoice_payload")]
    [JsonRequired]
    public required string InvoicePayload { get; init; } = null!;

    /// <summary>
    /// The new state of the subscription. Currently, it can be one of “canceled” if the user canceled the subscription, “active” if the user re-enabled a previously canceled subscription, or “failed” if payment for the subscription failed.
    /// </summary>
    [JsonPropertyName("state")]
    [JsonRequired]
    public required string State { get; init; } = null!;

}