// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Describes a service message about the chat owner leaving the chat.
/// </summary>
public sealed partial record class ChatOwnerLeft
{
    /// <summary>
    /// The user who will become the new owner of the chat if the previous owner does not return to the chat
    /// </summary>
    [JsonPropertyName("new_owner")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public User? NewOwner { get; init; }

}