// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object represents changes in the status of a chat member.
/// </summary>
public sealed partial record class ChatMemberUpdated
{
    /// <summary>
    /// Chat the user belongs to
    /// </summary>
    [JsonPropertyName("chat")]
    [JsonRequired]
    public required Chat Chat { get; init; } = null!;

    /// <summary>
    /// Performer of the action, which resulted in the change
    /// </summary>
    [JsonPropertyName("from")]
    [JsonRequired]
    public required User From { get; init; } = null!;

    /// <summary>
    /// Date the change was done in Unix time
    /// </summary>
    [JsonPropertyName("date")]
    [JsonRequired]
    public required long Date { get; init; }

    /// <summary>
    /// Previous information about the chat member
    /// </summary>
    [JsonPropertyName("old_chat_member")]
    [JsonRequired]
    public required ChatMember OldChatMember { get; init; } = null!;

    /// <summary>
    /// New information about the chat member
    /// </summary>
    [JsonPropertyName("new_chat_member")]
    [JsonRequired]
    public required ChatMember NewChatMember { get; init; } = null!;

    /// <summary>
    /// Chat invite link, which was used by the user to join the chat; for joining by invite link events only
    /// </summary>
    [JsonPropertyName("invite_link")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ChatInviteLink? InviteLink { get; init; }

    /// <summary>
    /// True, if the user joined the chat after sending a direct join request without using an invite link and being approved by an administrator
    /// </summary>
    [JsonPropertyName("via_join_request")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? ViaJoinRequest { get; init; }

    /// <summary>
    /// True, if the user joined the chat via a chat folder invite link
    /// </summary>
    [JsonPropertyName("via_chat_folder_invite_link")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? ViaChatFolderInviteLink { get; init; }

}