// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Represents a chat member that is under certain restrictions in the chat. Supergroups only.
/// </summary>
public sealed partial record class ChatMemberRestricted : IJsonOnDeserialized
{
    /// <summary>
    /// The member&apos;s status in the chat, always “restricted”
    /// </summary>
    public const string StatusValue = "restricted";

    [JsonPropertyName("status")]
    [JsonRequired]
    public string Status { get; init; } = StatusValue;

    /// <summary>
    /// Tag of the member
    /// </summary>
    [JsonPropertyName("tag")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Tag { get; init; }

    /// <summary>
    /// Information about the user
    /// </summary>
    [JsonPropertyName("user")]
    [JsonRequired]
    public required User User { get; init; } = null!;

    /// <summary>
    /// True, if the user is a member of the chat at the moment of the request
    /// </summary>
    [JsonPropertyName("is_member")]
    [JsonRequired]
    public required bool IsMember { get; init; }

    /// <summary>
    /// True, if the user is allowed to send text messages, rich messages, contacts, giveaways, giveaway winners, invoices, locations and venues
    /// </summary>
    [JsonPropertyName("can_send_messages")]
    [JsonRequired]
    public required bool CanSendMessages { get; init; }

    /// <summary>
    /// True, if the user is allowed to send audios
    /// </summary>
    [JsonPropertyName("can_send_audios")]
    [JsonRequired]
    public required bool CanSendAudios { get; init; }

    /// <summary>
    /// True, if the user is allowed to send documents
    /// </summary>
    [JsonPropertyName("can_send_documents")]
    [JsonRequired]
    public required bool CanSendDocuments { get; init; }

    /// <summary>
    /// True, if the user is allowed to send photos
    /// </summary>
    [JsonPropertyName("can_send_photos")]
    [JsonRequired]
    public required bool CanSendPhotos { get; init; }

    /// <summary>
    /// True, if the user is allowed to send videos
    /// </summary>
    [JsonPropertyName("can_send_videos")]
    [JsonRequired]
    public required bool CanSendVideos { get; init; }

    /// <summary>
    /// True, if the user is allowed to send video notes
    /// </summary>
    [JsonPropertyName("can_send_video_notes")]
    [JsonRequired]
    public required bool CanSendVideoNotes { get; init; }

    /// <summary>
    /// True, if the user is allowed to send voice notes
    /// </summary>
    [JsonPropertyName("can_send_voice_notes")]
    [JsonRequired]
    public required bool CanSendVoiceNotes { get; init; }

    /// <summary>
    /// True, if the user is allowed to send polls and checklists
    /// </summary>
    [JsonPropertyName("can_send_polls")]
    [JsonRequired]
    public required bool CanSendPolls { get; init; }

    /// <summary>
    /// True, if the user is allowed to send animations, games, stickers and use inline bots
    /// </summary>
    [JsonPropertyName("can_send_other_messages")]
    [JsonRequired]
    public required bool CanSendOtherMessages { get; init; }

    /// <summary>
    /// True, if the user is allowed to add web page previews to their messages
    /// </summary>
    [JsonPropertyName("can_add_web_page_previews")]
    [JsonRequired]
    public required bool CanAddWebPagePreviews { get; init; }

    /// <summary>
    /// True, if the user is allowed to react to messages
    /// </summary>
    [JsonPropertyName("can_react_to_messages")]
    [JsonRequired]
    public required bool CanReactToMessages { get; init; }

    /// <summary>
    /// True, if the user is allowed to edit their own tag
    /// </summary>
    [JsonPropertyName("can_edit_tag")]
    [JsonRequired]
    public required bool CanEditTag { get; init; }

    /// <summary>
    /// True, if the user is allowed to change the chat title, photo and other settings
    /// </summary>
    [JsonPropertyName("can_change_info")]
    [JsonRequired]
    public required bool CanChangeInfo { get; init; }

    /// <summary>
    /// True, if the user is allowed to invite new users to the chat
    /// </summary>
    [JsonPropertyName("can_invite_users")]
    [JsonRequired]
    public required bool CanInviteUsers { get; init; }

    /// <summary>
    /// True, if the user is allowed to pin messages
    /// </summary>
    [JsonPropertyName("can_pin_messages")]
    [JsonRequired]
    public required bool CanPinMessages { get; init; }

    /// <summary>
    /// True, if the user is allowed to create forum topics
    /// </summary>
    [JsonPropertyName("can_manage_topics")]
    [JsonRequired]
    public required bool CanManageTopics { get; init; }

    /// <summary>
    /// Date when restrictions will be lifted for this user; Unix time. If 0, then the user is restricted forever.
    /// </summary>
    [JsonPropertyName("until_date")]
    [JsonRequired]
    public required long UntilDate { get; init; }

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Status != StatusValue)
        {
            throw new JsonException("Expected Telegram literal 'restricted' for field 'status' on ChatMemberRestricted.");
        }

    }
}