// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// The boost was obtained by subscribing to Telegram Premium or by gifting a Telegram Premium subscription to another user.
/// </summary>
public sealed partial record class ChatBoostSourcePremium : IJsonOnDeserialized
{
    /// <summary>
    /// Source of the boost, always “premium”
    /// </summary>
    public const string SourceValue = "premium";

    [JsonPropertyName("source")]
    [JsonRequired]
    public string Source { get; init; } = SourceValue;

    /// <summary>
    /// User that boosted the chat
    /// </summary>
    [JsonPropertyName("user")]
    [JsonRequired]
    public required User User { get; init; } = null!;

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Source != SourceValue)
        {
            throw new JsonException("Expected Telegram literal 'premium' for field 'source' on ChatBoostSourcePremium.");
        }

    }
}