// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// The boost was obtained by the creation of a Telegram Premium or a Telegram Star giveaway. This boosts the chat 4 times for the duration of the corresponding Telegram Premium subscription for Telegram Premium giveaways and prize_star_count / 500 times for one year for Telegram Star giveaways.
/// </summary>
public sealed partial record class ChatBoostSourceGiveaway : IJsonOnDeserialized
{
    /// <summary>
    /// Source of the boost, always “giveaway”
    /// </summary>
    public const string SourceValue = "giveaway";

    [JsonPropertyName("source")]
    [JsonRequired]
    public string Source { get; init; } = SourceValue;

    /// <summary>
    /// Identifier of a message in the chat with the giveaway; the message could have been deleted already. May be 0 if the message isn&apos;t sent yet.
    /// </summary>
    [JsonPropertyName("giveaway_message_id")]
    [JsonRequired]
    public required long GiveawayMessageId { get; init; }

    /// <summary>
    /// User that won the prize in the giveaway if any; for Telegram Premium giveaways only
    /// </summary>
    [JsonPropertyName("user")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public User? User { get; init; }

    /// <summary>
    /// The number of Telegram Stars to be split between giveaway winners; for Telegram Star giveaways only
    /// </summary>
    [JsonPropertyName("prize_star_count")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? PrizeStarCount { get; init; }

    /// <summary>
    /// True, if the giveaway was completed, but there was no user to win the prize
    /// </summary>
    [JsonPropertyName("is_unclaimed")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? IsUnclaimed { get; init; }

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Source != SourceValue)
        {
            throw new JsonException("Expected Telegram literal 'giveaway' for field 'source' on ChatBoostSourceGiveaway.");
        }

    }
}