// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-25T20:26:26.1770012+00:00
//   Source SHA-256: bad109f0fc19b3b0d1703be99fa0161ca066363d8fca62e1165527885add506f
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Describes a checklist.
/// </summary>
public sealed partial record class Checklist
{
    /// <summary>
    /// Title of the checklist
    /// </summary>
    [JsonPropertyName("title")]
    [JsonRequired]
    public required string Title { get; init; } = null!;

    /// <summary>
    /// Special entities that appear in the checklist title
    /// </summary>
    [JsonPropertyName("title_entities")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<MessageEntity>? TitleEntities { get; init; }

    /// <summary>
    /// List of tasks in the checklist
    /// </summary>
    [JsonPropertyName("tasks")]
    [JsonRequired]
    public required IReadOnlyList<ChecklistTask> Tasks { get; init; } = null!;

    /// <summary>
    /// True, if users other than the creator of the list can add tasks to the list
    /// </summary>
    [JsonPropertyName("others_can_add_tasks")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? OthersCanAddTasks { get; init; }

    /// <summary>
    /// True, if users other than the creator of the list can mark tasks as done or not done
    /// </summary>
    [JsonPropertyName("others_can_mark_tasks_as_done")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? OthersCanMarkTasksAsDone { get; init; }

}