// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Describes a service message about a change in the price of direct messages sent to a channel chat.
/// </summary>
public sealed partial record class DirectMessagePriceChanged
{
    /// <summary>
    /// True, if direct messages are enabled for the channel chat; false otherwise
    /// </summary>
    [JsonPropertyName("are_direct_messages_enabled")]
    [JsonRequired]
    public required bool AreDirectMessagesEnabled { get; init; }

    /// <summary>
    /// The new number of Telegram Stars that must be paid by users for each direct message sent to the channel. Does not apply to users who have been exempted by administrators. Defaults to 0.
    /// </summary>
    [JsonPropertyName("direct_message_star_count")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? DirectMessageStarCount { get; init; }

}