// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Describes data required for decrypting and authenticating EncryptedPassportElement. See the Telegram Passport Documentation for a complete description of the data decryption and authentication processes.
/// </summary>
public sealed partial record class EncryptedCredentials
{
    /// <summary>
    /// Base64-encoded encrypted JSON-serialized data with unique user&apos;s payload, data hashes and secrets required for EncryptedPassportElement decryption and authentication
    /// </summary>
    [JsonPropertyName("data")]
    [JsonRequired]
    public required string Data { get; init; } = null!;

    /// <summary>
    /// Base64-encoded data hash for data authentication
    /// </summary>
    [JsonPropertyName("hash")]
    [JsonRequired]
    public required string Hash { get; init; } = null!;

    /// <summary>
    /// Base64-encoded secret, encrypted with the bot&apos;s public RSA key, required for data decryption
    /// </summary>
    [JsonPropertyName("secret")]
    [JsonRequired]
    public required string Secret { get; init; } = null!;

}