// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-25T20:26:26.1770012+00:00
//   Source SHA-256: bad109f0fc19b3b0d1703be99fa0161ca066363d8fca62e1165527885add506f
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object represents one row of the high scores table for a game.
/// </summary>
/// <remarks>
/// And that&apos;s about all we&apos;ve got for now.If you&apos;ve got any questions, please check out our Bot FAQ »
/// </remarks>
public sealed partial record class GameHighScore
{
    /// <summary>
    /// Position in high score table for the game
    /// </summary>
    [JsonPropertyName("position")]
    [JsonRequired]
    public required long Position { get; init; }

    /// <summary>
    /// User
    /// </summary>
    [JsonPropertyName("user")]
    [JsonRequired]
    public required User User { get; init; } = null!;

    /// <summary>
    /// Score
    /// </summary>
    [JsonPropertyName("score")]
    [JsonRequired]
    public required long Score { get; init; }

}