// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object represent a list of gifts.
/// </summary>
public sealed partial record class Gifts
{
    /// <summary>
    /// The list of gifts
    /// </summary>
    [JsonPropertyName("gifts")]
    [JsonRequired]
    public required IReadOnlyList<Gift> GiftsValue { get; init; } = null!;

}