// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object describes the background of a gift.
/// </summary>
public sealed partial record class GiftBackground
{
    /// <summary>
    /// Center color of the background in RGB format
    /// </summary>
    [JsonPropertyName("center_color")]
    [JsonRequired]
    public required long CenterColor { get; init; }

    /// <summary>
    /// Edge color of the background in RGB format
    /// </summary>
    [JsonPropertyName("edge_color")]
    [JsonRequired]
    public required long EdgeColor { get; init; }

    /// <summary>
    /// Text color of the background in RGB format
    /// </summary>
    [JsonPropertyName("text_color")]
    [JsonRequired]
    public required long TextColor { get; init; }

}