// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object represents a service message about the completion of a giveaway without public winners.
/// </summary>
public sealed partial record class GiveawayCompleted
{
    /// <summary>
    /// Number of winners in the giveaway
    /// </summary>
    [JsonPropertyName("winner_count")]
    [JsonRequired]
    public required long WinnerCount { get; init; }

    /// <summary>
    /// Number of undistributed prizes
    /// </summary>
    [JsonPropertyName("unclaimed_prize_count")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? UnclaimedPrizeCount { get; init; }

    /// <summary>
    /// Message with the giveaway that was completed, if it wasn&apos;t deleted
    /// </summary>
    [JsonPropertyName("giveaway_message")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Message? GiveawayMessage { get; init; }

    /// <summary>
    /// True, if the giveaway is a Telegram Star giveaway. Otherwise, currently, the giveaway is a Telegram Premium giveaway.
    /// </summary>
    [JsonPropertyName("is_star_giveaway")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? IsStarGiveaway { get; init; }

}