// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object represents a message about the completion of a giveaway with public winners.
/// </summary>
public sealed partial record class GiveawayWinners
{
    /// <summary>
    /// The chat that created the giveaway
    /// </summary>
    [JsonPropertyName("chat")]
    [JsonRequired]
    public required Chat Chat { get; init; } = null!;

    /// <summary>
    /// Identifier of the message with the giveaway in the chat
    /// </summary>
    [JsonPropertyName("giveaway_message_id")]
    [JsonRequired]
    public required long GiveawayMessageId { get; init; }

    /// <summary>
    /// Point in time (Unix timestamp) when winners of the giveaway were selected
    /// </summary>
    [JsonPropertyName("winners_selection_date")]
    [JsonRequired]
    public required long WinnersSelectionDate { get; init; }

    /// <summary>
    /// Total number of winners in the giveaway
    /// </summary>
    [JsonPropertyName("winner_count")]
    [JsonRequired]
    public required long WinnerCount { get; init; }

    /// <summary>
    /// List of up to 100 winners of the giveaway
    /// </summary>
    [JsonPropertyName("winners")]
    [JsonRequired]
    public required IReadOnlyList<User> Winners { get; init; } = null!;

    /// <summary>
    /// The number of other chats the user had to join in order to be eligible for the giveaway
    /// </summary>
    [JsonPropertyName("additional_chat_count")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? AdditionalChatCount { get; init; }

    /// <summary>
    /// The number of Telegram Stars that were split between giveaway winners; for Telegram Star giveaways only
    /// </summary>
    [JsonPropertyName("prize_star_count")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? PrizeStarCount { get; init; }

    /// <summary>
    /// The number of months the Telegram Premium subscription won from the giveaway will be active for; for Telegram Premium giveaways only
    /// </summary>
    [JsonPropertyName("premium_subscription_month_count")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? PremiumSubscriptionMonthCount { get; init; }

    /// <summary>
    /// Number of undistributed prizes
    /// </summary>
    [JsonPropertyName("unclaimed_prize_count")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? UnclaimedPrizeCount { get; init; }

    /// <summary>
    /// True, if only users who had joined the chats after the giveaway started were eligible to win
    /// </summary>
    [JsonPropertyName("only_new_members")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? OnlyNewMembers { get; init; }

    /// <summary>
    /// True, if the giveaway was canceled because the payment for it was refunded
    /// </summary>
    [JsonPropertyName("was_refunded")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? WasRefunded { get; init; }

    /// <summary>
    /// Description of additional giveaway prize
    /// </summary>
    [JsonPropertyName("prize_description")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? PrizeDescription { get; init; }

}