// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object represents one result of an inline query. Telegram clients currently support results of the following 20 types:
/// </summary>
/// <remarks>
/// Note: All URLs passed in inline query results will be available to end users and therefore must be assumed to be public.
/// InlineQueryResultCachedAudio
/// InlineQueryResultCachedDocument
/// InlineQueryResultCachedGif
/// InlineQueryResultCachedMpeg4Gif
/// InlineQueryResultCachedPhoto
/// InlineQueryResultCachedSticker
/// InlineQueryResultCachedVideo
/// InlineQueryResultCachedVoice
/// InlineQueryResultArticle
/// InlineQueryResultAudio
/// InlineQueryResultContact
/// InlineQueryResultGame
/// InlineQueryResultDocument
/// InlineQueryResultGif
/// InlineQueryResultLocation
/// InlineQueryResultMpeg4Gif
/// InlineQueryResultPhoto
/// InlineQueryResultVenue
/// InlineQueryResultVideo
/// InlineQueryResultVoice
/// Union members: InlineQueryResultCachedAudio, InlineQueryResultCachedDocument, InlineQueryResultCachedGif, InlineQueryResultCachedMpeg4Gif, InlineQueryResultCachedPhoto, InlineQueryResultCachedSticker, InlineQueryResultCachedVideo, InlineQueryResultCachedVoice, InlineQueryResultArticle, InlineQueryResultAudio, InlineQueryResultContact, InlineQueryResultGame, InlineQueryResultDocument, InlineQueryResultGif, InlineQueryResultLocation, InlineQueryResultMpeg4Gif, InlineQueryResultPhoto, InlineQueryResultVenue, InlineQueryResultVideo, InlineQueryResultVoice.
/// </remarks>
[JsonConverter(typeof(InlineQueryResultJsonConverter))]
public sealed partial record class InlineQueryResult
{
    private InlineQueryResult(InlineQueryResultCachedAudio value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultCachedAudio = value;
    }

    private InlineQueryResult(InlineQueryResultCachedDocument value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultCachedDocument = value;
    }

    private InlineQueryResult(InlineQueryResultCachedGif value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultCachedGif = value;
    }

    private InlineQueryResult(InlineQueryResultCachedMpeg4Gif value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultCachedMpeg4Gif = value;
    }

    private InlineQueryResult(InlineQueryResultCachedPhoto value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultCachedPhoto = value;
    }

    private InlineQueryResult(InlineQueryResultCachedSticker value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultCachedSticker = value;
    }

    private InlineQueryResult(InlineQueryResultCachedVideo value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultCachedVideo = value;
    }

    private InlineQueryResult(InlineQueryResultCachedVoice value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultCachedVoice = value;
    }

    private InlineQueryResult(InlineQueryResultArticle value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultArticle = value;
    }

    private InlineQueryResult(InlineQueryResultAudio value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultAudio = value;
    }

    private InlineQueryResult(InlineQueryResultContact value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultContact = value;
    }

    private InlineQueryResult(InlineQueryResultGame value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultGame = value;
    }

    private InlineQueryResult(InlineQueryResultDocument value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultDocument = value;
    }

    private InlineQueryResult(InlineQueryResultGif value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultGif = value;
    }

    private InlineQueryResult(InlineQueryResultLocation value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultLocation = value;
    }

    private InlineQueryResult(InlineQueryResultMpeg4Gif value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultMpeg4Gif = value;
    }

    private InlineQueryResult(InlineQueryResultPhoto value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultPhoto = value;
    }

    private InlineQueryResult(InlineQueryResultVenue value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultVenue = value;
    }

    private InlineQueryResult(InlineQueryResultVideo value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultVideo = value;
    }

    private InlineQueryResult(InlineQueryResultVoice value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InlineQueryResultVoice = value;
    }

    /// <summary>
    /// Gets the InlineQueryResultCachedAudio value when this instance represents that case.
    /// </summary>
    public InlineQueryResultCachedAudio? InlineQueryResultCachedAudio { get; }

    /// <summary>
    /// Gets the InlineQueryResultCachedDocument value when this instance represents that case.
    /// </summary>
    public InlineQueryResultCachedDocument? InlineQueryResultCachedDocument { get; }

    /// <summary>
    /// Gets the InlineQueryResultCachedGif value when this instance represents that case.
    /// </summary>
    public InlineQueryResultCachedGif? InlineQueryResultCachedGif { get; }

    /// <summary>
    /// Gets the InlineQueryResultCachedMpeg4Gif value when this instance represents that case.
    /// </summary>
    public InlineQueryResultCachedMpeg4Gif? InlineQueryResultCachedMpeg4Gif { get; }

    /// <summary>
    /// Gets the InlineQueryResultCachedPhoto value when this instance represents that case.
    /// </summary>
    public InlineQueryResultCachedPhoto? InlineQueryResultCachedPhoto { get; }

    /// <summary>
    /// Gets the InlineQueryResultCachedSticker value when this instance represents that case.
    /// </summary>
    public InlineQueryResultCachedSticker? InlineQueryResultCachedSticker { get; }

    /// <summary>
    /// Gets the InlineQueryResultCachedVideo value when this instance represents that case.
    /// </summary>
    public InlineQueryResultCachedVideo? InlineQueryResultCachedVideo { get; }

    /// <summary>
    /// Gets the InlineQueryResultCachedVoice value when this instance represents that case.
    /// </summary>
    public InlineQueryResultCachedVoice? InlineQueryResultCachedVoice { get; }

    /// <summary>
    /// Gets the InlineQueryResultArticle value when this instance represents that case.
    /// </summary>
    public InlineQueryResultArticle? InlineQueryResultArticle { get; }

    /// <summary>
    /// Gets the InlineQueryResultAudio value when this instance represents that case.
    /// </summary>
    public InlineQueryResultAudio? InlineQueryResultAudio { get; }

    /// <summary>
    /// Gets the InlineQueryResultContact value when this instance represents that case.
    /// </summary>
    public InlineQueryResultContact? InlineQueryResultContact { get; }

    /// <summary>
    /// Gets the InlineQueryResultGame value when this instance represents that case.
    /// </summary>
    public InlineQueryResultGame? InlineQueryResultGame { get; }

    /// <summary>
    /// Gets the InlineQueryResultDocument value when this instance represents that case.
    /// </summary>
    public InlineQueryResultDocument? InlineQueryResultDocument { get; }

    /// <summary>
    /// Gets the InlineQueryResultGif value when this instance represents that case.
    /// </summary>
    public InlineQueryResultGif? InlineQueryResultGif { get; }

    /// <summary>
    /// Gets the InlineQueryResultLocation value when this instance represents that case.
    /// </summary>
    public InlineQueryResultLocation? InlineQueryResultLocation { get; }

    /// <summary>
    /// Gets the InlineQueryResultMpeg4Gif value when this instance represents that case.
    /// </summary>
    public InlineQueryResultMpeg4Gif? InlineQueryResultMpeg4Gif { get; }

    /// <summary>
    /// Gets the InlineQueryResultPhoto value when this instance represents that case.
    /// </summary>
    public InlineQueryResultPhoto? InlineQueryResultPhoto { get; }

    /// <summary>
    /// Gets the InlineQueryResultVenue value when this instance represents that case.
    /// </summary>
    public InlineQueryResultVenue? InlineQueryResultVenue { get; }

    /// <summary>
    /// Gets the InlineQueryResultVideo value when this instance represents that case.
    /// </summary>
    public InlineQueryResultVideo? InlineQueryResultVideo { get; }

    /// <summary>
    /// Gets the InlineQueryResultVoice value when this instance represents that case.
    /// </summary>
    public InlineQueryResultVoice? InlineQueryResultVoice { get; }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultCachedAudio</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultCachedAudio value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultCachedAudio value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultCachedAudio(out InlineQueryResultCachedAudio? value)
    {
        value = InlineQueryResultCachedAudio;
        return value is not null;
    }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultCachedDocument</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultCachedDocument value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultCachedDocument value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultCachedDocument(out InlineQueryResultCachedDocument? value)
    {
        value = InlineQueryResultCachedDocument;
        return value is not null;
    }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultCachedGif</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultCachedGif value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultCachedGif value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultCachedGif(out InlineQueryResultCachedGif? value)
    {
        value = InlineQueryResultCachedGif;
        return value is not null;
    }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultCachedMpeg4Gif</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultCachedMpeg4Gif value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultCachedMpeg4Gif value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultCachedMpeg4Gif(out InlineQueryResultCachedMpeg4Gif? value)
    {
        value = InlineQueryResultCachedMpeg4Gif;
        return value is not null;
    }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultCachedPhoto</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultCachedPhoto value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultCachedPhoto value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultCachedPhoto(out InlineQueryResultCachedPhoto? value)
    {
        value = InlineQueryResultCachedPhoto;
        return value is not null;
    }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultCachedSticker</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultCachedSticker value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultCachedSticker value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultCachedSticker(out InlineQueryResultCachedSticker? value)
    {
        value = InlineQueryResultCachedSticker;
        return value is not null;
    }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultCachedVideo</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultCachedVideo value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultCachedVideo value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultCachedVideo(out InlineQueryResultCachedVideo? value)
    {
        value = InlineQueryResultCachedVideo;
        return value is not null;
    }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultCachedVoice</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultCachedVoice value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultCachedVoice value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultCachedVoice(out InlineQueryResultCachedVoice? value)
    {
        value = InlineQueryResultCachedVoice;
        return value is not null;
    }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultArticle</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultArticle value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultArticle value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultArticle(out InlineQueryResultArticle? value)
    {
        value = InlineQueryResultArticle;
        return value is not null;
    }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultAudio</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultAudio value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultAudio value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultAudio(out InlineQueryResultAudio? value)
    {
        value = InlineQueryResultAudio;
        return value is not null;
    }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultContact</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultContact value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultContact value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultContact(out InlineQueryResultContact? value)
    {
        value = InlineQueryResultContact;
        return value is not null;
    }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultGame</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultGame value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultGame value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultGame(out InlineQueryResultGame? value)
    {
        value = InlineQueryResultGame;
        return value is not null;
    }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultDocument</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultDocument value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultDocument value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultDocument(out InlineQueryResultDocument? value)
    {
        value = InlineQueryResultDocument;
        return value is not null;
    }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultGif</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultGif value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultGif value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultGif(out InlineQueryResultGif? value)
    {
        value = InlineQueryResultGif;
        return value is not null;
    }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultLocation</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultLocation value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultLocation value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultLocation(out InlineQueryResultLocation? value)
    {
        value = InlineQueryResultLocation;
        return value is not null;
    }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultMpeg4Gif</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultMpeg4Gif value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultMpeg4Gif value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultMpeg4Gif(out InlineQueryResultMpeg4Gif? value)
    {
        value = InlineQueryResultMpeg4Gif;
        return value is not null;
    }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultPhoto</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultPhoto value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultPhoto value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultPhoto(out InlineQueryResultPhoto? value)
    {
        value = InlineQueryResultPhoto;
        return value is not null;
    }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultVenue</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultVenue value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultVenue value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultVenue(out InlineQueryResultVenue? value)
    {
        value = InlineQueryResultVenue;
        return value is not null;
    }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultVideo</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultVideo value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultVideo value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultVideo(out InlineQueryResultVideo? value)
    {
        value = InlineQueryResultVideo;
        return value is not null;
    }

    /// <summary>
    /// Creates a InlineQueryResult value from <c>InlineQueryResultVoice</c>.
    /// </summary>
    public static InlineQueryResult From(InlineQueryResultVoice value)
    {
        return new InlineQueryResult(value);
    }

    public static implicit operator InlineQueryResult(InlineQueryResultVoice value)
    {
        return From(value);
    }

    public bool TryGetInlineQueryResultVoice(out InlineQueryResultVoice? value)
    {
        value = InlineQueryResultVoice;
        return value is not null;
    }

}

file sealed class InlineQueryResultJsonConverter : JsonConverter<InlineQueryResult>
{
    public override InlineQueryResult Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.StartObject)
        {
            throw new JsonException("Unable to deserialize InlineQueryResult: unexpected JSON token.");
        }

        using var document = JsonDocument.ParseValue(ref reader);

        if (document.RootElement.TryGetProperty("type", out var typeElement) && typeElement.ValueKind == JsonValueKind.String)
        {
            var discriminator = typeElement.GetString();
            switch (discriminator)
            {
                case "article":
                    return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultArticle>(options)
                        ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultArticle."));
                case "audio":
                    if (document.RootElement.TryGetProperty("audio_url", out _) && document.RootElement.TryGetProperty("id", out _) && document.RootElement.TryGetProperty("title", out _) && document.RootElement.TryGetProperty("type", out _))
                    {
                        return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultAudio>(options)
                            ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultAudio."));
                    }
                    if (document.RootElement.TryGetProperty("audio_file_id", out _) && document.RootElement.TryGetProperty("id", out _) && document.RootElement.TryGetProperty("type", out _))
                    {
                        return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultCachedAudio>(options)
                            ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultCachedAudio."));
                    }
                    throw new JsonException("Unable to refine discriminator value 'audio' for InlineQueryResult using required properties.");
                case "contact":
                    return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultContact>(options)
                        ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultContact."));
                case "document":
                    if (document.RootElement.TryGetProperty("document_url", out _) && document.RootElement.TryGetProperty("id", out _) && document.RootElement.TryGetProperty("mime_type", out _) && document.RootElement.TryGetProperty("title", out _) && document.RootElement.TryGetProperty("type", out _))
                    {
                        return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultDocument>(options)
                            ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultDocument."));
                    }
                    if (document.RootElement.TryGetProperty("document_file_id", out _) && document.RootElement.TryGetProperty("id", out _) && document.RootElement.TryGetProperty("title", out _) && document.RootElement.TryGetProperty("type", out _))
                    {
                        return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultCachedDocument>(options)
                            ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultCachedDocument."));
                    }
                    throw new JsonException("Unable to refine discriminator value 'document' for InlineQueryResult using required properties.");
                case "game":
                    return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultGame>(options)
                        ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultGame."));
                case "gif":
                    if (document.RootElement.TryGetProperty("gif_url", out _) && document.RootElement.TryGetProperty("id", out _) && document.RootElement.TryGetProperty("thumbnail_url", out _) && document.RootElement.TryGetProperty("type", out _))
                    {
                        return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultGif>(options)
                            ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultGif."));
                    }
                    if (document.RootElement.TryGetProperty("gif_file_id", out _) && document.RootElement.TryGetProperty("id", out _) && document.RootElement.TryGetProperty("type", out _))
                    {
                        return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultCachedGif>(options)
                            ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultCachedGif."));
                    }
                    throw new JsonException("Unable to refine discriminator value 'gif' for InlineQueryResult using required properties.");
                case "location":
                    return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultLocation>(options)
                        ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultLocation."));
                case "mpeg4_gif":
                    if (document.RootElement.TryGetProperty("id", out _) && document.RootElement.TryGetProperty("mpeg4_url", out _) && document.RootElement.TryGetProperty("thumbnail_url", out _) && document.RootElement.TryGetProperty("type", out _))
                    {
                        return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultMpeg4Gif>(options)
                            ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultMpeg4Gif."));
                    }
                    if (document.RootElement.TryGetProperty("id", out _) && document.RootElement.TryGetProperty("mpeg4_file_id", out _) && document.RootElement.TryGetProperty("type", out _))
                    {
                        return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultCachedMpeg4Gif>(options)
                            ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultCachedMpeg4Gif."));
                    }
                    throw new JsonException("Unable to refine discriminator value 'mpeg4_gif' for InlineQueryResult using required properties.");
                case "photo":
                    if (document.RootElement.TryGetProperty("id", out _) && document.RootElement.TryGetProperty("photo_url", out _) && document.RootElement.TryGetProperty("thumbnail_url", out _) && document.RootElement.TryGetProperty("type", out _))
                    {
                        return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultPhoto>(options)
                            ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultPhoto."));
                    }
                    if (document.RootElement.TryGetProperty("id", out _) && document.RootElement.TryGetProperty("photo_file_id", out _) && document.RootElement.TryGetProperty("type", out _))
                    {
                        return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultCachedPhoto>(options)
                            ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultCachedPhoto."));
                    }
                    throw new JsonException("Unable to refine discriminator value 'photo' for InlineQueryResult using required properties.");
                case "sticker":
                    return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultCachedSticker>(options)
                        ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultCachedSticker."));
                case "venue":
                    return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultVenue>(options)
                        ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultVenue."));
                case "video":
                    if (document.RootElement.TryGetProperty("id", out _) && document.RootElement.TryGetProperty("mime_type", out _) && document.RootElement.TryGetProperty("thumbnail_url", out _) && document.RootElement.TryGetProperty("title", out _) && document.RootElement.TryGetProperty("type", out _) && document.RootElement.TryGetProperty("video_url", out _))
                    {
                        return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultVideo>(options)
                            ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultVideo."));
                    }
                    if (document.RootElement.TryGetProperty("id", out _) && document.RootElement.TryGetProperty("title", out _) && document.RootElement.TryGetProperty("type", out _) && document.RootElement.TryGetProperty("video_file_id", out _))
                    {
                        return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultCachedVideo>(options)
                            ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultCachedVideo."));
                    }
                    throw new JsonException("Unable to refine discriminator value 'video' for InlineQueryResult using required properties.");
                case "voice":
                    if (document.RootElement.TryGetProperty("id", out _) && document.RootElement.TryGetProperty("title", out _) && document.RootElement.TryGetProperty("type", out _) && document.RootElement.TryGetProperty("voice_file_id", out _))
                    {
                        return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultCachedVoice>(options)
                            ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultCachedVoice."));
                    }
                    if (document.RootElement.TryGetProperty("id", out _) && document.RootElement.TryGetProperty("title", out _) && document.RootElement.TryGetProperty("type", out _) && document.RootElement.TryGetProperty("voice_url", out _))
                    {
                        return InlineQueryResult.From(document.RootElement.Deserialize<InlineQueryResultVoice>(options)
                            ?? throw new JsonException("Unable to deserialize InlineQueryResult as InlineQueryResultVoice."));
                    }
                    throw new JsonException("Unable to refine discriminator value 'voice' for InlineQueryResult using required properties.");
                default:
                    throw new JsonException($"Unknown discriminator value '{discriminator}' for InlineQueryResult.");
            }
        }

        throw new JsonException("Unable to deserialize InlineQueryResult from the provided Telegram payload.");
    }

    public override void Write(Utf8JsonWriter writer, InlineQueryResult value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(value);
        if (value.InlineQueryResultCachedAudio is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultCachedAudio, options);
            return;
        }

        if (value.InlineQueryResultCachedDocument is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultCachedDocument, options);
            return;
        }

        if (value.InlineQueryResultCachedGif is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultCachedGif, options);
            return;
        }

        if (value.InlineQueryResultCachedMpeg4Gif is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultCachedMpeg4Gif, options);
            return;
        }

        if (value.InlineQueryResultCachedPhoto is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultCachedPhoto, options);
            return;
        }

        if (value.InlineQueryResultCachedSticker is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultCachedSticker, options);
            return;
        }

        if (value.InlineQueryResultCachedVideo is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultCachedVideo, options);
            return;
        }

        if (value.InlineQueryResultCachedVoice is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultCachedVoice, options);
            return;
        }

        if (value.InlineQueryResultArticle is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultArticle, options);
            return;
        }

        if (value.InlineQueryResultAudio is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultAudio, options);
            return;
        }

        if (value.InlineQueryResultContact is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultContact, options);
            return;
        }

        if (value.InlineQueryResultGame is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultGame, options);
            return;
        }

        if (value.InlineQueryResultDocument is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultDocument, options);
            return;
        }

        if (value.InlineQueryResultGif is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultGif, options);
            return;
        }

        if (value.InlineQueryResultLocation is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultLocation, options);
            return;
        }

        if (value.InlineQueryResultMpeg4Gif is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultMpeg4Gif, options);
            return;
        }

        if (value.InlineQueryResultPhoto is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultPhoto, options);
            return;
        }

        if (value.InlineQueryResultVenue is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultVenue, options);
            return;
        }

        if (value.InlineQueryResultVideo is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultVideo, options);
            return;
        }

        if (value.InlineQueryResultVoice is not null)
        {
            JsonSerializer.Serialize(writer, value.InlineQueryResultVoice, options);
            return;
        }

        throw new JsonException("The InlineQueryResult instance does not contain a union case value.");
    }
}