// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Represents a link to a file. By default, this file will be sent by the user with an optional caption. Alternatively, you can use input_message_content to send a message with the specified content instead of the file. Currently, only .PDF and .ZIP files can be sent using this method.
/// </summary>
public sealed partial record class InlineQueryResultDocument : IJsonOnDeserialized
{
    /// <summary>
    /// Type of the result, must be document
    /// </summary>
    public const string TypeValue = "document";

    [JsonPropertyName("type")]
    [JsonRequired]
    public string Type { get; init; } = TypeValue;

    /// <summary>
    /// Unique identifier for this result, 1-64 bytes
    /// </summary>
    [JsonPropertyName("id")]
    [JsonRequired]
    public required string Id { get; init; } = null!;

    /// <summary>
    /// Title for the result
    /// </summary>
    [JsonPropertyName("title")]
    [JsonRequired]
    public required string Title { get; init; } = null!;

    /// <summary>
    /// Caption of the document to be sent, 0-1024 characters after entities parsing
    /// </summary>
    [JsonPropertyName("caption")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Caption { get; init; }

    /// <summary>
    /// Mode for parsing entities in the document caption. See formatting options for more details.
    /// </summary>
    [JsonPropertyName("parse_mode")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ParseMode { get; init; }

    /// <summary>
    /// List of special entities that appear in the caption, which can be specified instead of parse_mode
    /// </summary>
    [JsonPropertyName("caption_entities")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<MessageEntity>? CaptionEntities { get; init; }

    /// <summary>
    /// A valid URL for the file
    /// </summary>
    [JsonPropertyName("document_url")]
    [JsonRequired]
    public required string DocumentUrl { get; init; } = null!;

    /// <summary>
    /// MIME type of the content of the file, either “application/pdf” or “application/zip”
    /// </summary>
    [JsonPropertyName("mime_type")]
    [JsonRequired]
    public required string MimeType { get; init; } = null!;

    /// <summary>
    /// Short description of the result
    /// </summary>
    [JsonPropertyName("description")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Description { get; init; }

    /// <summary>
    /// Inline keyboard attached to the message
    /// </summary>
    [JsonPropertyName("reply_markup")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public InlineKeyboardMarkup? ReplyMarkup { get; init; }

    /// <summary>
    /// Content of the message to be sent instead of the file
    /// </summary>
    [JsonPropertyName("input_message_content")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public InputMessageContent? InputMessageContent { get; init; }

    /// <summary>
    /// URL of the thumbnail (JPEG only) for the file
    /// </summary>
    [JsonPropertyName("thumbnail_url")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ThumbnailUrl { get; init; }

    /// <summary>
    /// Thumbnail width
    /// </summary>
    [JsonPropertyName("thumbnail_width")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? ThumbnailWidth { get; init; }

    /// <summary>
    /// Thumbnail height
    /// </summary>
    [JsonPropertyName("thumbnail_height")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? ThumbnailHeight { get; init; }

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Type != TypeValue)
        {
            throw new JsonException("Expected Telegram literal 'document' for field 'type' on InlineQueryResultDocument.");
        }

    }
}