// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object describes the paid media to be sent. Currently, it can be one of
/// </summary>
/// <remarks>
/// InputPaidMediaLivePhoto
/// InputPaidMediaPhoto
/// InputPaidMediaVideo
/// Union members: InputPaidMediaLivePhoto, InputPaidMediaPhoto, InputPaidMediaVideo.
/// </remarks>
[JsonConverter(typeof(InputPaidMediaJsonConverter))]
public sealed partial record class InputPaidMedia
{
    private InputPaidMedia(InputPaidMediaLivePhoto value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InputPaidMediaLivePhoto = value;
    }

    private InputPaidMedia(InputPaidMediaPhoto value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InputPaidMediaPhoto = value;
    }

    private InputPaidMedia(InputPaidMediaVideo value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InputPaidMediaVideo = value;
    }

    /// <summary>
    /// Gets the InputPaidMediaLivePhoto value when this instance represents that case.
    /// </summary>
    public InputPaidMediaLivePhoto? InputPaidMediaLivePhoto { get; }

    /// <summary>
    /// Gets the InputPaidMediaPhoto value when this instance represents that case.
    /// </summary>
    public InputPaidMediaPhoto? InputPaidMediaPhoto { get; }

    /// <summary>
    /// Gets the InputPaidMediaVideo value when this instance represents that case.
    /// </summary>
    public InputPaidMediaVideo? InputPaidMediaVideo { get; }

    /// <summary>
    /// Creates a InputPaidMedia value from <c>InputPaidMediaLivePhoto</c>.
    /// </summary>
    public static InputPaidMedia From(InputPaidMediaLivePhoto value)
    {
        return new InputPaidMedia(value);
    }

    public static implicit operator InputPaidMedia(InputPaidMediaLivePhoto value)
    {
        return From(value);
    }

    public bool TryGetInputPaidMediaLivePhoto(out InputPaidMediaLivePhoto? value)
    {
        value = InputPaidMediaLivePhoto;
        return value is not null;
    }

    /// <summary>
    /// Creates a InputPaidMedia value from <c>InputPaidMediaPhoto</c>.
    /// </summary>
    public static InputPaidMedia From(InputPaidMediaPhoto value)
    {
        return new InputPaidMedia(value);
    }

    public static implicit operator InputPaidMedia(InputPaidMediaPhoto value)
    {
        return From(value);
    }

    public bool TryGetInputPaidMediaPhoto(out InputPaidMediaPhoto? value)
    {
        value = InputPaidMediaPhoto;
        return value is not null;
    }

    /// <summary>
    /// Creates a InputPaidMedia value from <c>InputPaidMediaVideo</c>.
    /// </summary>
    public static InputPaidMedia From(InputPaidMediaVideo value)
    {
        return new InputPaidMedia(value);
    }

    public static implicit operator InputPaidMedia(InputPaidMediaVideo value)
    {
        return From(value);
    }

    public bool TryGetInputPaidMediaVideo(out InputPaidMediaVideo? value)
    {
        value = InputPaidMediaVideo;
        return value is not null;
    }

}

file sealed class InputPaidMediaJsonConverter : JsonConverter<InputPaidMedia>
{
    public override InputPaidMedia Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.StartObject)
        {
            throw new JsonException("Unable to deserialize InputPaidMedia: unexpected JSON token.");
        }

        using var document = JsonDocument.ParseValue(ref reader);

        if (document.RootElement.TryGetProperty("type", out var typeElement) && typeElement.ValueKind == JsonValueKind.String)
        {
            var discriminator = typeElement.GetString();
            switch (discriminator)
            {
                case "live_photo":
                    return InputPaidMedia.From(document.RootElement.Deserialize<InputPaidMediaLivePhoto>(options)
                        ?? throw new JsonException("Unable to deserialize InputPaidMedia as InputPaidMediaLivePhoto."));
                case "photo":
                    return InputPaidMedia.From(document.RootElement.Deserialize<InputPaidMediaPhoto>(options)
                        ?? throw new JsonException("Unable to deserialize InputPaidMedia as InputPaidMediaPhoto."));
                case "video":
                    return InputPaidMedia.From(document.RootElement.Deserialize<InputPaidMediaVideo>(options)
                        ?? throw new JsonException("Unable to deserialize InputPaidMedia as InputPaidMediaVideo."));
                default:
                    throw new JsonException($"Unknown discriminator value '{discriminator}' for InputPaidMedia.");
            }
        }

        throw new JsonException("Unable to deserialize InputPaidMedia from the provided Telegram payload.");
    }

    public override void Write(Utf8JsonWriter writer, InputPaidMedia value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(value);
        if (value.InputPaidMediaLivePhoto is not null)
        {
            JsonSerializer.Serialize(writer, value.InputPaidMediaLivePhoto, options);
            return;
        }

        if (value.InputPaidMediaPhoto is not null)
        {
            JsonSerializer.Serialize(writer, value.InputPaidMediaPhoto, options);
            return;
        }

        if (value.InputPaidMediaVideo is not null)
        {
            JsonSerializer.Serialize(writer, value.InputPaidMediaVideo, options);
            return;
        }

        throw new JsonException("The InputPaidMedia instance does not contain a union case value.");
    }
}