// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.3
//   Telegram Bot API release: 2026-08-24
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#august-24-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Represents the content of a rich message to be sent as the result of an inline query.
/// </summary>
public sealed partial record class InputRichMessageContent
{
    /// <summary>
    /// The message to be sent. Only previously uploaded files may be used in the message.
    /// </summary>
    [JsonPropertyName("rich_message")]
    [JsonRequired]
    public required InputRichMessage RichMessage { get; init; } = null!;

}