// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object represents the content of a media message to be sent. It should be one of
/// </summary>
/// <remarks>
/// InputMediaAnimation
/// InputMediaAudio
/// InputMediaDocument
/// InputMediaLivePhoto
/// InputMediaPhoto
/// InputMediaVideo
/// Union members: InputMediaAnimation, InputMediaAudio, InputMediaDocument, InputMediaLivePhoto, InputMediaPhoto, InputMediaVideo.
/// </remarks>
[JsonConverter(typeof(InputMediaJsonConverter))]
public sealed partial record class InputMedia
{
    private InputMedia(InputMediaAnimation value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InputMediaAnimation = value;
    }

    private InputMedia(InputMediaAudio value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InputMediaAudio = value;
    }

    private InputMedia(InputMediaDocument value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InputMediaDocument = value;
    }

    private InputMedia(InputMediaLivePhoto value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InputMediaLivePhoto = value;
    }

    private InputMedia(InputMediaPhoto value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InputMediaPhoto = value;
    }

    private InputMedia(InputMediaVideo value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InputMediaVideo = value;
    }

    /// <summary>
    /// Gets the InputMediaAnimation value when this instance represents that case.
    /// </summary>
    public InputMediaAnimation? InputMediaAnimation { get; }

    /// <summary>
    /// Gets the InputMediaAudio value when this instance represents that case.
    /// </summary>
    public InputMediaAudio? InputMediaAudio { get; }

    /// <summary>
    /// Gets the InputMediaDocument value when this instance represents that case.
    /// </summary>
    public InputMediaDocument? InputMediaDocument { get; }

    /// <summary>
    /// Gets the InputMediaLivePhoto value when this instance represents that case.
    /// </summary>
    public InputMediaLivePhoto? InputMediaLivePhoto { get; }

    /// <summary>
    /// Gets the InputMediaPhoto value when this instance represents that case.
    /// </summary>
    public InputMediaPhoto? InputMediaPhoto { get; }

    /// <summary>
    /// Gets the InputMediaVideo value when this instance represents that case.
    /// </summary>
    public InputMediaVideo? InputMediaVideo { get; }

    /// <summary>
    /// Creates a InputMedia value from <c>InputMediaAnimation</c>.
    /// </summary>
    public static InputMedia From(InputMediaAnimation value)
    {
        return new InputMedia(value);
    }

    public static implicit operator InputMedia(InputMediaAnimation value)
    {
        return From(value);
    }

    public bool TryGetInputMediaAnimation(out InputMediaAnimation? value)
    {
        value = InputMediaAnimation;
        return value is not null;
    }

    /// <summary>
    /// Creates a InputMedia value from <c>InputMediaAudio</c>.
    /// </summary>
    public static InputMedia From(InputMediaAudio value)
    {
        return new InputMedia(value);
    }

    public static implicit operator InputMedia(InputMediaAudio value)
    {
        return From(value);
    }

    public bool TryGetInputMediaAudio(out InputMediaAudio? value)
    {
        value = InputMediaAudio;
        return value is not null;
    }

    /// <summary>
    /// Creates a InputMedia value from <c>InputMediaDocument</c>.
    /// </summary>
    public static InputMedia From(InputMediaDocument value)
    {
        return new InputMedia(value);
    }

    public static implicit operator InputMedia(InputMediaDocument value)
    {
        return From(value);
    }

    public bool TryGetInputMediaDocument(out InputMediaDocument? value)
    {
        value = InputMediaDocument;
        return value is not null;
    }

    /// <summary>
    /// Creates a InputMedia value from <c>InputMediaLivePhoto</c>.
    /// </summary>
    public static InputMedia From(InputMediaLivePhoto value)
    {
        return new InputMedia(value);
    }

    public static implicit operator InputMedia(InputMediaLivePhoto value)
    {
        return From(value);
    }

    public bool TryGetInputMediaLivePhoto(out InputMediaLivePhoto? value)
    {
        value = InputMediaLivePhoto;
        return value is not null;
    }

    /// <summary>
    /// Creates a InputMedia value from <c>InputMediaPhoto</c>.
    /// </summary>
    public static InputMedia From(InputMediaPhoto value)
    {
        return new InputMedia(value);
    }

    public static implicit operator InputMedia(InputMediaPhoto value)
    {
        return From(value);
    }

    public bool TryGetInputMediaPhoto(out InputMediaPhoto? value)
    {
        value = InputMediaPhoto;
        return value is not null;
    }

    /// <summary>
    /// Creates a InputMedia value from <c>InputMediaVideo</c>.
    /// </summary>
    public static InputMedia From(InputMediaVideo value)
    {
        return new InputMedia(value);
    }

    public static implicit operator InputMedia(InputMediaVideo value)
    {
        return From(value);
    }

    public bool TryGetInputMediaVideo(out InputMediaVideo? value)
    {
        value = InputMediaVideo;
        return value is not null;
    }

}

file sealed class InputMediaJsonConverter : JsonConverter<InputMedia>
{
    public override InputMedia Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.StartObject)
        {
            throw new JsonException("Unable to deserialize InputMedia: unexpected JSON token.");
        }

        using var document = JsonDocument.ParseValue(ref reader);
        var json = document.RootElement.GetRawText();

        if (document.RootElement.TryGetProperty("type", out var typeElement) && typeElement.ValueKind == JsonValueKind.String)
        {
            var discriminator = typeElement.GetString();
            switch (discriminator)
            {
                case "animation":
                    return InputMedia.From(JsonSerializer.Deserialize<InputMediaAnimation>(json, options)
                        ?? throw new JsonException("Unable to deserialize InputMedia as InputMediaAnimation."));
                case "audio":
                    return InputMedia.From(JsonSerializer.Deserialize<InputMediaAudio>(json, options)
                        ?? throw new JsonException("Unable to deserialize InputMedia as InputMediaAudio."));
                case "document":
                    return InputMedia.From(JsonSerializer.Deserialize<InputMediaDocument>(json, options)
                        ?? throw new JsonException("Unable to deserialize InputMedia as InputMediaDocument."));
                case "live_photo":
                    return InputMedia.From(JsonSerializer.Deserialize<InputMediaLivePhoto>(json, options)
                        ?? throw new JsonException("Unable to deserialize InputMedia as InputMediaLivePhoto."));
                case "photo":
                    return InputMedia.From(JsonSerializer.Deserialize<InputMediaPhoto>(json, options)
                        ?? throw new JsonException("Unable to deserialize InputMedia as InputMediaPhoto."));
                case "video":
                    return InputMedia.From(JsonSerializer.Deserialize<InputMediaVideo>(json, options)
                        ?? throw new JsonException("Unable to deserialize InputMedia as InputMediaVideo."));
                default:
                    throw new JsonException($"Unknown discriminator value '{discriminator}' for InputMedia.");
            }
        }

        throw new JsonException("Unable to deserialize InputMedia from the provided Telegram payload.");
    }

    public override void Write(Utf8JsonWriter writer, InputMedia value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(value);
        if (value.InputMediaAnimation is not null)
        {
            JsonSerializer.Serialize(writer, value.InputMediaAnimation, options);
            return;
        }

        if (value.InputMediaAudio is not null)
        {
            JsonSerializer.Serialize(writer, value.InputMediaAudio, options);
            return;
        }

        if (value.InputMediaDocument is not null)
        {
            JsonSerializer.Serialize(writer, value.InputMediaDocument, options);
            return;
        }

        if (value.InputMediaLivePhoto is not null)
        {
            JsonSerializer.Serialize(writer, value.InputMediaLivePhoto, options);
            return;
        }

        if (value.InputMediaPhoto is not null)
        {
            JsonSerializer.Serialize(writer, value.InputMediaPhoto, options);
            return;
        }

        if (value.InputMediaVideo is not null)
        {
            JsonSerializer.Serialize(writer, value.InputMediaVideo, options);
            return;
        }

        throw new JsonException("The InputMedia instance does not contain a union case value.");
    }
}