// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// An animated profile photo in the MPEG4 format.
/// </summary>
public sealed partial record class InputProfilePhotoAnimated : IJsonOnDeserialized
{
    /// <summary>
    /// Type of the profile photo, must be animated
    /// </summary>
    public const string TypeValue = "animated";

    [JsonPropertyName("type")]
    [JsonRequired]
    public string Type { get; init; } = TypeValue;

    /// <summary>
    /// The animated profile photo. Profile photos can&apos;t be reused and can only be uploaded as a new file, so you can pass “attach://&lt;file_attach_name&gt;” if the photo was uploaded using multipart/form-data under &lt;file_attach_name&gt;. More information on Sending Files »
    /// </summary>
    [JsonPropertyName("animation")]
    [JsonRequired]
    public required InputFileString Animation { get; init; } = null!;

    /// <summary>
    /// Timestamp in seconds of the frame that will be used as the static profile photo. Defaults to 0.0.
    /// </summary>
    [JsonPropertyName("main_frame_timestamp")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? MainFrameTimestamp { get; init; }

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Type != TypeValue)
        {
            throw new JsonException("Expected Telegram literal 'animated' for field 'type' on InputProfilePhotoAnimated.");
        }

    }
}