// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object describes the content of a story to post. Currently, it can be one of
/// </summary>
/// <remarks>
/// InputStoryContentPhoto
/// InputStoryContentVideo
/// Union members: InputStoryContentPhoto, InputStoryContentVideo.
/// </remarks>
[JsonConverter(typeof(InputStoryContentJsonConverter))]
public sealed partial record class InputStoryContent
{
    private InputStoryContent(InputStoryContentPhoto value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InputStoryContentPhoto = value;
    }

    private InputStoryContent(InputStoryContentVideo value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InputStoryContentVideo = value;
    }

    /// <summary>
    /// Gets the InputStoryContentPhoto value when this instance represents that case.
    /// </summary>
    public InputStoryContentPhoto? InputStoryContentPhoto { get; }

    /// <summary>
    /// Gets the InputStoryContentVideo value when this instance represents that case.
    /// </summary>
    public InputStoryContentVideo? InputStoryContentVideo { get; }

    /// <summary>
    /// Creates a InputStoryContent value from <c>InputStoryContentPhoto</c>.
    /// </summary>
    public static InputStoryContent From(InputStoryContentPhoto value)
    {
        return new InputStoryContent(value);
    }

    public static implicit operator InputStoryContent(InputStoryContentPhoto value)
    {
        return From(value);
    }

    public bool TryGetInputStoryContentPhoto(out InputStoryContentPhoto? value)
    {
        value = InputStoryContentPhoto;
        return value is not null;
    }

    /// <summary>
    /// Creates a InputStoryContent value from <c>InputStoryContentVideo</c>.
    /// </summary>
    public static InputStoryContent From(InputStoryContentVideo value)
    {
        return new InputStoryContent(value);
    }

    public static implicit operator InputStoryContent(InputStoryContentVideo value)
    {
        return From(value);
    }

    public bool TryGetInputStoryContentVideo(out InputStoryContentVideo? value)
    {
        value = InputStoryContentVideo;
        return value is not null;
    }

}

file sealed class InputStoryContentJsonConverter : JsonConverter<InputStoryContent>
{
    public override InputStoryContent Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.StartObject)
        {
            throw new JsonException("Unable to deserialize InputStoryContent: unexpected JSON token.");
        }

        using var document = JsonDocument.ParseValue(ref reader);

        if (document.RootElement.TryGetProperty("type", out var typeElement) && typeElement.ValueKind == JsonValueKind.String)
        {
            var discriminator = typeElement.GetString();
            switch (discriminator)
            {
                case "photo":
                    return InputStoryContent.From(document.RootElement.Deserialize<InputStoryContentPhoto>(options)
                        ?? throw new JsonException("Unable to deserialize InputStoryContent as InputStoryContentPhoto."));
                case "video":
                    return InputStoryContent.From(document.RootElement.Deserialize<InputStoryContentVideo>(options)
                        ?? throw new JsonException("Unable to deserialize InputStoryContent as InputStoryContentVideo."));
                default:
                    throw new JsonException($"Unknown discriminator value '{discriminator}' for InputStoryContent.");
            }
        }

        throw new JsonException("Unable to deserialize InputStoryContent from the provided Telegram payload.");
    }

    public override void Write(Utf8JsonWriter writer, InputStoryContent value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(value);
        if (value.InputStoryContentPhoto is not null)
        {
            JsonSerializer.Serialize(writer, value.InputStoryContentPhoto, options);
            return;
        }

        if (value.InputStoryContentVideo is not null)
        {
            JsonSerializer.Serialize(writer, value.InputStoryContentVideo, options);
            return;
        }

        throw new JsonException("The InputStoryContent instance does not contain a union case value.");
    }
}