// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object contains information about one answer option in a poll to be sent.
/// </summary>
public sealed partial record class InputPollOption
{
    /// <summary>
    /// Option text, 1-100 characters
    /// </summary>
    [JsonPropertyName("text")]
    [JsonRequired]
    public required string Text { get; init; } = null!;

    /// <summary>
    /// Mode for parsing entities in the text. See formatting options for more details. Currently, only custom emoji entities are allowed.
    /// </summary>
    [JsonPropertyName("text_parse_mode")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? TextParseMode { get; init; }

    /// <summary>
    /// A JSON-serialized list of special entities that appear in the poll option text. It can be specified instead of text_parse_mode.
    /// </summary>
    [JsonPropertyName("text_entities")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<MessageEntity>? TextEntities { get; init; }

    /// <summary>
    /// Media added to the poll option
    /// </summary>
    [JsonPropertyName("media")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public InputPollOptionMedia? Media { get; init; }

}