// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.3
//   Telegram Bot API release: 2026-08-24
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#august-24-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// A block containing a list of buttons that are shown in one row, corresponding to the custom HTML tag &lt;tg-button-row&gt;.
/// </summary>
public sealed partial record class InputRichBlockButtons : IJsonOnDeserialized
{
    /// <summary>
    /// Type of the block, always “buttons”
    /// </summary>
    public const string TypeValue = "buttons";

    [JsonPropertyName("type")]
    [JsonRequired]
    public string Type { get; init; } = TypeValue;

    /// <summary>
    /// List of 1-8 buttons to send
    /// </summary>
    [JsonPropertyName("buttons")]
    [JsonRequired]
    public required IReadOnlyList<RichMessageButton> Buttons { get; init; } = null!;

    /// <summary>
    /// Horizontal alignment of the buttons. Currently, must be one of “left”, “center”, or “right”.
    /// </summary>
    [JsonPropertyName("align")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Align { get; init; }

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Type != TypeValue)
        {
            throw new JsonException("Expected Telegram literal 'buttons' for field 'type' on InputRichBlockButtons.");
        }

    }
}