// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-25T20:26:26.1770012+00:00
//   Source SHA-256: bad109f0fc19b3b0d1703be99fa0161ca066363d8fca62e1165527885add506f
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Describes a task to add to a checklist.
/// </summary>
public sealed partial record class InputChecklistTask
{
    /// <summary>
    /// Unique identifier of the task; must be positive and unique among all task identifiers currently present in the checklist
    /// </summary>
    [JsonPropertyName("id")]
    [JsonRequired]
    public required long Id { get; init; }

    /// <summary>
    /// Text of the task; 1-100 characters after entities parsing
    /// </summary>
    [JsonPropertyName("text")]
    [JsonRequired]
    public required string Text { get; init; } = null!;

    /// <summary>
    /// Mode for parsing entities in the text. See formatting options for more details.
    /// </summary>
    [JsonPropertyName("parse_mode")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ParseMode { get; init; }

    /// <summary>
    /// List of special entities that appear in the text, which can be specified instead of parse_mode. Currently, only bold, italic, underline, strikethrough, spoiler, custom_emoji, and date_time entities are allowed.
    /// </summary>
    [JsonPropertyName("text_entities")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<MessageEntity>? TextEntities { get; init; }

}