// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object describes a profile photo to set. Currently, it can be one of
/// </summary>
/// <remarks>
/// InputProfilePhotoStatic
/// InputProfilePhotoAnimated
/// Union members: InputProfilePhotoStatic, InputProfilePhotoAnimated.
/// </remarks>
[JsonConverter(typeof(InputProfilePhotoJsonConverter))]
public sealed partial record class InputProfilePhoto
{
    private InputProfilePhoto(InputProfilePhotoStatic value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InputProfilePhotoStatic = value;
    }

    private InputProfilePhoto(InputProfilePhotoAnimated value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InputProfilePhotoAnimated = value;
    }

    /// <summary>
    /// Gets the InputProfilePhotoStatic value when this instance represents that case.
    /// </summary>
    public InputProfilePhotoStatic? InputProfilePhotoStatic { get; }

    /// <summary>
    /// Gets the InputProfilePhotoAnimated value when this instance represents that case.
    /// </summary>
    public InputProfilePhotoAnimated? InputProfilePhotoAnimated { get; }

    /// <summary>
    /// Creates a InputProfilePhoto value from <c>InputProfilePhotoStatic</c>.
    /// </summary>
    public static InputProfilePhoto From(InputProfilePhotoStatic value)
    {
        return new InputProfilePhoto(value);
    }

    public static implicit operator InputProfilePhoto(InputProfilePhotoStatic value)
    {
        return From(value);
    }

    public bool TryGetInputProfilePhotoStatic(out InputProfilePhotoStatic? value)
    {
        value = InputProfilePhotoStatic;
        return value is not null;
    }

    /// <summary>
    /// Creates a InputProfilePhoto value from <c>InputProfilePhotoAnimated</c>.
    /// </summary>
    public static InputProfilePhoto From(InputProfilePhotoAnimated value)
    {
        return new InputProfilePhoto(value);
    }

    public static implicit operator InputProfilePhoto(InputProfilePhotoAnimated value)
    {
        return From(value);
    }

    public bool TryGetInputProfilePhotoAnimated(out InputProfilePhotoAnimated? value)
    {
        value = InputProfilePhotoAnimated;
        return value is not null;
    }

}

file sealed class InputProfilePhotoJsonConverter : JsonConverter<InputProfilePhoto>
{
    public override InputProfilePhoto Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.StartObject)
        {
            throw new JsonException("Unable to deserialize InputProfilePhoto: unexpected JSON token.");
        }

        using var document = JsonDocument.ParseValue(ref reader);

        if (document.RootElement.TryGetProperty("type", out var typeElement) && typeElement.ValueKind == JsonValueKind.String)
        {
            var discriminator = typeElement.GetString();
            switch (discriminator)
            {
                case "animated":
                    return InputProfilePhoto.From(document.RootElement.Deserialize<InputProfilePhotoAnimated>(options)
                        ?? throw new JsonException("Unable to deserialize InputProfilePhoto as InputProfilePhotoAnimated."));
                case "static":
                    return InputProfilePhoto.From(document.RootElement.Deserialize<InputProfilePhotoStatic>(options)
                        ?? throw new JsonException("Unable to deserialize InputProfilePhoto as InputProfilePhotoStatic."));
                default:
                    throw new JsonException($"Unknown discriminator value '{discriminator}' for InputProfilePhoto.");
            }
        }

        throw new JsonException("Unable to deserialize InputProfilePhoto from the provided Telegram payload.");
    }

    public override void Write(Utf8JsonWriter writer, InputProfilePhoto value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(value);
        if (value.InputProfilePhotoStatic is not null)
        {
            JsonSerializer.Serialize(writer, value.InputProfilePhotoStatic, options);
            return;
        }

        if (value.InputProfilePhotoAnimated is not null)
        {
            JsonSerializer.Serialize(writer, value.InputProfilePhotoAnimated, options);
            return;
        }

        throw new JsonException("The InputProfilePhoto instance does not contain a union case value.");
    }
}