// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Represents the content of an invoice message to be sent as the result of an inline query.
/// </summary>
public sealed partial record class InputInvoiceMessageContent
{
    /// <summary>
    /// Product name, 1-32 characters
    /// </summary>
    [JsonPropertyName("title")]
    [JsonRequired]
    public required string Title { get; init; } = null!;

    /// <summary>
    /// Product description, 1-255 characters
    /// </summary>
    [JsonPropertyName("description")]
    [JsonRequired]
    public required string Description { get; init; } = null!;

    /// <summary>
    /// Bot-defined invoice payload, 1-128 bytes. This will not be displayed to the user, use it for your internal processes.
    /// </summary>
    [JsonPropertyName("payload")]
    [JsonRequired]
    public required string Payload { get; init; } = null!;

    /// <summary>
    /// Payment provider token, obtained via @BotFather. Pass an empty string for payments in Telegram Stars.
    /// </summary>
    [JsonPropertyName("provider_token")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ProviderToken { get; init; }

    /// <summary>
    /// Three-letter ISO 4217 currency code, see more on currencies. Pass “XTR” for payments in Telegram Stars.
    /// </summary>
    [JsonPropertyName("currency")]
    [JsonRequired]
    public required string Currency { get; init; } = null!;

    /// <summary>
    /// Price breakdown, a JSON-serialized list of components (e.g. product price, tax, discount, delivery cost, delivery tax, bonus, etc.). Must contain exactly one item for payments in Telegram Stars.
    /// </summary>
    [JsonPropertyName("prices")]
    [JsonRequired]
    public required IReadOnlyList<LabeledPrice> Prices { get; init; } = null!;

    /// <summary>
    /// The maximum accepted amount for tips in the smallest units of the currency (integer, not float/double). For example, for a maximum tip of US$ 1.45 pass max_tip_amount = 145. See the exp parameter in currencies.json, it shows the number of digits past the decimal point for each currency (2 for the majority of currencies). Defaults to 0. Not supported for payments in Telegram Stars.
    /// </summary>
    [JsonPropertyName("max_tip_amount")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? MaxTipAmount { get; init; }

    /// <summary>
    /// A JSON-serialized Array of suggested amounts of tip in the smallest units of the currency (integer, not float/double). At most 4 suggested tip amounts can be specified. The suggested tip amounts must be positive, passed in a strictly increased order and must not exceed max_tip_amount.
    /// </summary>
    [JsonPropertyName("suggested_tip_amounts")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<long>? SuggestedTipAmounts { get; init; }

    /// <summary>
    /// A JSON-serialized object for data about the invoice, which will be shared with the payment provider. A detailed description of the required fields should be provided by the payment provider.
    /// </summary>
    [JsonPropertyName("provider_data")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ProviderData { get; init; }

    /// <summary>
    /// URL of the product photo for the invoice. Can be a photo of the goods or a marketing image for a service.
    /// </summary>
    [JsonPropertyName("photo_url")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? PhotoUrl { get; init; }

    /// <summary>
    /// Photo size in bytes
    /// </summary>
    [JsonPropertyName("photo_size")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? PhotoSize { get; init; }

    /// <summary>
    /// Photo width
    /// </summary>
    [JsonPropertyName("photo_width")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? PhotoWidth { get; init; }

    /// <summary>
    /// Photo height
    /// </summary>
    [JsonPropertyName("photo_height")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? PhotoHeight { get; init; }

    /// <summary>
    /// Pass True if you require the user&apos;s full name to complete the order. Ignored for payments in Telegram Stars.
    /// </summary>
    [JsonPropertyName("need_name")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? NeedName { get; init; }

    /// <summary>
    /// Pass True if you require the user&apos;s phone number to complete the order. Ignored for payments in Telegram Stars.
    /// </summary>
    [JsonPropertyName("need_phone_number")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? NeedPhoneNumber { get; init; }

    /// <summary>
    /// Pass True if you require the user&apos;s email address to complete the order. Ignored for payments in Telegram Stars.
    /// </summary>
    [JsonPropertyName("need_email")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? NeedEmail { get; init; }

    /// <summary>
    /// Pass True if you require the user&apos;s shipping address to complete the order. Ignored for payments in Telegram Stars.
    /// </summary>
    [JsonPropertyName("need_shipping_address")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? NeedShippingAddress { get; init; }

    /// <summary>
    /// Pass True if the user&apos;s phone number should be sent to the provider. Ignored for payments in Telegram Stars.
    /// </summary>
    [JsonPropertyName("send_phone_number_to_provider")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? SendPhoneNumberToProvider { get; init; }

    /// <summary>
    /// Pass True if the user&apos;s email address should be sent to the provider. Ignored for payments in Telegram Stars.
    /// </summary>
    [JsonPropertyName("send_email_to_provider")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? SendEmailToProvider { get; init; }

    /// <summary>
    /// Pass True if the final price depends on the shipping method. Ignored for payments in Telegram Stars.
    /// </summary>
    [JsonPropertyName("is_flexible")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? IsFlexible { get; init; }

}