// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using TeleFlow.Telegram.Schema.Abstractions;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Represents a photo to be sent.
/// </summary>
public sealed partial record class InputMediaPhoto : IJsonOnDeserialized
{
    /// <summary>
    /// Type of the media, must be photo
    /// </summary>
    public const string TypeValue = "photo";

    [JsonPropertyName("type")]
    [JsonRequired]
    public string Type { get; init; } = TypeValue;

    /// <summary>
    /// File to send. Pass a file_id to send a file that exists on the Telegram servers (recommended), pass an HTTP URL for Telegram to get a file from the Internet, or pass “attach://&lt;file_attach_name&gt;” to upload a new one using multipart/form-data under &lt;file_attach_name&gt; name. More information on Sending Files »
    /// </summary>
    [JsonPropertyName("media")]
    [JsonRequired]
    public required InputFileString Media { get; init; } = null!;

    /// <summary>
    /// Caption of the photo to be sent, 0-1024 characters after entities parsing
    /// </summary>
    [JsonPropertyName("caption")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Caption { get; init; }

    /// <summary>
    /// Mode for parsing entities in the photo caption. See formatting options for more details.
    /// </summary>
    [JsonPropertyName("parse_mode")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ParseMode { get; init; }

    /// <summary>
    /// List of special entities that appear in the caption, which can be specified instead of parse_mode
    /// </summary>
    [JsonPropertyName("caption_entities")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<MessageEntity>? CaptionEntities { get; init; }

    /// <summary>
    /// Pass True if the caption must be shown above the message media
    /// </summary>
    [JsonPropertyName("show_caption_above_media")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? ShowCaptionAboveMedia { get; init; }

    /// <summary>
    /// Pass True if the photo needs to be covered with a spoiler animation
    /// </summary>
    [JsonPropertyName("has_spoiler")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? HasSpoiler { get; init; }

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Type != TypeValue)
        {
            throw new JsonException("Expected Telegram literal 'photo' for field 'type' on InputMediaPhoto.");
        }

    }
}