// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object contains basic information about an invoice.
/// </summary>
public sealed partial record class Invoice
{
    /// <summary>
    /// Product name
    /// </summary>
    [JsonPropertyName("title")]
    [JsonRequired]
    public required string Title { get; init; } = null!;

    /// <summary>
    /// Product description
    /// </summary>
    [JsonPropertyName("description")]
    [JsonRequired]
    public required string Description { get; init; } = null!;

    /// <summary>
    /// Unique bot deep-linking parameter that can be used to generate this invoice
    /// </summary>
    [JsonPropertyName("start_parameter")]
    [JsonRequired]
    public required string StartParameter { get; init; } = null!;

    /// <summary>
    /// Three-letter ISO 4217 currency code, or “XTR” for payments in Telegram Stars
    /// </summary>
    [JsonPropertyName("currency")]
    [JsonRequired]
    public required string Currency { get; init; } = null!;

    /// <summary>
    /// Total price in the smallest units of the currency (integer, not float/double). For example, for a price of US$ 1.45 pass amount = 145. See the exp parameter in currencies.json, it shows the number of digits past the decimal point for each currency (2 for the majority of currencies).
    /// </summary>
    [JsonPropertyName("total_amount")]
    [JsonRequired]
    public required long TotalAmount { get; init; }

}