// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object describes the position on faces where a mask should be placed by default.
/// </summary>
public sealed partial record class MaskPosition
{
    /// <summary>
    /// The part of the face relative to which the mask should be placed. One of “forehead”, “eyes”, “mouth”, or “chin”.
    /// </summary>
    [JsonPropertyName("point")]
    [JsonRequired]
    public required string Point { get; init; } = null!;

    /// <summary>
    /// Shift by X-axis measured in widths of the mask scaled to the face size, from left to right. For example, choosing -1.0 will place mask just to the left of the default mask position.
    /// </summary>
    [JsonPropertyName("x_shift")]
    [JsonRequired]
    public required double XShift { get; init; }

    /// <summary>
    /// Shift by Y-axis measured in heights of the mask scaled to the face size, from top to bottom. For example, 1.0 will place the mask just below the default mask position.
    /// </summary>
    [JsonPropertyName("y_shift")]
    [JsonRequired]
    public required double YShift { get; init; }

    /// <summary>
    /// Mask scaling coefficient. For example, 2.0 means double size.
    /// </summary>
    [JsonPropertyName("scale")]
    [JsonRequired]
    public required double Scale { get; init; }

}