// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object describes a message that can be inaccessible to the bot. It can be one of
/// </summary>
/// <remarks>
/// Message
/// InaccessibleMessage
/// Union members: Message, InaccessibleMessage.
/// </remarks>
[JsonConverter(typeof(MaybeInaccessibleMessageJsonConverter))]
public sealed partial record class MaybeInaccessibleMessage
{
    private MaybeInaccessibleMessage(Message value)
    {
        ArgumentNullException.ThrowIfNull(value);
        Message = value;
    }

    private MaybeInaccessibleMessage(InaccessibleMessage value)
    {
        ArgumentNullException.ThrowIfNull(value);
        InaccessibleMessage = value;
    }

    /// <summary>
    /// Gets the Message value when this instance represents that case.
    /// </summary>
    public Message? Message { get; }

    /// <summary>
    /// Gets the InaccessibleMessage value when this instance represents that case.
    /// </summary>
    public InaccessibleMessage? InaccessibleMessage { get; }

    /// <summary>
    /// Creates a MaybeInaccessibleMessage value from <c>Message</c>.
    /// </summary>
    public static MaybeInaccessibleMessage From(Message value)
    {
        return new MaybeInaccessibleMessage(value);
    }

    public static implicit operator MaybeInaccessibleMessage(Message value)
    {
        return From(value);
    }

    public bool TryGetMessage(out Message? value)
    {
        value = Message;
        return value is not null;
    }

    /// <summary>
    /// Creates a MaybeInaccessibleMessage value from <c>InaccessibleMessage</c>.
    /// </summary>
    public static MaybeInaccessibleMessage From(InaccessibleMessage value)
    {
        return new MaybeInaccessibleMessage(value);
    }

    public static implicit operator MaybeInaccessibleMessage(InaccessibleMessage value)
    {
        return From(value);
    }

    public bool TryGetInaccessibleMessage(out InaccessibleMessage? value)
    {
        value = InaccessibleMessage;
        return value is not null;
    }

}

file sealed class MaybeInaccessibleMessageJsonConverter : JsonConverter<MaybeInaccessibleMessage>
{
    public override MaybeInaccessibleMessage Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.StartObject)
        {
            throw new JsonException("Unable to deserialize MaybeInaccessibleMessage: unexpected JSON token.");
        }

        using var document = JsonDocument.ParseValue(ref reader);

        if (document.RootElement.TryGetProperty("date", out var dateElement) &&
            dateElement.ValueKind == JsonValueKind.Number &&
            dateElement.TryGetInt64(out var date) &&
            date == 0)
        {
            return MaybeInaccessibleMessage.From(document.RootElement.Deserialize<InaccessibleMessage>(options)
                ?? throw new JsonException("Unable to deserialize MaybeInaccessibleMessage as InaccessibleMessage."));
        }

        return MaybeInaccessibleMessage.From(document.RootElement.Deserialize<Message>(options)
            ?? throw new JsonException("Unable to deserialize MaybeInaccessibleMessage as Message."));
        throw new JsonException("Unable to deserialize MaybeInaccessibleMessage from the provided Telegram payload.");
    }

    public override void Write(Utf8JsonWriter writer, MaybeInaccessibleMessage value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(value);
        if (value.Message is not null)
        {
            JsonSerializer.Serialize(writer, value.Message, options);
            return;
        }

        if (value.InaccessibleMessage is not null)
        {
            JsonSerializer.Serialize(writer, value.InaccessibleMessage, options);
            return;
        }

        throw new JsonException("The MaybeInaccessibleMessage instance does not contain a union case value.");
    }
}