// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-25T20:26:26.1770012+00:00
//   Source SHA-256: bad109f0fc19b3b0d1703be99fa0161ca066363d8fca62e1165527885add506f
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object represents reaction changes on a message with anonymous reactions.
/// </summary>
public sealed partial record class MessageReactionCountUpdated
{
    /// <summary>
    /// The chat containing the message
    /// </summary>
    [JsonPropertyName("chat")]
    [JsonRequired]
    public required Chat Chat { get; init; } = null!;

    /// <summary>
    /// Unique message identifier inside the chat
    /// </summary>
    [JsonPropertyName("message_id")]
    [JsonRequired]
    public required long MessageId { get; init; }

    /// <summary>
    /// Date of the change in Unix time
    /// </summary>
    [JsonPropertyName("date")]
    [JsonRequired]
    public required long Date { get; init; }

    /// <summary>
    /// List of reactions that are present on the message
    /// </summary>
    [JsonPropertyName("reactions")]
    [JsonRequired]
    public required IReadOnlyList<ReactionCount> Reactions { get; init; } = null!;

}