// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object describes the origin of a message. It can be one of
/// </summary>
/// <remarks>
/// MessageOriginUser
/// MessageOriginHiddenUser
/// MessageOriginChat
/// MessageOriginChannel
/// Union members: MessageOriginUser, MessageOriginHiddenUser, MessageOriginChat, MessageOriginChannel.
/// </remarks>
[JsonConverter(typeof(MessageOriginJsonConverter))]
public sealed partial record class MessageOrigin
{
    private MessageOrigin(MessageOriginUser value)
    {
        ArgumentNullException.ThrowIfNull(value);
        MessageOriginUser = value;
    }

    private MessageOrigin(MessageOriginHiddenUser value)
    {
        ArgumentNullException.ThrowIfNull(value);
        MessageOriginHiddenUser = value;
    }

    private MessageOrigin(MessageOriginChat value)
    {
        ArgumentNullException.ThrowIfNull(value);
        MessageOriginChat = value;
    }

    private MessageOrigin(MessageOriginChannel value)
    {
        ArgumentNullException.ThrowIfNull(value);
        MessageOriginChannel = value;
    }

    /// <summary>
    /// Gets the MessageOriginUser value when this instance represents that case.
    /// </summary>
    public MessageOriginUser? MessageOriginUser { get; }

    /// <summary>
    /// Gets the MessageOriginHiddenUser value when this instance represents that case.
    /// </summary>
    public MessageOriginHiddenUser? MessageOriginHiddenUser { get; }

    /// <summary>
    /// Gets the MessageOriginChat value when this instance represents that case.
    /// </summary>
    public MessageOriginChat? MessageOriginChat { get; }

    /// <summary>
    /// Gets the MessageOriginChannel value when this instance represents that case.
    /// </summary>
    public MessageOriginChannel? MessageOriginChannel { get; }

    /// <summary>
    /// Creates a MessageOrigin value from <c>MessageOriginUser</c>.
    /// </summary>
    public static MessageOrigin From(MessageOriginUser value)
    {
        return new MessageOrigin(value);
    }

    public static implicit operator MessageOrigin(MessageOriginUser value)
    {
        return From(value);
    }

    public bool TryGetMessageOriginUser(out MessageOriginUser? value)
    {
        value = MessageOriginUser;
        return value is not null;
    }

    /// <summary>
    /// Creates a MessageOrigin value from <c>MessageOriginHiddenUser</c>.
    /// </summary>
    public static MessageOrigin From(MessageOriginHiddenUser value)
    {
        return new MessageOrigin(value);
    }

    public static implicit operator MessageOrigin(MessageOriginHiddenUser value)
    {
        return From(value);
    }

    public bool TryGetMessageOriginHiddenUser(out MessageOriginHiddenUser? value)
    {
        value = MessageOriginHiddenUser;
        return value is not null;
    }

    /// <summary>
    /// Creates a MessageOrigin value from <c>MessageOriginChat</c>.
    /// </summary>
    public static MessageOrigin From(MessageOriginChat value)
    {
        return new MessageOrigin(value);
    }

    public static implicit operator MessageOrigin(MessageOriginChat value)
    {
        return From(value);
    }

    public bool TryGetMessageOriginChat(out MessageOriginChat? value)
    {
        value = MessageOriginChat;
        return value is not null;
    }

    /// <summary>
    /// Creates a MessageOrigin value from <c>MessageOriginChannel</c>.
    /// </summary>
    public static MessageOrigin From(MessageOriginChannel value)
    {
        return new MessageOrigin(value);
    }

    public static implicit operator MessageOrigin(MessageOriginChannel value)
    {
        return From(value);
    }

    public bool TryGetMessageOriginChannel(out MessageOriginChannel? value)
    {
        value = MessageOriginChannel;
        return value is not null;
    }

}

file sealed class MessageOriginJsonConverter : JsonConverter<MessageOrigin>
{
    public override MessageOrigin Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.StartObject)
        {
            throw new JsonException("Unable to deserialize MessageOrigin: unexpected JSON token.");
        }

        using var document = JsonDocument.ParseValue(ref reader);

        if (document.RootElement.TryGetProperty("type", out var typeElement) && typeElement.ValueKind == JsonValueKind.String)
        {
            var discriminator = typeElement.GetString();
            switch (discriminator)
            {
                case "channel":
                    return MessageOrigin.From(document.RootElement.Deserialize<MessageOriginChannel>(options)
                        ?? throw new JsonException("Unable to deserialize MessageOrigin as MessageOriginChannel."));
                case "chat":
                    return MessageOrigin.From(document.RootElement.Deserialize<MessageOriginChat>(options)
                        ?? throw new JsonException("Unable to deserialize MessageOrigin as MessageOriginChat."));
                case "hidden_user":
                    return MessageOrigin.From(document.RootElement.Deserialize<MessageOriginHiddenUser>(options)
                        ?? throw new JsonException("Unable to deserialize MessageOrigin as MessageOriginHiddenUser."));
                case "user":
                    return MessageOrigin.From(document.RootElement.Deserialize<MessageOriginUser>(options)
                        ?? throw new JsonException("Unable to deserialize MessageOrigin as MessageOriginUser."));
                default:
                    throw new JsonException($"Unknown discriminator value '{discriminator}' for MessageOrigin.");
            }
        }

        throw new JsonException("Unable to deserialize MessageOrigin from the provided Telegram payload.");
    }

    public override void Write(Utf8JsonWriter writer, MessageOrigin value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(value);
        if (value.MessageOriginUser is not null)
        {
            JsonSerializer.Serialize(writer, value.MessageOriginUser, options);
            return;
        }

        if (value.MessageOriginHiddenUser is not null)
        {
            JsonSerializer.Serialize(writer, value.MessageOriginHiddenUser, options);
            return;
        }

        if (value.MessageOriginChat is not null)
        {
            JsonSerializer.Serialize(writer, value.MessageOriginChat, options);
            return;
        }

        if (value.MessageOriginChannel is not null)
        {
            JsonSerializer.Serialize(writer, value.MessageOriginChannel, options);
            return;
        }

        throw new JsonException("The MessageOrigin instance does not contain a union case value.");
    }
}