// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Contains the list of gifts received and owned by a user or a chat.
/// </summary>
public sealed partial record class OwnedGifts
{
    /// <summary>
    /// The total number of gifts owned by the user or the chat
    /// </summary>
    [JsonPropertyName("total_count")]
    [JsonRequired]
    public required long TotalCount { get; init; }

    /// <summary>
    /// The list of gifts
    /// </summary>
    [JsonPropertyName("gifts")]
    [JsonRequired]
    public required IReadOnlyList<OwnedGift> Gifts { get; init; } = null!;

    /// <summary>
    /// Offset for the next request. If empty, then there are no more results.
    /// </summary>
    [JsonPropertyName("next_offset")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? NextOffset { get; init; }

}