// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// The paid media is a photo.
/// </summary>
public sealed partial record class PaidMediaPhoto : IJsonOnDeserialized
{
    /// <summary>
    /// Type of the paid media, always “photo”
    /// </summary>
    public const string TypeValue = "photo";

    [JsonPropertyName("type")]
    [JsonRequired]
    public string Type { get; init; } = TypeValue;

    /// <summary>
    /// The photo
    /// </summary>
    [JsonPropertyName("photo")]
    [JsonRequired]
    public required IReadOnlyList<PhotoSize> Photo { get; init; } = null!;

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Type != TypeValue)
        {
            throw new JsonException("Expected Telegram literal 'photo' for field 'type' on PaidMediaPhoto.");
        }

    }
}