// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object describes paid media. Currently, it can be one of
/// </summary>
/// <remarks>
/// PaidMediaLivePhoto
/// PaidMediaPhoto
/// PaidMediaPreview
/// PaidMediaVideo
/// Union members: PaidMediaLivePhoto, PaidMediaPhoto, PaidMediaPreview, PaidMediaVideo.
/// </remarks>
[JsonConverter(typeof(PaidMediaJsonConverter))]
public sealed partial record class PaidMedia
{
    private PaidMedia(PaidMediaLivePhoto value)
    {
        ArgumentNullException.ThrowIfNull(value);
        PaidMediaLivePhoto = value;
    }

    private PaidMedia(PaidMediaPhoto value)
    {
        ArgumentNullException.ThrowIfNull(value);
        PaidMediaPhoto = value;
    }

    private PaidMedia(PaidMediaPreview value)
    {
        ArgumentNullException.ThrowIfNull(value);
        PaidMediaPreview = value;
    }

    private PaidMedia(PaidMediaVideo value)
    {
        ArgumentNullException.ThrowIfNull(value);
        PaidMediaVideo = value;
    }

    /// <summary>
    /// Gets the PaidMediaLivePhoto value when this instance represents that case.
    /// </summary>
    public PaidMediaLivePhoto? PaidMediaLivePhoto { get; }

    /// <summary>
    /// Gets the PaidMediaPhoto value when this instance represents that case.
    /// </summary>
    public PaidMediaPhoto? PaidMediaPhoto { get; }

    /// <summary>
    /// Gets the PaidMediaPreview value when this instance represents that case.
    /// </summary>
    public PaidMediaPreview? PaidMediaPreview { get; }

    /// <summary>
    /// Gets the PaidMediaVideo value when this instance represents that case.
    /// </summary>
    public PaidMediaVideo? PaidMediaVideo { get; }

    /// <summary>
    /// Creates a PaidMedia value from <c>PaidMediaLivePhoto</c>.
    /// </summary>
    public static PaidMedia From(PaidMediaLivePhoto value)
    {
        return new PaidMedia(value);
    }

    public static implicit operator PaidMedia(PaidMediaLivePhoto value)
    {
        return From(value);
    }

    public bool TryGetPaidMediaLivePhoto(out PaidMediaLivePhoto? value)
    {
        value = PaidMediaLivePhoto;
        return value is not null;
    }

    /// <summary>
    /// Creates a PaidMedia value from <c>PaidMediaPhoto</c>.
    /// </summary>
    public static PaidMedia From(PaidMediaPhoto value)
    {
        return new PaidMedia(value);
    }

    public static implicit operator PaidMedia(PaidMediaPhoto value)
    {
        return From(value);
    }

    public bool TryGetPaidMediaPhoto(out PaidMediaPhoto? value)
    {
        value = PaidMediaPhoto;
        return value is not null;
    }

    /// <summary>
    /// Creates a PaidMedia value from <c>PaidMediaPreview</c>.
    /// </summary>
    public static PaidMedia From(PaidMediaPreview value)
    {
        return new PaidMedia(value);
    }

    public static implicit operator PaidMedia(PaidMediaPreview value)
    {
        return From(value);
    }

    public bool TryGetPaidMediaPreview(out PaidMediaPreview? value)
    {
        value = PaidMediaPreview;
        return value is not null;
    }

    /// <summary>
    /// Creates a PaidMedia value from <c>PaidMediaVideo</c>.
    /// </summary>
    public static PaidMedia From(PaidMediaVideo value)
    {
        return new PaidMedia(value);
    }

    public static implicit operator PaidMedia(PaidMediaVideo value)
    {
        return From(value);
    }

    public bool TryGetPaidMediaVideo(out PaidMediaVideo? value)
    {
        value = PaidMediaVideo;
        return value is not null;
    }

}

file sealed class PaidMediaJsonConverter : JsonConverter<PaidMedia>
{
    public override PaidMedia Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.StartObject)
        {
            throw new JsonException("Unable to deserialize PaidMedia: unexpected JSON token.");
        }

        using var document = JsonDocument.ParseValue(ref reader);

        if (document.RootElement.TryGetProperty("type", out var typeElement) && typeElement.ValueKind == JsonValueKind.String)
        {
            var discriminator = typeElement.GetString();
            switch (discriminator)
            {
                case "live_photo":
                    return PaidMedia.From(document.RootElement.Deserialize<PaidMediaLivePhoto>(options)
                        ?? throw new JsonException("Unable to deserialize PaidMedia as PaidMediaLivePhoto."));
                case "photo":
                    return PaidMedia.From(document.RootElement.Deserialize<PaidMediaPhoto>(options)
                        ?? throw new JsonException("Unable to deserialize PaidMedia as PaidMediaPhoto."));
                case "preview":
                    return PaidMedia.From(document.RootElement.Deserialize<PaidMediaPreview>(options)
                        ?? throw new JsonException("Unable to deserialize PaidMedia as PaidMediaPreview."));
                case "video":
                    return PaidMedia.From(document.RootElement.Deserialize<PaidMediaVideo>(options)
                        ?? throw new JsonException("Unable to deserialize PaidMedia as PaidMediaVideo."));
                default:
                    throw new JsonException($"Unknown discriminator value '{discriminator}' for PaidMedia.");
            }
        }

        throw new JsonException("Unable to deserialize PaidMedia from the provided Telegram payload.");
    }

    public override void Write(Utf8JsonWriter writer, PaidMedia value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(value);
        if (value.PaidMediaLivePhoto is not null)
        {
            JsonSerializer.Serialize(writer, value.PaidMediaLivePhoto, options);
            return;
        }

        if (value.PaidMediaPhoto is not null)
        {
            JsonSerializer.Serialize(writer, value.PaidMediaPhoto, options);
            return;
        }

        if (value.PaidMediaPreview is not null)
        {
            JsonSerializer.Serialize(writer, value.PaidMediaPreview, options);
            return;
        }

        if (value.PaidMediaVideo is not null)
        {
            JsonSerializer.Serialize(writer, value.PaidMediaVideo, options);
            return;
        }

        throw new JsonException("The PaidMedia instance does not contain a union case value.");
    }
}