// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-25T20:26:26.1770012+00:00
//   Source SHA-256: bad109f0fc19b3b0d1703be99fa0161ca066363d8fca62e1165527885add506f
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Represents an issue in one of the data fields that was provided by the user. The error is considered resolved when the field&apos;s value changes.
/// </summary>
public sealed partial record class PassportElementErrorDataField : IJsonOnDeserialized
{
    /// <summary>
    /// Error source, must be data
    /// </summary>
    public const string SourceValue = "data";

    [JsonPropertyName("source")]
    [JsonRequired]
    public string Source { get; init; } = SourceValue;

    /// <summary>
    /// The section of the user&apos;s Telegram Passport which has the error, one of “personal_details”, “passport”, “driver_license”, “identity_card”, “internal_passport”, “address”
    /// </summary>
    [JsonPropertyName("type")]
    [JsonRequired]
    public required string Type { get; init; } = null!;

    /// <summary>
    /// Name of the data field which has the error
    /// </summary>
    [JsonPropertyName("field_name")]
    [JsonRequired]
    public required string FieldName { get; init; } = null!;

    /// <summary>
    /// Base64-encoded data hash
    /// </summary>
    [JsonPropertyName("data_hash")]
    [JsonRequired]
    public required string DataHash { get; init; } = null!;

    /// <summary>
    /// Error message
    /// </summary>
    [JsonPropertyName("message")]
    [JsonRequired]
    public required string Message { get; init; } = null!;

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Source != SourceValue)
        {
            throw new JsonException("Expected Telegram literal 'data' for field 'source' on PassportElementErrorDataField.");
        }

    }
}