// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Represents an issue with a document scan. The error is considered resolved when the file with the document scan changes.
/// </summary>
public sealed partial record class PassportElementErrorFile : IJsonOnDeserialized
{
    /// <summary>
    /// Error source, must be file
    /// </summary>
    public const string SourceValue = "file";

    [JsonPropertyName("source")]
    [JsonRequired]
    public string Source { get; init; } = SourceValue;

    /// <summary>
    /// The section of the user&apos;s Telegram Passport which has the issue, one of “utility_bill”, “bank_statement”, “rental_agreement”, “passport_registration”, “temporary_registration”
    /// </summary>
    [JsonPropertyName("type")]
    [JsonRequired]
    public required string Type { get; init; } = null!;

    /// <summary>
    /// Base64-encoded file hash
    /// </summary>
    [JsonPropertyName("file_hash")]
    [JsonRequired]
    public required string FileHash { get; init; } = null!;

    /// <summary>
    /// Error message
    /// </summary>
    [JsonPropertyName("message")]
    [JsonRequired]
    public required string Message { get; init; } = null!;

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Source != SourceValue)
        {
            throw new JsonException("Expected Telegram literal 'file' for field 'source' on PassportElementErrorFile.");
        }

    }
}