// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.3
//   Telegram Bot API release: 2026-08-24
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#august-24-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Describes Telegram Passport data shared with the bot by the user.
/// </summary>
public sealed partial record class PassportData
{
    /// <summary>
    /// Array with information about documents and other Telegram Passport elements that was shared with the bot
    /// </summary>
    [JsonPropertyName("data")]
    [JsonRequired]
    public required IReadOnlyList<EncryptedPassportElement> Data { get; init; } = null!;

    /// <summary>
    /// Encrypted credentials required to decrypt the data
    /// </summary>
    [JsonPropertyName("credentials")]
    [JsonRequired]
    public required EncryptedCredentials Credentials { get; init; } = null!;

}