// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-25T20:26:26.1770012+00:00
//   Source SHA-256: bad109f0fc19b3b0d1703be99fa0161ca066363d8fca62e1165527885add506f
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object represents one size of a photo or a file / sticker thumbnail.
/// </summary>
public sealed partial record class PhotoSize
{
    /// <summary>
    /// Identifier for this file, which can be used to download or reuse the file
    /// </summary>
    [JsonPropertyName("file_id")]
    [JsonRequired]
    public required string FileId { get; init; } = null!;

    /// <summary>
    /// Unique identifier for this file, which is supposed to be the same over time and for different bots. Can&apos;t be used to download or reuse the file.
    /// </summary>
    [JsonPropertyName("file_unique_id")]
    [JsonRequired]
    public required string FileUniqueId { get; init; } = null!;

    /// <summary>
    /// Photo width
    /// </summary>
    [JsonPropertyName("width")]
    [JsonRequired]
    public required long Width { get; init; }

    /// <summary>
    /// Photo height
    /// </summary>
    [JsonPropertyName("height")]
    [JsonRequired]
    public required long Height { get; init; }

    /// <summary>
    /// File size in bytes
    /// </summary>
    [JsonPropertyName("file_size")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? FileSize { get; init; }

}