// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object represents one size of a photo or a file / sticker thumbnail.
/// </summary>
public sealed partial record class PhotoSize
{
    /// <summary>
    /// Identifier for this file, which can be used to download or reuse the file
    /// </summary>
    [JsonPropertyName("file_id")]
    [JsonRequired]
    public required string FileId { get; init; } = null!;

    /// <summary>
    /// Unique identifier for this file, which is supposed to be the same over time and for different bots. Can&apos;t be used to download or reuse the file.
    /// </summary>
    [JsonPropertyName("file_unique_id")]
    [JsonRequired]
    public required string FileUniqueId { get; init; } = null!;

    /// <summary>
    /// Photo width
    /// </summary>
    [JsonPropertyName("width")]
    [JsonRequired]
    public required long Width { get; init; }

    /// <summary>
    /// Photo height
    /// </summary>
    [JsonPropertyName("height")]
    [JsonRequired]
    public required long Height { get; init; }

    /// <summary>
    /// File size in bytes
    /// </summary>
    [JsonPropertyName("file_size")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? FileSize { get; init; }

}