// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object represents an answer of a user in a non-anonymous poll.
/// </summary>
public sealed partial record class PollAnswer
{
    /// <summary>
    /// Unique poll identifier
    /// </summary>
    [JsonPropertyName("poll_id")]
    [JsonRequired]
    public required string PollId { get; init; } = null!;

    /// <summary>
    /// The chat that changed the answer to the poll, if the voter is anonymous
    /// </summary>
    [JsonPropertyName("voter_chat")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Chat? VoterChat { get; init; }

    /// <summary>
    /// The user that changed the answer to the poll, if the voter isn&apos;t anonymous
    /// </summary>
    [JsonPropertyName("user")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public User? User { get; init; }

    /// <summary>
    /// 0-based identifiers of chosen answer options. May be empty if the vote was retracted.
    /// </summary>
    [JsonPropertyName("option_ids")]
    [JsonRequired]
    public required IReadOnlyList<long> OptionIds { get; init; } = null!;

    /// <summary>
    /// Persistent identifiers of the chosen answer options. May be empty if the vote was retracted.
    /// </summary>
    [JsonPropertyName("option_persistent_ids")]
    [JsonRequired]
    public required IReadOnlyList<string> OptionPersistentIds { get; init; } = null!;

}