// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Describes a service message about an option added to a poll.
/// </summary>
public sealed partial record class PollOptionAdded
{
    /// <summary>
    /// Message containing the poll to which the option was added, if known. Note that the Message object in this field will not contain the reply_to_message field even if it itself is a reply.
    /// </summary>
    [JsonPropertyName("poll_message")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public MaybeInaccessibleMessage? PollMessage { get; init; }

    /// <summary>
    /// Unique identifier of the added option
    /// </summary>
    [JsonPropertyName("option_persistent_id")]
    [JsonRequired]
    public required string OptionPersistentId { get; init; } = null!;

    /// <summary>
    /// Option text
    /// </summary>
    [JsonPropertyName("option_text")]
    [JsonRequired]
    public required string OptionText { get; init; } = null!;

    /// <summary>
    /// Special entities that appear in the option_text
    /// </summary>
    [JsonPropertyName("option_text_entities")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<MessageEntity>? OptionTextEntities { get; init; }

}