// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Describes a keyboard button to be used by a user of a Mini App.
/// </summary>
public sealed partial record class PreparedKeyboardButton
{
    /// <summary>
    /// Unique identifier of the keyboard button
    /// </summary>
    [JsonPropertyName("id")]
    [JsonRequired]
    public required string Id { get; init; } = null!;

}