// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object represents the content of a service message, sent whenever a user in the chat triggers a proximity alert set by another user.
/// </summary>
public sealed partial record class ProximityAlertTriggered
{
    /// <summary>
    /// User that triggered the alert
    /// </summary>
    [JsonPropertyName("traveler")]
    [JsonRequired]
    public required User Traveler { get; init; } = null!;

    /// <summary>
    /// User that set the alert
    /// </summary>
    [JsonPropertyName("watcher")]
    [JsonRequired]
    public required User Watcher { get; init; } = null!;

    /// <summary>
    /// The distance between the users
    /// </summary>
    [JsonPropertyName("distance")]
    [JsonRequired]
    public required long Distance { get; init; }

}