// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-25T20:26:26.1770012+00:00
//   Source SHA-256: bad109f0fc19b3b0d1703be99fa0161ca066363d8fca62e1165527885add506f
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object represents the content of a service message, sent whenever a user in the chat triggers a proximity alert set by another user.
/// </summary>
public sealed partial record class ProximityAlertTriggered
{
    /// <summary>
    /// User that triggered the alert
    /// </summary>
    [JsonPropertyName("traveler")]
    [JsonRequired]
    public required User Traveler { get; init; } = null!;

    /// <summary>
    /// User that set the alert
    /// </summary>
    [JsonPropertyName("watcher")]
    [JsonRequired]
    public required User Watcher { get; init; } = null!;

    /// <summary>
    /// The distance between the users
    /// </summary>
    [JsonPropertyName("distance")]
    [JsonRequired]
    public required long Distance { get; init; }

}