// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// A block with a map, corresponding to the custom HTML tag &lt;tg-map&gt;.
/// </summary>
public sealed partial record class RichBlockMap : IJsonOnDeserialized
{
    /// <summary>
    /// Type of the block, always “map”
    /// </summary>
    public const string TypeValue = "map";

    [JsonPropertyName("type")]
    [JsonRequired]
    public string Type { get; init; } = TypeValue;

    /// <summary>
    /// Location of the center of the map
    /// </summary>
    [JsonPropertyName("location")]
    [JsonRequired]
    public required Location Location { get; init; } = null!;

    /// <summary>
    /// Map zoom level; 13-20
    /// </summary>
    [JsonPropertyName("zoom")]
    [JsonRequired]
    public required long Zoom { get; init; }

    /// <summary>
    /// Expected width of the map
    /// </summary>
    [JsonPropertyName("width")]
    [JsonRequired]
    public required long Width { get; init; }

    /// <summary>
    /// Expected height of the map
    /// </summary>
    [JsonPropertyName("height")]
    [JsonRequired]
    public required long Height { get; init; }

    /// <summary>
    /// Caption of the block
    /// </summary>
    [JsonPropertyName("caption")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public RichBlockCaption? Caption { get; init; }

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Type != TypeValue)
        {
            throw new JsonException("Expected Telegram literal 'map' for field 'type' on RichBlockMap.");
        }

    }
}