// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// A block with a mathematical expression in LaTeX format, corresponding to the custom HTML tag &lt;tg-math-block&gt;.
/// </summary>
public sealed partial record class RichBlockMathematicalExpression : IJsonOnDeserialized
{
    /// <summary>
    /// Type of the block, always “mathematical_expression”
    /// </summary>
    public const string TypeValue = "mathematical_expression";

    [JsonPropertyName("type")]
    [JsonRequired]
    public string Type { get; init; } = TypeValue;

    /// <summary>
    /// The mathematical expression in LaTeX format
    /// </summary>
    [JsonPropertyName("expression")]
    [JsonRequired]
    public required string Expression { get; init; } = null!;

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Type != TypeValue)
        {
            throw new JsonException("Expected Telegram literal 'mathematical_expression' for field 'type' on RichBlockMathematicalExpression.");
        }

    }
}