// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// An item of a list.
/// </summary>
public sealed partial record class RichBlockListItem : IJsonOnDeserialized
{
    /// <summary>
    /// Label of the item
    /// </summary>
    [JsonPropertyName("label")]
    [JsonRequired]
    public required string Label { get; init; } = null!;

    /// <summary>
    /// The content of the item
    /// </summary>
    [JsonPropertyName("blocks")]
    [JsonRequired]
    public required IReadOnlyList<RichBlock> Blocks { get; init; } = null!;

    /// <summary>
    /// True, if the item has a checkbox
    /// </summary>
    [JsonPropertyName("has_checkbox")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? HasCheckbox { get; init; }

    /// <summary>
    /// True, if the item has a checked checkbox
    /// </summary>
    [JsonPropertyName("is_checked")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? IsChecked { get; init; }

    /// <summary>
    /// For ordered lists, the numeric value of the item label
    /// </summary>
    [JsonPropertyName("value")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? Value { get; init; }

    /// <summary>
    /// For ordered lists, the type of the item label; must be one of “a” for lowercase letters, “A” for uppercase letters, “i” for lowercase Roman numerals, “I” for uppercase Roman numerals, or “1” for decimal numbers
    /// </summary>
    public const string? TypeValue = "one";

    [JsonPropertyName("type")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Type { get; init; } = TypeValue;

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Type != TypeValue)
        {
            throw new JsonException("Expected Telegram literal 'one' for field 'type' on RichBlockListItem.");
        }

    }
}