// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// A table, corresponding to the HTML tag &lt;table&gt;.
/// </summary>
public sealed partial record class RichBlockTable : IJsonOnDeserialized
{
    /// <summary>
    /// Type of the block, always “table”
    /// </summary>
    public const string TypeValue = "table";

    [JsonPropertyName("type")]
    [JsonRequired]
    public string Type { get; init; } = TypeValue;

    /// <summary>
    /// Cells of the table
    /// </summary>
    [JsonPropertyName("cells")]
    [JsonRequired]
    public required IReadOnlyList<IReadOnlyList<RichBlockTableCell>> Cells { get; init; } = null!;

    /// <summary>
    /// True, if the table has borders
    /// </summary>
    [JsonPropertyName("is_bordered")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? IsBordered { get; init; }

    /// <summary>
    /// True, if the table is striped
    /// </summary>
    [JsonPropertyName("is_striped")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? IsStriped { get; init; }

    /// <summary>
    /// Caption of the table
    /// </summary>
    [JsonPropertyName("caption")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public RichText? Caption { get; init; }

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Type != TypeValue)
        {
            throw new JsonException("Expected Telegram literal 'table' for field 'type' on RichBlockTable.");
        }

    }
}