// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object represents a rich formatted text. Currently, it can be either a String for plain text, an Array of RichText, or any of the following types:
/// </summary>
/// <remarks>
/// RichTextBold
/// RichTextItalic
/// RichTextUnderline
/// RichTextStrikethrough
/// RichTextSpoiler
/// RichTextDateTime
/// RichTextTextMention
/// RichTextSubscript
/// RichTextSuperscript
/// RichTextMarked
/// RichTextCode
/// RichTextCustomEmoji
/// RichTextMathematicalExpression
/// RichTextUrl
/// RichTextEmailAddress
/// RichTextPhoneNumber
/// RichTextBankCardNumber
/// RichTextMention
/// RichTextHashtag
/// RichTextCashtag
/// RichTextBotCommand
/// RichTextAnchor
/// RichTextAnchorLink
/// RichTextReference
/// RichTextReferenceLink
/// Union members: String, Array of RichText, RichTextBold, RichTextItalic, RichTextUnderline, RichTextStrikethrough, RichTextSpoiler, RichTextDateTime, RichTextTextMention, RichTextSubscript, RichTextSuperscript, RichTextMarked, RichTextCode, RichTextCustomEmoji, RichTextMathematicalExpression, RichTextUrl, RichTextEmailAddress, RichTextPhoneNumber, RichTextBankCardNumber, RichTextMention, RichTextHashtag, RichTextCashtag, RichTextBotCommand, RichTextAnchor, RichTextAnchorLink, RichTextReference, RichTextReferenceLink.
/// </remarks>
[JsonConverter(typeof(RichTextJsonConverter))]
public sealed partial record class RichText
{
    private RichText(string value)
    {
        ArgumentNullException.ThrowIfNull(value);
        String = value;
    }

    private RichText(IReadOnlyList<RichText> value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextArray = value;
    }

    private RichText(RichTextBold value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextBold = value;
    }

    private RichText(RichTextItalic value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextItalic = value;
    }

    private RichText(RichTextUnderline value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextUnderline = value;
    }

    private RichText(RichTextStrikethrough value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextStrikethrough = value;
    }

    private RichText(RichTextSpoiler value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextSpoiler = value;
    }

    private RichText(RichTextDateTime value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextDateTime = value;
    }

    private RichText(RichTextTextMention value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextTextMention = value;
    }

    private RichText(RichTextSubscript value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextSubscript = value;
    }

    private RichText(RichTextSuperscript value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextSuperscript = value;
    }

    private RichText(RichTextMarked value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextMarked = value;
    }

    private RichText(RichTextCode value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextCode = value;
    }

    private RichText(RichTextCustomEmoji value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextCustomEmoji = value;
    }

    private RichText(RichTextMathematicalExpression value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextMathematicalExpression = value;
    }

    private RichText(RichTextUrl value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextUrl = value;
    }

    private RichText(RichTextEmailAddress value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextEmailAddress = value;
    }

    private RichText(RichTextPhoneNumber value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextPhoneNumber = value;
    }

    private RichText(RichTextBankCardNumber value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextBankCardNumber = value;
    }

    private RichText(RichTextMention value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextMention = value;
    }

    private RichText(RichTextHashtag value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextHashtag = value;
    }

    private RichText(RichTextCashtag value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextCashtag = value;
    }

    private RichText(RichTextBotCommand value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextBotCommand = value;
    }

    private RichText(RichTextAnchor value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextAnchor = value;
    }

    private RichText(RichTextAnchorLink value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextAnchorLink = value;
    }

    private RichText(RichTextReference value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextReference = value;
    }

    private RichText(RichTextReferenceLink value)
    {
        ArgumentNullException.ThrowIfNull(value);
        RichTextReferenceLink = value;
    }

    /// <summary>
    /// Gets the String value when this instance represents that case.
    /// </summary>
    public string? String { get; }

    /// <summary>
    /// Gets the Array of RichText value when this instance represents that case.
    /// </summary>
    public IReadOnlyList<RichText>? RichTextArray { get; }

    /// <summary>
    /// Gets the RichTextBold value when this instance represents that case.
    /// </summary>
    public RichTextBold? RichTextBold { get; }

    /// <summary>
    /// Gets the RichTextItalic value when this instance represents that case.
    /// </summary>
    public RichTextItalic? RichTextItalic { get; }

    /// <summary>
    /// Gets the RichTextUnderline value when this instance represents that case.
    /// </summary>
    public RichTextUnderline? RichTextUnderline { get; }

    /// <summary>
    /// Gets the RichTextStrikethrough value when this instance represents that case.
    /// </summary>
    public RichTextStrikethrough? RichTextStrikethrough { get; }

    /// <summary>
    /// Gets the RichTextSpoiler value when this instance represents that case.
    /// </summary>
    public RichTextSpoiler? RichTextSpoiler { get; }

    /// <summary>
    /// Gets the RichTextDateTime value when this instance represents that case.
    /// </summary>
    public RichTextDateTime? RichTextDateTime { get; }

    /// <summary>
    /// Gets the RichTextTextMention value when this instance represents that case.
    /// </summary>
    public RichTextTextMention? RichTextTextMention { get; }

    /// <summary>
    /// Gets the RichTextSubscript value when this instance represents that case.
    /// </summary>
    public RichTextSubscript? RichTextSubscript { get; }

    /// <summary>
    /// Gets the RichTextSuperscript value when this instance represents that case.
    /// </summary>
    public RichTextSuperscript? RichTextSuperscript { get; }

    /// <summary>
    /// Gets the RichTextMarked value when this instance represents that case.
    /// </summary>
    public RichTextMarked? RichTextMarked { get; }

    /// <summary>
    /// Gets the RichTextCode value when this instance represents that case.
    /// </summary>
    public RichTextCode? RichTextCode { get; }

    /// <summary>
    /// Gets the RichTextCustomEmoji value when this instance represents that case.
    /// </summary>
    public RichTextCustomEmoji? RichTextCustomEmoji { get; }

    /// <summary>
    /// Gets the RichTextMathematicalExpression value when this instance represents that case.
    /// </summary>
    public RichTextMathematicalExpression? RichTextMathematicalExpression { get; }

    /// <summary>
    /// Gets the RichTextUrl value when this instance represents that case.
    /// </summary>
    public RichTextUrl? RichTextUrl { get; }

    /// <summary>
    /// Gets the RichTextEmailAddress value when this instance represents that case.
    /// </summary>
    public RichTextEmailAddress? RichTextEmailAddress { get; }

    /// <summary>
    /// Gets the RichTextPhoneNumber value when this instance represents that case.
    /// </summary>
    public RichTextPhoneNumber? RichTextPhoneNumber { get; }

    /// <summary>
    /// Gets the RichTextBankCardNumber value when this instance represents that case.
    /// </summary>
    public RichTextBankCardNumber? RichTextBankCardNumber { get; }

    /// <summary>
    /// Gets the RichTextMention value when this instance represents that case.
    /// </summary>
    public RichTextMention? RichTextMention { get; }

    /// <summary>
    /// Gets the RichTextHashtag value when this instance represents that case.
    /// </summary>
    public RichTextHashtag? RichTextHashtag { get; }

    /// <summary>
    /// Gets the RichTextCashtag value when this instance represents that case.
    /// </summary>
    public RichTextCashtag? RichTextCashtag { get; }

    /// <summary>
    /// Gets the RichTextBotCommand value when this instance represents that case.
    /// </summary>
    public RichTextBotCommand? RichTextBotCommand { get; }

    /// <summary>
    /// Gets the RichTextAnchor value when this instance represents that case.
    /// </summary>
    public RichTextAnchor? RichTextAnchor { get; }

    /// <summary>
    /// Gets the RichTextAnchorLink value when this instance represents that case.
    /// </summary>
    public RichTextAnchorLink? RichTextAnchorLink { get; }

    /// <summary>
    /// Gets the RichTextReference value when this instance represents that case.
    /// </summary>
    public RichTextReference? RichTextReference { get; }

    /// <summary>
    /// Gets the RichTextReferenceLink value when this instance represents that case.
    /// </summary>
    public RichTextReferenceLink? RichTextReferenceLink { get; }

    /// <summary>
    /// Creates a RichText value from <c>string</c>.
    /// </summary>
    public static RichText From(string value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(string value)
    {
        return From(value);
    }

    public bool TryGetString(out string? value)
    {
        value = String;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>IReadOnlyList&lt;RichText&gt;</c>.
    /// </summary>
    public static RichText From(IReadOnlyList<RichText> value)
    {
        return new RichText(value);
    }

    public bool TryGetRichTextArray(out IReadOnlyList<RichText>? value)
    {
        value = RichTextArray;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextBold</c>.
    /// </summary>
    public static RichText From(RichTextBold value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextBold value)
    {
        return From(value);
    }

    public bool TryGetRichTextBold(out RichTextBold? value)
    {
        value = RichTextBold;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextItalic</c>.
    /// </summary>
    public static RichText From(RichTextItalic value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextItalic value)
    {
        return From(value);
    }

    public bool TryGetRichTextItalic(out RichTextItalic? value)
    {
        value = RichTextItalic;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextUnderline</c>.
    /// </summary>
    public static RichText From(RichTextUnderline value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextUnderline value)
    {
        return From(value);
    }

    public bool TryGetRichTextUnderline(out RichTextUnderline? value)
    {
        value = RichTextUnderline;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextStrikethrough</c>.
    /// </summary>
    public static RichText From(RichTextStrikethrough value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextStrikethrough value)
    {
        return From(value);
    }

    public bool TryGetRichTextStrikethrough(out RichTextStrikethrough? value)
    {
        value = RichTextStrikethrough;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextSpoiler</c>.
    /// </summary>
    public static RichText From(RichTextSpoiler value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextSpoiler value)
    {
        return From(value);
    }

    public bool TryGetRichTextSpoiler(out RichTextSpoiler? value)
    {
        value = RichTextSpoiler;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextDateTime</c>.
    /// </summary>
    public static RichText From(RichTextDateTime value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextDateTime value)
    {
        return From(value);
    }

    public bool TryGetRichTextDateTime(out RichTextDateTime? value)
    {
        value = RichTextDateTime;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextTextMention</c>.
    /// </summary>
    public static RichText From(RichTextTextMention value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextTextMention value)
    {
        return From(value);
    }

    public bool TryGetRichTextTextMention(out RichTextTextMention? value)
    {
        value = RichTextTextMention;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextSubscript</c>.
    /// </summary>
    public static RichText From(RichTextSubscript value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextSubscript value)
    {
        return From(value);
    }

    public bool TryGetRichTextSubscript(out RichTextSubscript? value)
    {
        value = RichTextSubscript;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextSuperscript</c>.
    /// </summary>
    public static RichText From(RichTextSuperscript value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextSuperscript value)
    {
        return From(value);
    }

    public bool TryGetRichTextSuperscript(out RichTextSuperscript? value)
    {
        value = RichTextSuperscript;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextMarked</c>.
    /// </summary>
    public static RichText From(RichTextMarked value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextMarked value)
    {
        return From(value);
    }

    public bool TryGetRichTextMarked(out RichTextMarked? value)
    {
        value = RichTextMarked;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextCode</c>.
    /// </summary>
    public static RichText From(RichTextCode value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextCode value)
    {
        return From(value);
    }

    public bool TryGetRichTextCode(out RichTextCode? value)
    {
        value = RichTextCode;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextCustomEmoji</c>.
    /// </summary>
    public static RichText From(RichTextCustomEmoji value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextCustomEmoji value)
    {
        return From(value);
    }

    public bool TryGetRichTextCustomEmoji(out RichTextCustomEmoji? value)
    {
        value = RichTextCustomEmoji;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextMathematicalExpression</c>.
    /// </summary>
    public static RichText From(RichTextMathematicalExpression value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextMathematicalExpression value)
    {
        return From(value);
    }

    public bool TryGetRichTextMathematicalExpression(out RichTextMathematicalExpression? value)
    {
        value = RichTextMathematicalExpression;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextUrl</c>.
    /// </summary>
    public static RichText From(RichTextUrl value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextUrl value)
    {
        return From(value);
    }

    public bool TryGetRichTextUrl(out RichTextUrl? value)
    {
        value = RichTextUrl;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextEmailAddress</c>.
    /// </summary>
    public static RichText From(RichTextEmailAddress value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextEmailAddress value)
    {
        return From(value);
    }

    public bool TryGetRichTextEmailAddress(out RichTextEmailAddress? value)
    {
        value = RichTextEmailAddress;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextPhoneNumber</c>.
    /// </summary>
    public static RichText From(RichTextPhoneNumber value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextPhoneNumber value)
    {
        return From(value);
    }

    public bool TryGetRichTextPhoneNumber(out RichTextPhoneNumber? value)
    {
        value = RichTextPhoneNumber;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextBankCardNumber</c>.
    /// </summary>
    public static RichText From(RichTextBankCardNumber value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextBankCardNumber value)
    {
        return From(value);
    }

    public bool TryGetRichTextBankCardNumber(out RichTextBankCardNumber? value)
    {
        value = RichTextBankCardNumber;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextMention</c>.
    /// </summary>
    public static RichText From(RichTextMention value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextMention value)
    {
        return From(value);
    }

    public bool TryGetRichTextMention(out RichTextMention? value)
    {
        value = RichTextMention;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextHashtag</c>.
    /// </summary>
    public static RichText From(RichTextHashtag value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextHashtag value)
    {
        return From(value);
    }

    public bool TryGetRichTextHashtag(out RichTextHashtag? value)
    {
        value = RichTextHashtag;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextCashtag</c>.
    /// </summary>
    public static RichText From(RichTextCashtag value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextCashtag value)
    {
        return From(value);
    }

    public bool TryGetRichTextCashtag(out RichTextCashtag? value)
    {
        value = RichTextCashtag;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextBotCommand</c>.
    /// </summary>
    public static RichText From(RichTextBotCommand value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextBotCommand value)
    {
        return From(value);
    }

    public bool TryGetRichTextBotCommand(out RichTextBotCommand? value)
    {
        value = RichTextBotCommand;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextAnchor</c>.
    /// </summary>
    public static RichText From(RichTextAnchor value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextAnchor value)
    {
        return From(value);
    }

    public bool TryGetRichTextAnchor(out RichTextAnchor? value)
    {
        value = RichTextAnchor;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextAnchorLink</c>.
    /// </summary>
    public static RichText From(RichTextAnchorLink value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextAnchorLink value)
    {
        return From(value);
    }

    public bool TryGetRichTextAnchorLink(out RichTextAnchorLink? value)
    {
        value = RichTextAnchorLink;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextReference</c>.
    /// </summary>
    public static RichText From(RichTextReference value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextReference value)
    {
        return From(value);
    }

    public bool TryGetRichTextReference(out RichTextReference? value)
    {
        value = RichTextReference;
        return value is not null;
    }

    /// <summary>
    /// Creates a RichText value from <c>RichTextReferenceLink</c>.
    /// </summary>
    public static RichText From(RichTextReferenceLink value)
    {
        return new RichText(value);
    }

    public static implicit operator RichText(RichTextReferenceLink value)
    {
        return From(value);
    }

    public bool TryGetRichTextReferenceLink(out RichTextReferenceLink? value)
    {
        value = RichTextReferenceLink;
        return value is not null;
    }

}

file sealed class RichTextJsonConverter : JsonConverter<RichText>
{
    public override RichText Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.String)
        {
            return RichText.From(reader.GetString() ?? throw new JsonException("Expected a string value."));
        }

        if (reader.TokenType == JsonTokenType.StartArray)
        {
            return RichText.From(JsonSerializer.Deserialize<IReadOnlyList<RichText>>(ref reader, options)
                ?? throw new JsonException("Unable to deserialize RichText as Array of RichText."));
        }

        if (reader.TokenType != JsonTokenType.StartObject)
        {
            throw new JsonException("Unable to deserialize RichText: unexpected JSON token.");
        }

        using var document = JsonDocument.ParseValue(ref reader);
        var json = document.RootElement.GetRawText();

        if (document.RootElement.TryGetProperty("type", out var typeElement) && typeElement.ValueKind == JsonValueKind.String)
        {
            var discriminator = typeElement.GetString();
            switch (discriminator)
            {
                case "anchor":
                    return RichText.From(JsonSerializer.Deserialize<RichTextAnchor>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextAnchor."));
                case "anchor_link":
                    return RichText.From(JsonSerializer.Deserialize<RichTextAnchorLink>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextAnchorLink."));
                case "bank_card_number":
                    return RichText.From(JsonSerializer.Deserialize<RichTextBankCardNumber>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextBankCardNumber."));
                case "bold":
                    return RichText.From(JsonSerializer.Deserialize<RichTextBold>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextBold."));
                case "bot_command":
                    return RichText.From(JsonSerializer.Deserialize<RichTextBotCommand>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextBotCommand."));
                case "cashtag":
                    return RichText.From(JsonSerializer.Deserialize<RichTextCashtag>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextCashtag."));
                case "code":
                    return RichText.From(JsonSerializer.Deserialize<RichTextCode>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextCode."));
                case "custom_emoji":
                    return RichText.From(JsonSerializer.Deserialize<RichTextCustomEmoji>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextCustomEmoji."));
                case "date_time":
                    return RichText.From(JsonSerializer.Deserialize<RichTextDateTime>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextDateTime."));
                case "email_address":
                    return RichText.From(JsonSerializer.Deserialize<RichTextEmailAddress>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextEmailAddress."));
                case "hashtag":
                    return RichText.From(JsonSerializer.Deserialize<RichTextHashtag>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextHashtag."));
                case "italic":
                    return RichText.From(JsonSerializer.Deserialize<RichTextItalic>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextItalic."));
                case "marked":
                    return RichText.From(JsonSerializer.Deserialize<RichTextMarked>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextMarked."));
                case "mathematical_expression":
                    return RichText.From(JsonSerializer.Deserialize<RichTextMathematicalExpression>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextMathematicalExpression."));
                case "mention":
                    return RichText.From(JsonSerializer.Deserialize<RichTextMention>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextMention."));
                case "phone_number":
                    return RichText.From(JsonSerializer.Deserialize<RichTextPhoneNumber>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextPhoneNumber."));
                case "reference":
                    return RichText.From(JsonSerializer.Deserialize<RichTextReference>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextReference."));
                case "reference_link":
                    return RichText.From(JsonSerializer.Deserialize<RichTextReferenceLink>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextReferenceLink."));
                case "spoiler":
                    return RichText.From(JsonSerializer.Deserialize<RichTextSpoiler>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextSpoiler."));
                case "strikethrough":
                    return RichText.From(JsonSerializer.Deserialize<RichTextStrikethrough>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextStrikethrough."));
                case "subscript":
                    return RichText.From(JsonSerializer.Deserialize<RichTextSubscript>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextSubscript."));
                case "superscript":
                    return RichText.From(JsonSerializer.Deserialize<RichTextSuperscript>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextSuperscript."));
                case "text_mention":
                    return RichText.From(JsonSerializer.Deserialize<RichTextTextMention>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextTextMention."));
                case "underline":
                    return RichText.From(JsonSerializer.Deserialize<RichTextUnderline>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextUnderline."));
                case "url":
                    return RichText.From(JsonSerializer.Deserialize<RichTextUrl>(json, options)
                        ?? throw new JsonException("Unable to deserialize RichText as RichTextUrl."));
                default:
                    throw new JsonException($"Unknown discriminator value '{discriminator}' for RichText.");
            }
        }

        throw new JsonException("Unable to deserialize RichText from the provided Telegram payload.");
    }

    public override void Write(Utf8JsonWriter writer, RichText value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(value);
        if (value.String is not null)
        {
            JsonSerializer.Serialize(writer, value.String, options);
            return;
        }

        if (value.RichTextArray is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextArray, options);
            return;
        }

        if (value.RichTextBold is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextBold, options);
            return;
        }

        if (value.RichTextItalic is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextItalic, options);
            return;
        }

        if (value.RichTextUnderline is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextUnderline, options);
            return;
        }

        if (value.RichTextStrikethrough is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextStrikethrough, options);
            return;
        }

        if (value.RichTextSpoiler is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextSpoiler, options);
            return;
        }

        if (value.RichTextDateTime is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextDateTime, options);
            return;
        }

        if (value.RichTextTextMention is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextTextMention, options);
            return;
        }

        if (value.RichTextSubscript is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextSubscript, options);
            return;
        }

        if (value.RichTextSuperscript is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextSuperscript, options);
            return;
        }

        if (value.RichTextMarked is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextMarked, options);
            return;
        }

        if (value.RichTextCode is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextCode, options);
            return;
        }

        if (value.RichTextCustomEmoji is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextCustomEmoji, options);
            return;
        }

        if (value.RichTextMathematicalExpression is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextMathematicalExpression, options);
            return;
        }

        if (value.RichTextUrl is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextUrl, options);
            return;
        }

        if (value.RichTextEmailAddress is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextEmailAddress, options);
            return;
        }

        if (value.RichTextPhoneNumber is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextPhoneNumber, options);
            return;
        }

        if (value.RichTextBankCardNumber is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextBankCardNumber, options);
            return;
        }

        if (value.RichTextMention is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextMention, options);
            return;
        }

        if (value.RichTextHashtag is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextHashtag, options);
            return;
        }

        if (value.RichTextCashtag is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextCashtag, options);
            return;
        }

        if (value.RichTextBotCommand is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextBotCommand, options);
            return;
        }

        if (value.RichTextAnchor is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextAnchor, options);
            return;
        }

        if (value.RichTextAnchorLink is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextAnchorLink, options);
            return;
        }

        if (value.RichTextReference is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextReference, options);
            return;
        }

        if (value.RichTextReferenceLink is not null)
        {
            JsonSerializer.Serialize(writer, value.RichTextReferenceLink, options);
            return;
        }

        throw new JsonException("The RichText instance does not contain a union case value.");
    }
}