// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-25T20:26:26.1770012+00:00
//   Source SHA-256: bad109f0fc19b3b0d1703be99fa0161ca066363d8fca62e1165527885add506f
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// A link to a reference.
/// </summary>
public sealed partial record class RichTextReferenceLink : IJsonOnDeserialized
{
    /// <summary>
    /// Type of the rich text, always “reference_link”
    /// </summary>
    public const string TypeValue = "reference_link";

    [JsonPropertyName("type")]
    [JsonRequired]
    public string Type { get; init; } = TypeValue;

    /// <summary>
    /// The link text
    /// </summary>
    [JsonPropertyName("text")]
    [JsonRequired]
    public required RichText Text { get; init; } = null!;

    /// <summary>
    /// The name of the reference
    /// </summary>
    [JsonPropertyName("reference_name")]
    [JsonRequired]
    public required string ReferenceName { get; init; } = null!;

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Type != TypeValue)
        {
            throw new JsonException("Expected Telegram literal 'reference_link' for field 'type' on RichTextReferenceLink.");
        }

    }
}