// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// A mathematical expression.
/// </summary>
public sealed partial record class RichTextMathematicalExpression : IJsonOnDeserialized
{
    /// <summary>
    /// Type of the rich text, always “mathematical_expression”
    /// </summary>
    public const string TypeValue = "mathematical_expression";

    [JsonPropertyName("type")]
    [JsonRequired]
    public string Type { get; init; } = TypeValue;

    /// <summary>
    /// The expression in LaTeX format
    /// </summary>
    [JsonPropertyName("expression")]
    [JsonRequired]
    public required string Expression { get; init; } = null!;

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Type != TypeValue)
        {
            throw new JsonException("Expected Telegram literal 'mathematical_expression' for field 'type' on RichTextMathematicalExpression.");
        }

    }
}