// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// A mention by a username.
/// </summary>
public sealed partial record class RichTextMention : IJsonOnDeserialized
{
    /// <summary>
    /// Type of the rich text, always “mention”
    /// </summary>
    public const string TypeValue = "mention";

    [JsonPropertyName("type")]
    [JsonRequired]
    public string Type { get; init; } = TypeValue;

    /// <summary>
    /// The text
    /// </summary>
    [JsonPropertyName("text")]
    [JsonRequired]
    public required RichText Text { get; init; } = null!;

    /// <summary>
    /// The username
    /// </summary>
    [JsonPropertyName("username")]
    [JsonRequired]
    public required string Username { get; init; } = null!;

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Type != TypeValue)
        {
            throw new JsonException("Expected Telegram literal 'mention' for field 'type' on RichTextMention.");
        }

    }
}