// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Formatted date and time.
/// </summary>
public sealed partial record class RichTextDateTime : IJsonOnDeserialized
{
    /// <summary>
    /// Type of the rich text, always “date_time”
    /// </summary>
    public const string TypeValue = "date_time";

    [JsonPropertyName("type")]
    [JsonRequired]
    public string Type { get; init; } = TypeValue;

    /// <summary>
    /// The text
    /// </summary>
    [JsonPropertyName("text")]
    [JsonRequired]
    public required RichText Text { get; init; } = null!;

    /// <summary>
    /// The Unix time associated with the entity
    /// </summary>
    [JsonPropertyName("unix_time")]
    [JsonRequired]
    public required long UnixTime { get; init; }

    /// <summary>
    /// The string that defines the formatting of the date and time. See date-time entity formatting for more details.
    /// </summary>
    [JsonPropertyName("date_time_format")]
    [JsonRequired]
    public required string DateTimeFormat { get; init; } = null!;

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Type != TypeValue)
        {
            throw new JsonException("Expected Telegram literal 'date_time' for field 'type' on RichTextDateTime.");
        }

    }
}