// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Describes an inline message sent by a Web App on behalf of a user.
/// </summary>
public sealed partial record class SentWebAppMessage
{
    /// <summary>
    /// Identifier of the sent inline message. Available only if there is an inline keyboard attached to the message.
    /// </summary>
    [JsonPropertyName("inline_message_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? InlineMessageId { get; init; }

}