// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-25T20:26:26.1770012+00:00
//   Source SHA-256: bad109f0fc19b3b0d1703be99fa0161ca066363d8fca62e1165527885add506f
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Describes an amount of Telegram Stars.
/// </summary>
public sealed partial record class StarAmount
{
    /// <summary>
    /// Integer amount of Telegram Stars, rounded to 0; can be negative
    /// </summary>
    [JsonPropertyName("amount")]
    [JsonRequired]
    public required long Amount { get; init; }

    /// <summary>
    /// The number of 1/1000000000 shares of Telegram Stars; from -999999999 to 999999999; can be negative if and only if amount is non-positive
    /// </summary>
    [JsonPropertyName("nanostar_amount")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? NanostarAmount { get; init; }

}