// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object represents a sticker set.
/// </summary>
public sealed partial record class StickerSet
{
    /// <summary>
    /// Sticker set name
    /// </summary>
    [JsonPropertyName("name")]
    [JsonRequired]
    public required string Name { get; init; } = null!;

    /// <summary>
    /// Sticker set title
    /// </summary>
    [JsonPropertyName("title")]
    [JsonRequired]
    public required string Title { get; init; } = null!;

    /// <summary>
    /// Type of stickers in the set, currently one of “regular”, “mask”, “custom_emoji”
    /// </summary>
    [JsonPropertyName("sticker_type")]
    [JsonRequired]
    public required string StickerType { get; init; } = null!;

    /// <summary>
    /// List of all set stickers
    /// </summary>
    [JsonPropertyName("stickers")]
    [JsonRequired]
    public required IReadOnlyList<Sticker> Stickers { get; init; } = null!;

    /// <summary>
    /// Sticker set thumbnail in the .WEBP, .TGS, or .WEBM format
    /// </summary>
    [JsonPropertyName("thumbnail")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public PhotoSize? Thumbnail { get; init; }

}