// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Describes the type of a clickable area on a story. Currently, it can be one of
/// </summary>
/// <remarks>
/// StoryAreaTypeLocation
/// StoryAreaTypeSuggestedReaction
/// StoryAreaTypeLink
/// StoryAreaTypeWeather
/// StoryAreaTypeUniqueGift
/// Union members: StoryAreaTypeLocation, StoryAreaTypeSuggestedReaction, StoryAreaTypeLink, StoryAreaTypeWeather, StoryAreaTypeUniqueGift.
/// </remarks>
[JsonConverter(typeof(StoryAreaTypeJsonConverter))]
public sealed partial record class StoryAreaType
{
    private StoryAreaType(StoryAreaTypeLocation value)
    {
        ArgumentNullException.ThrowIfNull(value);
        StoryAreaTypeLocation = value;
    }

    private StoryAreaType(StoryAreaTypeSuggestedReaction value)
    {
        ArgumentNullException.ThrowIfNull(value);
        StoryAreaTypeSuggestedReaction = value;
    }

    private StoryAreaType(StoryAreaTypeLink value)
    {
        ArgumentNullException.ThrowIfNull(value);
        StoryAreaTypeLink = value;
    }

    private StoryAreaType(StoryAreaTypeWeather value)
    {
        ArgumentNullException.ThrowIfNull(value);
        StoryAreaTypeWeather = value;
    }

    private StoryAreaType(StoryAreaTypeUniqueGift value)
    {
        ArgumentNullException.ThrowIfNull(value);
        StoryAreaTypeUniqueGift = value;
    }

    /// <summary>
    /// Gets the StoryAreaTypeLocation value when this instance represents that case.
    /// </summary>
    public StoryAreaTypeLocation? StoryAreaTypeLocation { get; }

    /// <summary>
    /// Gets the StoryAreaTypeSuggestedReaction value when this instance represents that case.
    /// </summary>
    public StoryAreaTypeSuggestedReaction? StoryAreaTypeSuggestedReaction { get; }

    /// <summary>
    /// Gets the StoryAreaTypeLink value when this instance represents that case.
    /// </summary>
    public StoryAreaTypeLink? StoryAreaTypeLink { get; }

    /// <summary>
    /// Gets the StoryAreaTypeWeather value when this instance represents that case.
    /// </summary>
    public StoryAreaTypeWeather? StoryAreaTypeWeather { get; }

    /// <summary>
    /// Gets the StoryAreaTypeUniqueGift value when this instance represents that case.
    /// </summary>
    public StoryAreaTypeUniqueGift? StoryAreaTypeUniqueGift { get; }

    /// <summary>
    /// Creates a StoryAreaType value from <c>StoryAreaTypeLocation</c>.
    /// </summary>
    public static StoryAreaType From(StoryAreaTypeLocation value)
    {
        return new StoryAreaType(value);
    }

    public static implicit operator StoryAreaType(StoryAreaTypeLocation value)
    {
        return From(value);
    }

    public bool TryGetStoryAreaTypeLocation(out StoryAreaTypeLocation? value)
    {
        value = StoryAreaTypeLocation;
        return value is not null;
    }

    /// <summary>
    /// Creates a StoryAreaType value from <c>StoryAreaTypeSuggestedReaction</c>.
    /// </summary>
    public static StoryAreaType From(StoryAreaTypeSuggestedReaction value)
    {
        return new StoryAreaType(value);
    }

    public static implicit operator StoryAreaType(StoryAreaTypeSuggestedReaction value)
    {
        return From(value);
    }

    public bool TryGetStoryAreaTypeSuggestedReaction(out StoryAreaTypeSuggestedReaction? value)
    {
        value = StoryAreaTypeSuggestedReaction;
        return value is not null;
    }

    /// <summary>
    /// Creates a StoryAreaType value from <c>StoryAreaTypeLink</c>.
    /// </summary>
    public static StoryAreaType From(StoryAreaTypeLink value)
    {
        return new StoryAreaType(value);
    }

    public static implicit operator StoryAreaType(StoryAreaTypeLink value)
    {
        return From(value);
    }

    public bool TryGetStoryAreaTypeLink(out StoryAreaTypeLink? value)
    {
        value = StoryAreaTypeLink;
        return value is not null;
    }

    /// <summary>
    /// Creates a StoryAreaType value from <c>StoryAreaTypeWeather</c>.
    /// </summary>
    public static StoryAreaType From(StoryAreaTypeWeather value)
    {
        return new StoryAreaType(value);
    }

    public static implicit operator StoryAreaType(StoryAreaTypeWeather value)
    {
        return From(value);
    }

    public bool TryGetStoryAreaTypeWeather(out StoryAreaTypeWeather? value)
    {
        value = StoryAreaTypeWeather;
        return value is not null;
    }

    /// <summary>
    /// Creates a StoryAreaType value from <c>StoryAreaTypeUniqueGift</c>.
    /// </summary>
    public static StoryAreaType From(StoryAreaTypeUniqueGift value)
    {
        return new StoryAreaType(value);
    }

    public static implicit operator StoryAreaType(StoryAreaTypeUniqueGift value)
    {
        return From(value);
    }

    public bool TryGetStoryAreaTypeUniqueGift(out StoryAreaTypeUniqueGift? value)
    {
        value = StoryAreaTypeUniqueGift;
        return value is not null;
    }

}

file sealed class StoryAreaTypeJsonConverter : JsonConverter<StoryAreaType>
{
    public override StoryAreaType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.StartObject)
        {
            throw new JsonException("Unable to deserialize StoryAreaType: unexpected JSON token.");
        }

        var objectReader = reader;
        ReadObjectMetadata(
            ref objectReader,
            out var typeDiscriminator);

        if (typeDiscriminator is not null)
        {
            switch (typeDiscriminator)
            {
                case "link":
                    return StoryAreaType.From(JsonSerializer.Deserialize<StoryAreaTypeLink>(ref reader, options)
                        ?? throw new JsonException("Unable to deserialize StoryAreaType as StoryAreaTypeLink."));
                case "location":
                    return StoryAreaType.From(JsonSerializer.Deserialize<StoryAreaTypeLocation>(ref reader, options)
                        ?? throw new JsonException("Unable to deserialize StoryAreaType as StoryAreaTypeLocation."));
                case "suggested_reaction":
                    return StoryAreaType.From(JsonSerializer.Deserialize<StoryAreaTypeSuggestedReaction>(ref reader, options)
                        ?? throw new JsonException("Unable to deserialize StoryAreaType as StoryAreaTypeSuggestedReaction."));
                case "unique_gift":
                    return StoryAreaType.From(JsonSerializer.Deserialize<StoryAreaTypeUniqueGift>(ref reader, options)
                        ?? throw new JsonException("Unable to deserialize StoryAreaType as StoryAreaTypeUniqueGift."));
                case "weather":
                    return StoryAreaType.From(JsonSerializer.Deserialize<StoryAreaTypeWeather>(ref reader, options)
                        ?? throw new JsonException("Unable to deserialize StoryAreaType as StoryAreaTypeWeather."));
                default:
                    throw new JsonException($"Unknown discriminator value '{typeDiscriminator}' for StoryAreaType.");
            }
        }

        throw new JsonException("Unable to deserialize StoryAreaType from the provided Telegram payload.");
    }

    private static void ReadObjectMetadata(
        ref Utf8JsonReader reader,
        out string? typeDiscriminator)
    {
        typeDiscriminator = null;

        while (reader.Read())
        {
            if (reader.TokenType == JsonTokenType.EndObject)
            {
                return;
            }

            if (reader.TokenType != JsonTokenType.PropertyName)
            {
                throw new JsonException("Unable to scan union object metadata: expected a JSON property name.");
            }

            if (reader.ValueTextEquals("type"u8))
            {
                if (!reader.Read())
                {
                    throw new JsonException("Unable to scan union object metadata: expected a JSON property value.");
                }

                typeDiscriminator = null;
                if (reader.TokenType == JsonTokenType.String)
                {
                    typeDiscriminator = reader.GetString();
                }

                reader.Skip();
                continue;
            }

            if (!reader.Read())
            {
                throw new JsonException("Unable to scan union object metadata: expected a JSON property value.");
            }

            reader.Skip();
        }

        throw new JsonException("Unable to scan union object metadata: object was not closed.");
    }

    public override void Write(Utf8JsonWriter writer, StoryAreaType value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(value);
        if (value.StoryAreaTypeLocation is not null)
        {
            JsonSerializer.Serialize(writer, value.StoryAreaTypeLocation, options);
            return;
        }

        if (value.StoryAreaTypeSuggestedReaction is not null)
        {
            JsonSerializer.Serialize(writer, value.StoryAreaTypeSuggestedReaction, options);
            return;
        }

        if (value.StoryAreaTypeLink is not null)
        {
            JsonSerializer.Serialize(writer, value.StoryAreaTypeLink, options);
            return;
        }

        if (value.StoryAreaTypeWeather is not null)
        {
            JsonSerializer.Serialize(writer, value.StoryAreaTypeWeather, options);
            return;
        }

        if (value.StoryAreaTypeUniqueGift is not null)
        {
            JsonSerializer.Serialize(writer, value.StoryAreaTypeUniqueGift, options);
            return;
        }

        throw new JsonException("The StoryAreaType instance does not contain a union case value.");
    }
}