// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Describes a story area pointing to a location. Currently, a story can have up to 10 location areas.
/// </summary>
public sealed partial record class StoryAreaTypeLocation : IJsonOnDeserialized
{
    /// <summary>
    /// Type of the area, always “location”
    /// </summary>
    public const string TypeValue = "location";

    [JsonPropertyName("type")]
    [JsonRequired]
    public string Type { get; init; } = TypeValue;

    /// <summary>
    /// Location latitude in degrees
    /// </summary>
    [JsonPropertyName("latitude")]
    [JsonRequired]
    public required double Latitude { get; init; }

    /// <summary>
    /// Location longitude in degrees
    /// </summary>
    [JsonPropertyName("longitude")]
    [JsonRequired]
    public required double Longitude { get; init; }

    /// <summary>
    /// Address of the location
    /// </summary>
    [JsonPropertyName("address")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public LocationAddress? Address { get; init; }

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Type != TypeValue)
        {
            throw new JsonException("Expected Telegram literal 'location' for field 'type' on StoryAreaTypeLocation.");
        }

    }
}