// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object contains basic information about a successful payment. Note that if the buyer initiates a chargeback with the relevant payment provider following this transaction, the funds may be debited from your balance. This is outside of Telegram&apos;s control.
/// </summary>
public sealed partial record class SuccessfulPayment
{
    /// <summary>
    /// Three-letter ISO 4217 currency code, or “XTR” for payments in Telegram Stars
    /// </summary>
    [JsonPropertyName("currency")]
    [JsonRequired]
    public required string Currency { get; init; } = null!;

    /// <summary>
    /// Total price in the smallest units of the currency (integer, not float/double). For example, for a price of US$ 1.45 pass amount = 145. See the exp parameter in currencies.json, it shows the number of digits past the decimal point for each currency (2 for the majority of currencies).
    /// </summary>
    [JsonPropertyName("total_amount")]
    [JsonRequired]
    public required long TotalAmount { get; init; }

    /// <summary>
    /// Bot-specified invoice payload
    /// </summary>
    [JsonPropertyName("invoice_payload")]
    [JsonRequired]
    public required string InvoicePayload { get; init; } = null!;

    /// <summary>
    /// Expiration date of the subscription, in Unix time; for recurring payments only
    /// </summary>
    [JsonPropertyName("subscription_expiration_date")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? SubscriptionExpirationDate { get; init; }

    /// <summary>
    /// True, if the payment is a recurring payment for a subscription
    /// </summary>
    [JsonPropertyName("is_recurring")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? IsRecurring { get; init; }

    /// <summary>
    /// True, if the payment is the first payment for a subscription
    /// </summary>
    [JsonPropertyName("is_first_recurring")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? IsFirstRecurring { get; init; }

    /// <summary>
    /// Identifier of the shipping option chosen by the user
    /// </summary>
    [JsonPropertyName("shipping_option_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ShippingOptionId { get; init; }

    /// <summary>
    /// Order information provided by the user
    /// </summary>
    [JsonPropertyName("order_info")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public OrderInfo? OrderInfo { get; init; }

    /// <summary>
    /// Telegram payment identifier
    /// </summary>
    [JsonPropertyName("telegram_payment_charge_id")]
    [JsonRequired]
    public required string TelegramPaymentChargeId { get; init; } = null!;

    /// <summary>
    /// Provider payment identifier
    /// </summary>
    [JsonPropertyName("provider_payment_charge_id")]
    [JsonRequired]
    public required string ProviderPaymentChargeId { get; init; } = null!;

}