// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Contains information about a suggested post.
/// </summary>
public sealed partial record class SuggestedPostInfo
{
    /// <summary>
    /// State of the suggested post. Currently, it can be one of “pending”, “approved”, “declined”.
    /// </summary>
    [JsonPropertyName("state")]
    [JsonRequired]
    public required string State { get; init; } = null!;

    /// <summary>
    /// Proposed price of the post. If the field is omitted, then the post is unpaid.
    /// </summary>
    [JsonPropertyName("price")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public SuggestedPostPrice? Price { get; init; }

    /// <summary>
    /// Proposed send date of the post. If the field is omitted, then the post can be published at any time within 30 days at the sole discretion of the user or administrator who approves it.
    /// </summary>
    [JsonPropertyName("send_date")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? SendDate { get; init; }

}