// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.2
//   Telegram Bot API release: 2026-07-14
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#july-14-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Describes a withdrawal transaction to the Telegram Ads platform.
/// </summary>
public sealed partial record class TransactionPartnerTelegramAds : IJsonOnDeserialized
{
    /// <summary>
    /// Type of the transaction partner, always “telegram_ads”
    /// </summary>
    public const string TypeValue = "telegram_ads";

    [JsonPropertyName("type")]
    [JsonRequired]
    public string Type { get; init; } = TypeValue;

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Type != TypeValue)
        {
            throw new JsonException("Expected Telegram literal 'telegram_ads' for field 'type' on TransactionPartnerTelegramAds.");
        }

    }
}