// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;
using System.Text.Json;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// Describes the affiliate program that issued the affiliate commission received via this transaction.
/// </summary>
public sealed partial record class TransactionPartnerAffiliateProgram : IJsonOnDeserialized
{
    /// <summary>
    /// Type of the transaction partner, always “affiliate_program”
    /// </summary>
    public const string TypeValue = "affiliate_program";

    [JsonPropertyName("type")]
    [JsonRequired]
    public string Type { get; init; } = TypeValue;

    /// <summary>
    /// Information about the bot that sponsored the affiliate program
    /// </summary>
    [JsonPropertyName("sponsor_user")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public User? SponsorUser { get; init; }

    /// <summary>
    /// The number of Telegram Stars received by the bot for each 1000 Telegram Stars received by the affiliate program sponsor from referred users
    /// </summary>
    [JsonPropertyName("commission_per_mille")]
    [JsonRequired]
    public required long CommissionPerMille { get; init; }

    void IJsonOnDeserialized.OnDeserialized()
    {
        if (Type != TypeValue)
        {
            throw new JsonException("Expected Telegram literal 'affiliate_program' for field 'type' on TransactionPartnerAffiliateProgram.");
        }

    }
}