// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object describes the colors of the backdrop of a unique gift.
/// </summary>
public sealed partial record class UniqueGiftBackdropColors
{
    /// <summary>
    /// The color in the center of the backdrop in RGB format
    /// </summary>
    [JsonPropertyName("center_color")]
    [JsonRequired]
    public required long CenterColor { get; init; }

    /// <summary>
    /// The color on the edges of the backdrop in RGB format
    /// </summary>
    [JsonPropertyName("edge_color")]
    [JsonRequired]
    public required long EdgeColor { get; init; }

    /// <summary>
    /// The color to be applied to the symbol in RGB format
    /// </summary>
    [JsonPropertyName("symbol_color")]
    [JsonRequired]
    public required long SymbolColor { get; init; }

    /// <summary>
    /// The color for the text on the backdrop in RGB format
    /// </summary>
    [JsonPropertyName("text_color")]
    [JsonRequired]
    public required long TextColor { get; init; }

}