// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-18T14:34:01.3212475+00:00
//   Source SHA-256: 8d628bd894ffd733d2978983a94cc4d3eaa3877e30593554647e4849e612fe8d
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object describes the backdrop of a unique gift.
/// </summary>
public sealed partial record class UniqueGiftBackdrop
{
    /// <summary>
    /// Name of the backdrop
    /// </summary>
    [JsonPropertyName("name")]
    [JsonRequired]
    public required string Name { get; init; } = null!;

    /// <summary>
    /// Colors of the backdrop
    /// </summary>
    [JsonPropertyName("colors")]
    [JsonRequired]
    public required UniqueGiftBackdropColors Colors { get; init; } = null!;

    /// <summary>
    /// The number of unique gifts that receive this backdrop for every 1000 gifts upgraded
    /// </summary>
    [JsonPropertyName("rarity_per_mille")]
    [JsonRequired]
    public required long RarityPerMille { get; init; }

}