// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object represents the audios displayed on a user&apos;s profile.
/// </summary>
public sealed partial record class UserProfileAudios
{
    /// <summary>
    /// Total number of profile audios for the target user
    /// </summary>
    [JsonPropertyName("total_count")]
    [JsonRequired]
    public required long TotalCount { get; init; }

    /// <summary>
    /// Requested profile audios
    /// </summary>
    [JsonPropertyName("audios")]
    [JsonRequired]
    public required IReadOnlyList<Audio> Audios { get; init; } = null!;

}