// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Source snapshot: 2026-06-25T20:26:26.1770012+00:00
//   Source SHA-256: bad109f0fc19b3b0d1703be99fa0161ca066363d8fca62e1165527885add506f
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Schema version: 6
//   Generator version: 8
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object represents a Telegram user or bot.
/// </summary>
public sealed partial record class User
{
    /// <summary>
    /// Unique identifier for this user or bot. This number may have more than 32 significant bits and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a 64-bit integer or double-precision float type are safe for storing this identifier.
    /// </summary>
    [JsonPropertyName("id")]
    [JsonRequired]
    public required long Id { get; init; }

    /// <summary>
    /// True, if this user is a bot
    /// </summary>
    [JsonPropertyName("is_bot")]
    [JsonRequired]
    public required bool IsBot { get; init; }

    /// <summary>
    /// User&apos;s or bot&apos;s first name
    /// </summary>
    [JsonPropertyName("first_name")]
    [JsonRequired]
    public required string FirstName { get; init; } = null!;

    /// <summary>
    /// User&apos;s or bot&apos;s last name
    /// </summary>
    [JsonPropertyName("last_name")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? LastName { get; init; }

    /// <summary>
    /// User&apos;s or bot&apos;s username
    /// </summary>
    [JsonPropertyName("username")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Username { get; init; }

    /// <summary>
    /// IETF language tag of the user&apos;s language
    /// </summary>
    [JsonPropertyName("language_code")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? LanguageCode { get; init; }

    /// <summary>
    /// True, if this user is a Telegram Premium user
    /// </summary>
    [JsonPropertyName("is_premium")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? IsPremium { get; init; }

    /// <summary>
    /// True, if this user added the bot to the attachment menu
    /// </summary>
    [JsonPropertyName("added_to_attachment_menu")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? AddedToAttachmentMenu { get; init; }

    /// <summary>
    /// True, if the bot can be invited to groups. Returned only in getMe.
    /// </summary>
    [JsonPropertyName("can_join_groups")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? CanJoinGroups { get; init; }

    /// <summary>
    /// True, if privacy mode is disabled for the bot. Returned only in getMe.
    /// </summary>
    [JsonPropertyName("can_read_all_group_messages")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? CanReadAllGroupMessages { get; init; }

    /// <summary>
    /// True, if the bot supports guest queries from chats it is not a member of. Returned only in getMe.
    /// </summary>
    [JsonPropertyName("supports_guest_queries")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? SupportsGuestQueries { get; init; }

    /// <summary>
    /// True, if the bot supports inline queries. Returned only in getMe.
    /// </summary>
    [JsonPropertyName("supports_inline_queries")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? SupportsInlineQueries { get; init; }

    /// <summary>
    /// True, if the bot can be connected to a user account to manage it. Returned only in getMe.
    /// </summary>
    [JsonPropertyName("can_connect_to_business")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? CanConnectToBusiness { get; init; }

    /// <summary>
    /// True, if the bot has a main Web App. Returned only in getMe.
    /// </summary>
    [JsonPropertyName("has_main_web_app")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? HasMainWebApp { get; init; }

    /// <summary>
    /// True, if the bot has forum topic mode enabled in private chats. Returned only in getMe.
    /// </summary>
    [JsonPropertyName("has_topics_enabled")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? HasTopicsEnabled { get; init; }

    /// <summary>
    /// True, if the bot allows users to create and delete topics in private chats. Returned only in getMe.
    /// </summary>
    [JsonPropertyName("allows_users_to_create_topics")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? AllowsUsersToCreateTopics { get; init; }

    /// <summary>
    /// True, if other bots can be created to be controlled by the bot. Returned only in getMe.
    /// </summary>
    [JsonPropertyName("can_manage_bots")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? CanManageBots { get; init; }

    /// <summary>
    /// True, if the bot supports join request queries and can be assigned to process them. Returned only in getMe.
    /// </summary>
    [JsonPropertyName("supports_join_request_queries")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? SupportsJoinRequestQueries { get; init; }

}