// <auto-generated>
//   This file was generated by TeleFlow.Telegram.SchemaGenerator.
//   Kind: Type
//   Source: https://core.telegram.org/bots/api
//   Telegram Bot API version: 10.1
//   Telegram Bot API release: 2026-06-11
//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#june-11-2026
//   Do not edit this file manually.
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace TeleFlow.Telegram.Schema.Types;

/// <summary>
/// This object represents a service message about new members invited to a video chat.
/// </summary>
public sealed partial record class VideoChatParticipantsInvited
{
    /// <summary>
    /// New members that were invited to the video chat
    /// </summary>
    [JsonPropertyName("users")]
    [JsonRequired]
    public required IReadOnlyList<User> Users { get; init; } = null!;

}